### ISSUE TITLE
Move publisher and dataset redirects to a config file or in the sysadmin interface

### ISSUE THREAD

**Issue by newkdukem** [IATI/ckanext-iati#135]
As mentioned in https://github.com/ViderumGlobal/ckanext-iati/issues/128#issuecomment-318653637 it would be a good idea to move the redirects for dataset and publisher from the [plugins.py](https://github.com/ViderumGlobal/ckanext-iati/blob/master/ckanext/iati/plugins.py) file, to a separate configuration file or as an sysadmin interface. 
The pro in adding a sysadmin web interface over the configuration file approach is that it will remove the process of redeploying the changes.

**Comment by amy-silcock** [comment]
That sounds good, particularly having it on the sysadmin interface. Could you please explain more about what this would look like and involve our end?

@dalepotter do you have views on this?

**Comment by andylolz** [comment]
These redirects are a bit questionable! A bunch of the dataset redirects are broken anyway (in the sense that they redirect to a 404.)

 * https://iatiregistry.org/dataset/minbuza_activities (broken :cry:)
 * https://iatiregistry.org/dataset/ciuk-org (broken :cry:)
 * https://iatiregistry.org/dataset/uncdf-org (broken :cry:)
 * https://iatiregistry.org/dataset/plan_uk-org210613 (broken :cry:)
 * https://iatiregistry.org/dataset/globalintegrity-org (broken :cry:)

Other easter eggs: while https://iatiregistry.org/publisher/wb doesn’t redirect, world bank datasets have this URL shortening feature e.g.
https://iatiregistry.org/dataset/wb-af redirects to https://iatiregistry.org/dataset/worldbank-af

For datasets, I’m not sure if it’s really a good idea to do redirects at all. I’m not sure what the value is? I’d suggest simply removing all the dataset redirects.

For publishers, I guess I can see why it would be a feature… But doing it in a really correct way (i.e. programmatic redirects, auto-appended to whenever a publisher’s ID is changed; preventing reuse of previously used publisher IDs) is presumably a bigger task.

**Comment by dalepotter** [comment]
After discussion with @amy-silcock and @PetyaKangalova this is not regarded as priority for new feature development, so closing this issue for now...
