### ISSUE TITLE
TTFB on `/publisher` is really high

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#148]
The ‘visits’ to ‘updates’ ratio of `/publisher` is probably really high, i.e. many people visit that page compared to how often the content changes. This makes it an ideal candidate for caching! But currently, the time to first byte (TTFB) is something like 5 seconds – suggesting there’s a lot of server-side processing going on, and probably nothing is cached.

Obviously this is not a priority issue… But I visit that page regularly, and every time I hit that 5 second pause, I spend those 5 seconds wondering why the page isn’t cached.

Anecdotally, I think this problem started around the same time the registry switched to use https.

**Comment by dalepotter** [comment]
This issue is linked to https://github.com/ViderumGlobal/ckanext-iati/issues/82

**Comment by andylolz** [comment]
Obviously unsurprising, but here’s a lazy static version that loads in a fraction of the time: https://andylolz.github.io/iati-registry/

Paginating the table and adding a search would speed things up even further.

**Comment by dalepotter** [comment]
@derwas could you comment on if it possible to implement caching on this page and what the implications would be? From there, we can decide how to take this forward as appropriate.

**Comment by andylolz** [comment]
It looks like this might be fixed! 🚀

**Comment by derwas** [comment]
I will look at cashing options for this page and get back to you as soon as possible.

**Comment by Ocre42** [comment]
One of the options would be using pagination, using alphabetised pages instead of simple numbering, so it would still be relatively easy to find publishers. The problem would still be that some pages would have a lot more results than others (A and U for instance), so that's still up for discussion on our next chat.

**Comment by andylolz** [comment]
> so it would still be relatively easy to find publishers

Finding a name in a long list is not a great user experience. Personally I really like a typeahead, like the ones used [here](https://iati-canary.herokuapp.com/#status) and [here](https://andylolz.github.io/org-id-finder/). This could be a nice reusable bit of code, since it could also sit on the IATI Dashboard homepage, too.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop As discussed on this week's call, we have discussed this internally and would like to begin progressing it!

Our thinking is that we would the page to work in a similar way that it does for a publisher's list of dataset (when they have >20 datasets). See WHO's datasets for example: https://iatiregistry.org/publisher/who

So the requirements would be:
- 20 organisations per page
- Option to navigate to first, last, next two, previous two, or user defined page (i.e. as per the following dataset page screenshot, but with the additional option to type a specific page)
![image](https://user-images.githubusercontent.com/46994072/68034514-b35ee200-fcb9-11e9-84f0-b15838f95062.png)
- Dropdown that works in the same way as @andylolz's examples in his latest post

**Comment by andylolz** [comment]
Sounds good.

Have you considered installing varnish (or similar) on the server? That could speed things up a lot, lighten the load on your server, and hopefully wouldn’t involve much bespoke-to-IATI work (since it’s a separate layer).

**Comment by gtkChop** [comment]
@JoshStanleyDevInit

Please see the staging link:
[IATI Staging](https://staging.iatiregistry.org/publisher)

- We are utilizing the existing SOLR index and loading only 20 results at a time.
- Arranged all publishers alphabetically.
- The search field is enabled to search in the entire list (including that is not displayed i.e search across 1082 active publisher).
- Lot faster compared to previous version page.

Please let me know your feedback and will be changing accordingly. Thanks

**Comment by andylolz** [comment]
> Arranged all publishers alphabetically.

A couple of bugs with this.
1. [Order by Name Descending](https://staging.iatiregistry.org/publisher?q=&sort=name+desc) defaults to a table ordered by name (ascending). Makes more sense to default to a table that’s consistent with the "Order by" dropdown.
2. The ordering here is by publishers’ handles, rather than names. So e.g. [order by Name Descending](https://staging.iatiregistry.org/publisher?q=&sort=name+desc) shows "Commune de Zè - Bénin", which obviously starts with a C. But [the publisher’s handle starts with a Z](https://staging.iatiregistry.org/publisher/ze), which is why it’s shown here.

**Comment by JoshStanleyDevInit** [comment]
This is looking great, thanks @gtkChop 

In addition to @andylolz's comments, a point from me:

Using the text  search bar, it seems that you can search either by Publisher Name or Publisher ID. Publisher ID isn't actually a column in the  table so I suggest remove searching by Publisher ID, and add searching by Org ID, as this is a common need for publishers/data users.

**Comment by gtkChop** [comment]
@andylolz Changed the default sort according to the value.

@JoshStanleyDevInit Working on it.

**Comment by gtkChop** [comment]
@JoshStanleyDevInit @Ocre42 @andylolz 

Enabled search - by publisher id, fixed order by ascending and descending by title. And also enabled search for extra fields.

https://staging.iatiregistry.org/publisher

Please let me know if this looks good, I will move to production. Thanks

**Comment by JoshStanleyDevInit** [comment]
@gtkChop search by Org ID looks good, as does the ordering!

Please can you confirm what other search fields you have added? I searched for 'aab', for example, and this returned Windle Trust Kenya. The only instance of 'aab' that I could find in their details was in the Description field, which I don't think you should be able to search by.

Thanks!
Josh

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

Yes currently looks in all extra values of the publisher. That includes description as well.

Can be changed accordingly

**Comment by JoshStanleyDevInit** [comment]
@gtkChop I think it would be preferable if you could only search by IATI Organisation Identifier or Publisher Name

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 
Fixed this.

Now user can search only by the following fields:
- name
- title
- publisher id (org id)

**Comment by JoshStanleyDevInit** [comment]
@gtkChop We have now reviewed this on staging and are happy for it to be deployed to live.

Thanks!

**Comment by gtkChop** [comment]
@JoshStanleyDevInit Deployed. Please reopen if any changes required. Thanks
