### ISSUE TITLE
Spaces in identifier

### ISSUE THREAD

**Issue by notshi** [IATI/ckanext-iati#165]
Following on from [this discussion](https://github.com/OpenDataServices/org-ids/issues/195).

![id_space1](https://user-images.githubusercontent.com/1515961/37522054-c1068350-291a-11e8-87f1-e3323a8321fe.png)

The **Publisher d-portal** link uses the Identifier to direct users to a page on d-portal.
http://d-portal.org/ctrack.html?publisher=BE-BCE_KBO-%200550758080#view=main

In the [example above](https://www.iatiregistry.org/publisher/eip), this d-portal page has no activities.

Note that it isn't obvious there is a space in the Identifier until you see the url (*%20*).

![id_space0](https://user-images.githubusercontent.com/1515961/37522053-c0e41900-291a-11e8-9e8e-ea86f1c76d55.png)

Clicking through the [dataset link](https://www.iatiregistry.org/dataset/eip-ye), the space becomes obvious in the Publisher Identifier.

We also see that there are 2 activities in the dataset.

Removing the space, the url becomes
http://d-portal.org/ctrack.html?publisher=XI-PB-BE550758080#view=main which contains the 2 activities.

Not really a bug report but thought I should bring up this finding.

**Comment by andylolz** [comment]
Related: https://github.com/ViderumGlobal/ckanext-iati/issues/128#issuecomment-366303215

**Comment by dalepotter** [comment]
@derwas could you comment on to what extent it is possible to add validation to this field that would prevent whitespace? - Or perhaps validate the organisation identifier more rigorously, using a regex that we can provide.

**Comment by andylolz** [comment]
> @derwas could you comment on to what extent it is possible to add validation to this field that would prevent whitespace? - Or perhaps validate the organisation identifier more rigorously, using a regex that we can provide.

^^ I gather IATI doesn’t impose a restriction on whitespace in org IDs ([see here](http://iatistandard.org/203/organisation-standard/iati-organisations/iati-organisation/organisation-identifier/#rules), for instance). I tried to discern whether a restriction is imposed higher up, at [org-id.guide](http://org-id.guide) level, but didn’t reach a conclusion (OpenDataServices/org-ids#195). But I’d assume not.

So I’m not sure it would be correct for the registry to add this sort of validation, unless it’s actually a rule.

**Comment by dalepotter** [comment]
FYI The initially reported issue seems to have now been fixed (according to the [dataset page](https://www.iatiregistry.org/dataset/eip-ye)):

![image](https://user-images.githubusercontent.com/8247168/40989572-1f2abaa4-68e6-11e8-8772-98775ebc9c39.png)

**Comment by derwas** [comment]
@dale I will consider a validator for this field but it is not a high priority for the moment.

I also noticed that even after the fix of the whitespace in the id of the organization, d-portal did not pick the correct information about this organization. It only took the correct organization name.

**Comment by notshi** [comment]
This is a strange one to track down ~ turns out there are issues on many levels.

It looks like the activities published by European Institute of Peace has a different publisher identifier for its ```reporting-org @ref```.

![eip](https://user-images.githubusercontent.com/1515961/41157077-5870e922-6b1c-11e8-9e3d-bf644b3c475a.png)

d-portal picks up whatever it finds - in this case, the correct organisation name has no activities associated with it, even if it's listed in the Registry.

**Comment by notshi** [comment]
Raised here - https://github.com/IATI/ckanext-iati/issues/165

**Comment by derwas** [comment]
@notshi do you still have some issues from spaces in identifiers?

**Comment by notshi** [comment]
I've closed this issue as it's brought up in #217 - could we continue the discussion there? Thanks!
