### ISSUE TITLE
Make it clear which branch is run on production, and link to the source code on iatiregistry.org

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#168]
7debfc7b is head of master currently, but the change isn’t reflected on production. This suggests the site isn’t deployed from master, or has local changes on production.

It would be preferable to deploy from master, in order to ensure that the code on github (that’s visible to everyone) reflects the code on production.

**Comment by derwas** [comment]
@andylolz we have migrated the IATI Registry to a new infrastructure. We are still working on the code on a private github repository. The code should be released soon.

**Comment by andylolz** [comment]
Thanks for your response, @derwas.

What’s the reason for making the production code closed source (albeit temporarily)?

I’m concerned because making code closed tends to be a [trapdoor function](https://en.wikipedia.org/wiki/Trapdoor_function). That is, it’s much easier to go from open source to closed source than vice versa.

**Comment by dalepotter** [comment]
The IATI team had a catch up call with @derwas today and there it is planned to bring the production code back onto this repo. 

Initially it will be pushed to a new branch, with the intention of merging down to master, so things can become cleaner once again :-)

**Comment by derwas** [comment]
The production code is running from this repo on the branch ckan-2.8.1. This branch is set as a default branch for now.

**Comment by andylolz** [comment]
> The production code is running from this repo on the branch ckan-2.8.1. 

This still doesn’t seem to be the case, @derwas.

This commit is on the derilinx repo: https://github.com/derilinx/ckanext-iati/commit/9ff52077ccebcf5846f4cfdb0156d6bb931d6703

It’s not on the IATI repo. BUT it has been deployed and marked as fixed: #205.

So production still isn’t deployed from this repo.

**Comment by andylolz** [comment]
https://github.com/derilinx/ckanext-iati still exists (I guess that’s okay, but I don’t see why); https://github.com/IATI/ckanext-iati/tree/master is 18 commits behind ckan-2.8.1 (I guess that’s okay too).

My last comment on here illustrated that at the time, you weren’t deploying from this repo. That is a problem. You didn’t reply, so I’ve no idea whether the current process addresses this.

IATI have a new senior dev now (@samuele-mattiuzzo). So I’ll unsubscribe and leave it to them.

**Comment by samuele-mattiuzzo** [comment]
This can be closed

**Comment by andylolz** [comment]
Revisiting now that this issue is a year old. It remains unresolved. iatiregistry.org is not deployed from this repo as @dalepotter promised ([see](https://github.com/IATI/ckanext-iati/branches)). It looks like it’s deployed from [the derilinx fork](https://github.com/derilinx/ckanext-iati), but who knows.

Ideally there would be a link in the footer of iatiregistry.org or something to show where the production code lives.

At present this is closed source by obfuscation, and it’s not clear why. It’s not in the spirit of CKAN or Open Knowledge at all 😞

**Comment by dalepotter** [comment]
> iatiregistry.org is not deployed from this repo as @dalepotter promised (see)

For full context from my time with the secretariat (albeit that feels like a long time ago now!), it would have been the folks at Derilinx had promised me this, and then one of my jobs was to manage and communicate between them and the community - I'm just the messenger!! 

For what it's worth I 100% agree that the production instance should be deployed from master - that would be the gitflow way of doing it, which was what we were looking for the new supplier to sign up to.

**Comment by andylolz** [comment]
> it would have been the folks at Derilinx had promised me this, and then one of my jobs was to manage and communicate between them and the community - I'm just the messenger!!

Apologies Dale – you’re absolutely right.

**Comment by andylolz** [comment]
I’ve renamed this issue to make it a bit clearer what the ask is.

@samuele-mattiuzzo please can this be reopened, since it hasn’t been fixed yet?

**Comment by andylolz** [comment]
Flagging this again, because I think this issue may again be causing confusion internally. I see a recent PR to the `ckan-2.8.1` branch of this repo. However, I think the current production branch is in fact either the `prod` or the `production` branch of the derilinx repo. I don't think the derilinx repo is linked anywhere - I only know about it because of this ticket.

I'll raise this with Wendy, but just wanted to log something here to try and make it a bit clearer.

**Comment by EricSoroos** [comment]
IATI/master and derilinx/production are now the same commit. ITAI/master is now the default branch in this repo, and should be the base for pull requests. 

Derilinx/prod has been removed to reduce confusion.

**Comment by andylolz** [comment]
That’s brilliant news – many thanks @EricSoroos.

**Comment by andylolz** [comment]
`derilinx/production` is currently 30 commits ahead of `IATI/master`, and is the version deployed to https://iatiregistry.org

@samuele-mattiuzzo please can this be reopened, since it hasn’t been fixed yet?

**Comment by stevieflow** [comment]
> derilinx/production is currently 30 commits ahead of IATI/master, and is the version deployed to https://iatiregistry.org

It's really crucial that this is sorted.  We cannot afford for a vital piece of infrastructure to be so our of synch

**Comment by gtkChop** [comment]
Master should be in sync with the production branch now.

**Comment by andylolz** [comment]
Thanks @gtkChop. But I don’t think that addresses the core problem.

Specifically: please can we be clear about what open source code is running on iatiregistry.org

That means which repo, and which branch. Ideally, this information would be linked from iatiregistry.org, or made clear in some way on that website. That’s the request here.

**Comment by stevieflow** [comment]
I'm unclear why this ticket is closed, when 

> Make it clear which branch is run on production, and link to the source code on iatiregistry.org 

.. has not been addressed

**Comment by samuele-mattiuzzo** [comment]
Agreed with @andylolz and @stevieflow . It's the same thing we have struggled with ourselves, knowing exactly where to look when we need to suggest something or fix bugs. Ideally, for the sake of transparency, a mention somewhere (`README` is probably good enough) what code is running where, which repository and version it refers to and all that is worth doing

**Comment by gtkChop** [comment]
The production code is pulled from the ITAI/master. Updated read me file. Hope this is clear now.

**Comment by gtkChop** [comment]
All the production code will be deployed from the branch master https://github.com/IATI/ckanext-iati

Same as in readme file.
