### ISSUE TITLE
Certificates problem on www.iatiregistry.org

### ISSUE THREAD

**Issue by markbrough** [IATI/ckanext-iati#169]
https://www.iatiregistry.org/ errors `SSL_ERROR_BAD_CERT_DOMAIN`

This is a problem on Firefox, on Chrome it silently redirects to https://iatiregistry.org/

**Comment by mbocevski** [comment]
The Let's encrypt certificate is only issued to the bare domain: iatiregistry.org. www (www.iatiregistry.org) needs to be added as a SAN to the certificate.

**Comment by markbrough** [comment]
Just tested again on Firefox -- https://www.iatiregistry.org now redirects to https://iatiregistry.org and the certificates issue no longer appears -- closing.
