### ISSUE TITLE
Heading on homepage doesn’t make sense

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#170]
![screen shot 2018-03-28 at 18 37 15](https://user-images.githubusercontent.com/464193/38046280-31958eae-32b7-11e8-9ece-6e76dc244e42.png)

I assume the idea was to rebrand from “IATI Data Registry” to “IATI Data” (?) ([see this](https://github.com/IATI/ckanext-iati/commit/a272c63c5aa87f57cd9ecf066f3ed12521ddf36a).) Or to make this the landing page for all IATI Data type things. In any case, I don’t think this idea reached fruition.

The IATI Registry is the place to register IATI data. I’m not sure it’s the place to search or use anything (unless you want raw XML). So I’m not sure what this heading should say. Perhaps just “Welcome to the IATI Registry” ?

**Comment by dalepotter** [comment]
Thanks @andylolz - this is a valid point. Whilst the current sentence is technically correct, it is due to be fully reviewed as part of further work on the IATI websites. This is also in conjunction with the completion of the IATI style guide.

**Comment by andylolz** [comment]
> Whilst the current sentence is technically correct

Fair enough. Closing this one, then.

**Comment by andylolz** [comment]
Looks like I closed this because @dalepotter said it was due to be fixed. 6 months on it’s still there, so reopening.

**Comment by amy-silcock** [comment]
Still waiting for changes to be made on the live Registry. This issue is now being taken care of under this issue: https://github.com/IATI/ckanext-iati/issues/250
