### ISSUE TITLE
Update setup instructions in README

### ISSUE THREAD

**Issue by dalepotter** [IATI/ckanext-iati#172]
@derwas would it be possible to update the setup instructions in the [README file](https://github.com/IATI/ckanext-iati#installation).  

Ideally, I would like a walk through on know the steps that I to set-up and run the code locally?  The end result might be similar to this example: https://github.com/IATI/IATI-Dashboard/#installation

**Comment by derwas** [comment]
The instructions are the same. I would highly appreciate if someone would go through these instructions and let me know if there is anything missing.
