### ISSUE TITLE
Re-enable / fix tests

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#175]
Looks like tests were commented out in c36d4191. The commit message says:

> Comment travis dependencies, uncomment after migration to 2.6.2

But presumably the second part of this (the uncommenting) didn’t happen.

Also, note that the travis badge in the README points to the old repo location, which is why it currently says “build unknown”.

**Comment by Bjwebb** [comment]
Across IATI we're using GitHub Actions now, rather than Travis. It would be good to discuss what tests we could get set up on that.

**Comment by robredpath** [comment]
CKAN standard test suite is run within Derilinx build system

IATI specific tests are in https://github.com/IATI/ckanext-iati/tree/master/ckanext/iati/tests and are run at the same time. If any fail, we expect @cormachallinanderilinx to fix them, or discuss with us.
