### ISSUE TITLE
IATI Org. file- AICS-URL error

### ISSUE THREAD

**Issue by PetyaKangalova** [IATI/ckanext-iati#178]
A publisher-[ AICS](https://iatiregistry.org/publisher/aics?q=organisation+file&sort=metadata_modified+desc)- noticed that their organisation file is showing an error on the IATI Registry (see screenshot below). The file can be accessed fine from the URL provided (http://openaid.aics.gov.it/iati/aics-org.xml). Could you please have a look and fix the error currently showing on their page? Thanks!

![image](https://user-images.githubusercontent.com/24607542/39475025-70780870-4d4e-11e8-9e53-df2c15c9e252.png)

**Comment by andylolz** [comment]
Same for https://iatiregistry.org/dataset/ifcwbg-org

![screen shot 2018-05-01 at 15 11 49](https://user-images.githubusercontent.com/464193/39475893-ff3e4dd2-4d51-11e8-87e7-037b83f97385.png)

**Comment by andylolz** [comment]
Here’s a list, in fact:
 * http://iatiregistry.org/dataset/bmub_iki-998
 * http://iatiregistry.org/dataset/france-af
 * http://iatiregistry.org/dataset/france-bd
 * http://iatiregistry.org/dataset/france-bdi
 * http://iatiregistry.org/dataset/france-bf
 * http://iatiregistry.org/dataset/france-bn
 * http://iatiregistry.org/dataset/france-br
 * http://iatiregistry.org/dataset/france-cg
 * http://iatiregistry.org/dataset/france-cl
 * http://iatiregistry.org/dataset/france-co
 * http://iatiregistry.org/dataset/france-ct
 * http://iatiregistry.org/dataset/france-dji
 * http://iatiregistry.org/dataset/france-do
 * http://iatiregistry.org/dataset/france-ec
 * http://iatiregistry.org/dataset/france-eg
 * http://iatiregistry.org/dataset/france-et
 * http://iatiregistry.org/dataset/france-ga
 * http://iatiregistry.org/dataset/france-gh
 * http://iatiregistry.org/dataset/france-jo
 * http://iatiregistry.org/dataset/france-ke
 * http://iatiregistry.org/dataset/france-kh
 * http://iatiregistry.org/dataset/france-la
 * http://iatiregistry.org/dataset/france-ma
 * http://iatiregistry.org/dataset/france-mdg
 * http://iatiregistry.org/dataset/france-ml
 * http://iatiregistry.org/dataset/france-mm
 * http://iatiregistry.org/dataset/france-mt
 * http://iatiregistry.org/dataset/france-mz
 * http://iatiregistry.org/dataset/france-ne
 * http://iatiregistry.org/dataset/france-ng
 * http://iatiregistry.org/dataset/france-ph
 * http://iatiregistry.org/dataset/france-pk
 * http://iatiregistry.org/dataset/france-sd
 * http://iatiregistry.org/dataset/france-sn
 * http://iatiregistry.org/dataset/france-tgo
 * http://iatiregistry.org/dataset/france-tk
 * http://iatiregistry.org/dataset/france-tn
 * http://iatiregistry.org/dataset/france-tz
 * http://iatiregistry.org/dataset/france-ug
 * http://iatiregistry.org/dataset/france-za
 * http://iatiregistry.org/dataset/ifcwbg-org
 * http://iatiregistry.org/dataset/lead_international-activities
 * http://iatiregistry.org/dataset/somo-29042016
 * http://iatiregistry.org/dataset/somo-org
 * http://iatiregistry.org/dataset/tib-projects

**Comment by derwas** [comment]
Issue fixed!

**Comment by andylolz** [comment]
I clicked some of the links above at random. This one still appears to be broken:
https://iatiregistry.org/dataset/lead_international-activities

Possibly others?

**Comment by derwas** [comment]
The remaining issues are very similar to  #186 
I need to check why the archiver has been developed to parse the xml files using that method. If we decide to implement another method for parsing the xml file all the issues should disappear.

**Comment by andylolz** [comment]
> The remaining issues are very similar to #186

This one isn’t:
https://iatiregistry.org/dataset/lead_international-activities

> If we decide to implement another method for parsing the xml file all the issues should disappear.

In all instances where the error message is:

> Could not parse XML file: Entity 'bull' not defined, line 32, column 72 (line 32)

…the issue has nothing to do with XML parsing. The server is responding with HTML, not XML. If you view the HTML, it looks like this: https://rawgit.com/andylolz/4fdefb723750a0e9379b0e4c34fad392/raw/res.html

If you set the User-Agent header when requesting the XML, it fixes the problem.

**Comment by derwas** [comment]
This issue has been fixed with respect to the updates done on the archiver.
