### ISSUE TITLE
registry appears to use CKAN v2.8.0 alpha (unreleased) ?

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#179]
Very possible I’ve got this wrong, but thought it best I check by raising here.

This page:
https://iatiregistry.org/api/3/action/status_show

Shows:
![screen shot 2018-05-01 at 15 34 21](https://user-images.githubusercontent.com/464193/39476782-2812bb64-4d55-11e8-86f5-ca38aaf86c6f.png)

But this page:
https://github.com/ckan/ckan/releases

Suggests CKAN v2.8.0a is currently a pre-release alpha, which is presumably not yet suitable for production?

**Comment by andylolz** [comment]
Great! Thanks for this.

**Comment by dalepotter** [comment]
The IATI team had a catch up call with @derwas today and we're there is a plan to update the Registry to CKAN 2.8.1 once it is released (next week was mentioned). That will then bring us back onto a stable version, which should allow this ticket to be resolved.

**Comment by derwas** [comment]
The IATI registry is now updated to CKAN v2.8.1

**Comment by andylolz** [comment]
Nice! Thanks
