### ISSUE TITLE
CSV upload- not working

### ISSUE THREAD

**Issue by PetyaKangalova** [IATI/ckanext-iati#181]
There seems to be a bug with the CSV upload functionality on the IATI Registry.

UNOPS and the European Commission have notified us of the errors. I have tested  the CSV files on IATI staging and the live site and I am unable to upload them successfully. The screenshot below shows that the file has been imported and this is not correct.

![iati_index](https://user-images.githubusercontent.com/24607542/39482262-4121cf08-4d66-11e8-88a5-de3af45ac6c6.PNG)

@derwas Zendesk ticket related to [UNOPS file](https://iati.zendesk.com/agent/tickets/6678) and [European Commission one](https://iati.zendesk.com/agent/tickets/6617).

 As this is stopping organisation from successfully uploading their data I have added on the high priority list for a fix.

**Comment by derwas** [comment]
Issue fixed.

**Comment by PetyaKangalova** [comment]
I have just tried uploading a CSV file for the [European Commission - Service for Foreign Policy Instruments](https://iatiregistry.org/publisher/ec-fpi) and I am getting the same error as the user- see below. I am using the correct template and have tested with the attached CSV template in this [Zendesk ticket](https://iati.zendesk.com/agent/tickets/6617). 


![image](https://user-images.githubusercontent.com/24607542/39515344-b854f18c-4df1-11e8-9473-c8234409fca0.png)

There are a number of CSV files that the European Commission need to upload. Could you have a look at let me know once there is a fix as they need to update their data latest this week.

**Comment by PetyaKangalova** [comment]
@derwas Is there any update on the European Commission file? The CSV files need to be uploaded successfully end of this week at the latest. I have updated the[ Zendesk ticket](https://iati.zendesk.com/agent/tickets/6617) as well.

**Comment by derwas** [comment]
@PetyaKangalova All worked well for me! I uploaded the three CSV files without any issues!

<img width="992" alt="screen shot 2018-05-09 at 09 19 25" src="https://user-images.githubusercontent.com/21320874/39803828-2b89432e-536a-11e8-9b6a-4bf490544c82.png">

**Comment by PetyaKangalova** [comment]
Organisation confirmed that upload has been successful so closing the issue.
