### ISSUE TITLE
First published date not filling in

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#182]
Hi,

With our recent publishers sometimes the 'first published date' is being filled in automatically and sometimes it is not.

E.g. for Action Against Hunger Spain this didn't happen.

Where it's not happening we are filling in the date manually.

**Comment by andylolz** [comment]
[Action Against Hunger Spain](https://iatiregistry.org/publisher/acfspain) currently says:

![screen shot 2018-05-14 at 15 45 11](https://user-images.githubusercontent.com/464193/40004538-d359d146-578d-11e8-8bde-5f506f653558.png)

Is that as a result of the manual update?

**Comment by amy-silcock** [comment]
Hi Derilinx,

The 'first published' date is still not always filling in automatically. e.g. https://www.iatiregistry.org/publisher/ads-nyanza 

We've also come across more examples of where the 'first published' date has been updated e.g. AbleChildAfrica first published in 2013. However the Registry is saying 2018: https://www.iatiregistry.org/publisher/ablechildafrica

@dalepotter please can we get this bug looked at and sorted.

**Comment by dalepotter** [comment]
Marking as `Bug` for @derwas to take a look at when next available.

**Comment by derwas** [comment]
I noticed that this happens for new organizations only. This is much related to #161 .
I will investigate further and get back to you as soon as possible.

**Comment by andylolz** [comment]
The API appears to show first published date using at least two different date formats:
https://gist.github.com/andylolz/93ef80cf6cca2217c08adaad2f2f86a3
