### ISSUE TITLE
'Last updated date' not updating

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#183]
Hi,

A tool provider has got in contact to say that the 'last updated date' for a publisher's dataset is not updating automatically.

Further details are in zendesk ticket #6739

**Comment by andylolz** [comment]
Is this a duplicate of #174?

**Comment by derwas** [comment]
@amy-silcock  is this still an open issue?

**Comment by dalepotter** [comment]
As @andylolz this is a duplicate of #174 and #125 so closing this one...
