### ISSUE TITLE
IATI Registry not following re-directs

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#184]
The publisher ECDPM is hosting their file using google storage. It is an xml file.

https://iatiregistry.org/publisher/ecdpm 

However, we think the Registry is not following the redirects to the file. And is rather displaying an error tha says the file is a html document.

Please could you take a look?

The related zendesk ticket is #6677

**Comment by andylolz** [comment]
I think there’s an issue with the permissions settings on the ECDPM google cloud storage.

To check this, try following the steps below:

 1. open a new incognito browser
 2. visit the [ECDPM activity file](https://iatiregistry.org/dataset/ecdpm-act) on the IATI registry
 3. click the download button
 4. see the following sign in page:
    ![screen shot 2018-05-15 at 11 26 27](https://user-images.githubusercontent.com/464193/40051493-ddfda780-5832-11e8-8743-236ad77ffda7.png)

**Comment by andylolz** [comment]
> I think there’s an issue with the permissions settings on the ECDPM google cloud storage.

Looks to be fixed now. Correspondingly, the warning on the registry has disappeared.

**Comment by derwas** [comment]
Thanks @andylolz :)

**Comment by amy-silcock** [comment]
Great, I confirm that it's fixed
