### ISSUE TITLE
Searching data on the IATI Registry

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#188]
Hi,

I've noticed that when you're searching datasets here: https://www.iatiregistry.org/dataset

There are only a small number of publishers which you can sort by. Do we know the reason as to why this is? Or please can we include all the publishers here.

Thanks,

Amy

**Comment by dalepotter** [comment]
Example:
![image](https://user-images.githubusercontent.com/8247168/40989060-9bc494b0-68e4-11e8-8854-7c97ac3b397f.png)

Perhaps this list is hardcoded, since there do not appear to be 750+ publishers in the dropdown :-)

Marking as `Bug` for @derwas to take a look at when next available.

**Comment by derwas** [comment]
Fixed! All publishers should appear on the list now.

**Comment by dalepotter** [comment]
Just checked and this is resolved - great work @derwas
