### ISSUE TITLE
Automatic detection of Org or Activity file

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#190]
Can we have the IATI Registry automatically detecting if a file is an Org file or Activity file?

At the moment some users have entered this incorrectly.

This relates to the zendesk ticket: #4187

**Comment by derwas** [comment]
@amy-silcock  I do not have access to the Zendesk ticket for details.

**Comment by amy-silcock** [comment]
@derwas you should now how access :+1:

**Comment by derwas** [comment]
@amy-silcock the updates on the archiver detect meta-data issues that relate to the type of the file and value provided in the dataset metadata.

I replied to the Zendesk Ticket.
