### ISSUE TITLE
Error message on GAVI Alliance's files

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#193]
Hi,

Please can the error message currently appearing here: https://iatiregistry.org/publisher/gavi be removed? From our end their files are correct.

The zendesk ticket number is: #6966

Thanks.

**Comment by andylolz** [comment]
There’s [a byte order mark (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark) at the start. That’s what’s causing the parsing issues.

I agree with @amy-silcock that the GAVI files are correct. BOMs are optional, so should be handled by the requester prior to parsing.

You can fix the error by decoding with something like `res.decode('utf-8-sig')`.

**Comment by derwas** [comment]
The issue is not anymore relevant.
We can ensure an proper encoding of the files when parsed, but we prefer to make publishers aware of the issue and correct the encoding from their side.

**Comment by andylolz** [comment]
> We can ensure an proper encoding of the files when parsed, but we prefer to make publishers aware of the issue and correct the encoding from their side.

As I mentioned above, the BOM is optional. It’s not incorrect for the publisher to use it.

You can ask publishers not to use it, but you should definitely handle cases where they do.
