### ISSUE TITLE
Remove static pages and update header links

### ISSUE THREAD

**Issue by dalepotter** [IATI/ckanext-iati#194]
As part of a review of content on using IATI data (which took place alongside the transition to a new website), some static content currently on the IATI Registry has been re-drafted and added to the new main iatistandard.org site.

## Updating the header

As such please could the following links be updated in the header:
![image](https://user-images.githubusercontent.com/8247168/42375157-8c65665c-8112-11e8-8035-80922b5db153.png)

`https://iatiregistry.org/using-iati-data` -> `http://iatistandard.org/en/using-data/`

`https://iatiregistry.org/registry-dashboard` -> `http://iatistandard.org/en/guidance/publishing-data/data-quality-/how-to-improve-you-data-quality-with-the-iati-dashboard/`

`https://iatiregistry.org/about` -> `http://iatistandard.org/en/using-data/IATI-tools-and-resources/using-IATI-registry/`

`https://iatiregistry.org/registry-api` -> `http://iatistandard.org/en/using-data/IATI-tools-and-resources/using-IATI-registry/`

`https://iatiregistry.org/help`  -> `http://iatistandard.org/en/guidance/preparing-organisation/organisation-account/how-to-register-with-iati/`

The navigation menu appears to be defined in https://github.com/IATI/ckanext-iati/blob/master/ckanext/iati/theme/templates/header.html#L100-L108 though I couldn't work out how the `href` links are defined (hence not making a PR to resolve this)!

## Deleting static files

As the links will point to the iatistandard.org site, please could the corresponding static files be deleted from the repo. The static files to be deleted are in: https://github.com/IATI/ckanext-iati/tree/master/ckanext/iati/theme/templates/static

## Redirects
Please could server redirects also be setup for the above links, so that anyone who has bookmarked the Registry static pages will be redirected accordingly.

**Comment by derwas** [comment]
All done!

**Comment by dalepotter** [comment]
Resolved in commits derilinx/ckanext-iati@0a98c646292fd8ea8c6619a5080edaf82e3c7bcf derilinx/ckanext-iati@a2a32f41f08af9c115ad912878dcfa2447afa06a derilinx/ckanext-iati@62dc9727b37f567a258ceef9c0ad0bd0a2a98a6f and derilinx/ckanext-iati@67e488b784ff1827f84d6c0181b13f3a93e0c890 - therefore closing this issue.

Thanks @derwas
