### ISSUE TITLE
Broken links on Organisation Form

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#196]
Hi,

With the move to the new IATI website a couple of links on the Organisation Form are now broken. I've created a pull request to fix them: https://github.com/IATI/ckanext-iati/pull/195

**Comment by amy-silcock** [comment]
I've also made the pr here: https://github.com/derilinx/ckanext-iati/pull/1 

Not sure which one we're using?

**Comment by andylolz** [comment]
> Not sure which one we're using?

👍 for this. Situation is unclear currently. Issue tracker in one repo; code deployed from another. Stale code in official repo etc.

**Comment by derwas** [comment]
Hi @amy-silcock , pull request merged!

**Comment by amy-silcock** [comment]
Thanks @derwas
