### ISSUE TITLE
Remove quotation marks from archiver user agent

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#197]
Since the registry moved to live on Derilinx servers, the user agent that the archiver uses has been set to `"IATI (CKAN)"`.

The speech marks in this string cause problems for some publishers’ servers, causing the archiver to be blocked. I’ve demonstrated that in the following gist:
https://gist.github.com/andylolz/382d8f862443b7e75261c5de8dcb1969

This replaces #186, which was very long and confusing.

**Comment by derwas** [comment]
All looks good now!

**Comment by andylolz** [comment]
Yes – I can see (from download logs) that the quotation marks were removed from the user agent. That’s great – closing this.
