### ISSUE TITLE
Data - Register - 404 Not Found Error

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#199]
Hi,

If you click on Data, then Register you currently get the following screen:

![image](https://user-images.githubusercontent.com/27764077/43404375-41d45df4-940f-11e8-92a8-43d88d882f7e.png)

It looks like the link to this page may have changed? You can get to it through your publisher account, as well as the link on the IATI Standard guidance.

Can this be changed please?

**Comment by derwas** [comment]
Fixed thanks to @andylolz :)

**Comment by amy-silcock** [comment]
Thanks both!
