### ISSUE TITLE
Removing admins

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#201]
Hi,

On the Registry there are a number of 'admin' accounts. We are keen to keep the accounts for Amy, Bill, Jahnvi and Petya. 

There are a number of other admin accounts. Can you please remove those which aren't needed or are currently being used by Derilinx? I'm not sure what some of them are / were used for. And don't want to accidentally remove an account which is performing a function.

Thanks,

Amy

**Comment by amy-silcock** [comment]
Hi @derwas,

Please can you also check the user account setting for Wendy Rogers and ensure that she's no longer receiving e-mails from the IATI Registry.

**Comment by derwas** [comment]
Fixed.
