### ISSUE TITLE
IATI Registry 404

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#203]
When I click on 'my data' I get taken back to the 'publishers' page.

This also means as Admins we can't access the list of pending accounts:

![image](https://user-images.githubusercontent.com/27764077/44254706-84b33380-a1fb-11e8-9c83-ab0d53b11264.png)

Please can this be fixed asap

**Comment by derwas** [comment]
Fixed

**Comment by amy-silcock** [comment]
Great, I can now access the correct pages
