### ISSUE TITLE
API

### ISSUE THREAD

**Issue by notshi** [IATI/ckanext-iati#204]
Raised here - https://github.com/devinit/D-Portal/issues/484

Looks like https://iatiregistry.org/api/rest/group has been turned off [when this happened](https://github.com/IATI/ckanext-iati/issues/179).

Will there be updates somewhere public about such things in the future? Mentioning because the readme.md of this repo does not reflect the current version.

**Comment by amy-silcock** [comment]
@derwas any update on this issue?

**Comment by derwas** [comment]
Ongoing!

**Comment by amy-silcock** [comment]
please can we have an update on this one?

**Comment by derwas** [comment]
@notshi sorry for my late comment here, I thought that you already got my answer from Zendesk https://iati.zendesk.com/agent/tickets/7161

I guess you found out already about this https://docs.ckan.org/en/2.8/changelog.html#v-2-8-1-2018-07-25 and https://docs.ckan.org/en/2.8/changelog.html#v-2-8-0-2018-05-09

For performance and security reasons CKAN API V1 and V2 have been removed making only API V3 available. 

This means https://iatiregistry.org/api/rest/group  is no longer available instead you can use https://iatiregistry.org/api/action/organization_list or https://iatiregistry.org/api/action/organization_list?all_fields=true

@amy-silcock I have commented on this on Zendesk https://iati.zendesk.com/agent/tickets/7161 and thought it was communicated properly. Do we need to create an announcement page on iatiregistry.org to cover this widely?

**Comment by notshi** [comment]
@derwas Thanks for the update and confirming what we already worked out. I don't have access to that ticket.

![screenshot-20180924154016-1405x490](https://user-images.githubusercontent.com/1515961/45959757-8e0d9800-c012-11e8-9a97-ba44478cb403.png)

Can you please confirm the following statements from https://github.com/devinit/D-Portal/issues/484#issuecomment-413955812?

> ```
> https://iatiregistry.org/api/3/action/group_show?id=........
> ```
> will get information about the given publisher id
> 
> this information is in a slightly different format to what we used to get and lacks some of the previously data.
> 
> Fun fact, this API is rate limited or maybe just really slow and since I can not see a way to batch it we must perform a separate request for each publisher which takes forever.

1. Is this the best URL to use?
2. Is this API rate limited?
3. Is there a hidden, faster way (batch request) to get information about a publisher?

**Comment by derwas** [comment]
@notshi you have the following API calls that you might consider:
- https://iatiregistry.org/api/action/organization_list for the list of publisher ids
- https://iatiregistry.org/api/action/organization_list?all_fields=true for more details for all organizations (I do not recommend as it might be slow)
- and for more details about a specific organization/publisher, you can use this https://iatiregistry.org/api/action/organization_show?id= {organization id or name}
e.g., : https://iatiregistry.org/api/action/organization_show?id=3f130c79-f65a-4777-a7ea-65d5d9581284 or https://iatiregistry.org/api/action/organization_show?id=ipao-test

**Comment by derwas** [comment]
@notshi there is currently no limited rate for accessing iatiregistry.org.

However, it might happen that the registry becomes subject to DOS attacks, for short periods of time (1 to 2 days) we apply rate limiting policy (10 requests per second).

If you have a fixed IP where you are querying the registry from, you can share it with me and we can whitelist it so that you won't get affected by any rate limits.

**Comment by notshi** [comment]
Many thanks for the info and offer, @derwas - would be good to have a batch solution rather than a whitelist as we don't want to solve it just for d-portal.

**Comment by derwas** [comment]
@notshi I have removed the rate limits for accessing iatiregistry.org.

We are now maintaining a blacklist of potential sources of nuisance that we keep updated regularly.

Do you still experience any issues querying the registry?

**Comment by derwas** [comment]
@notshi can we close this issue?

**Comment by notshi** [comment]
Many thanks, @derwas - we've not noticed any increase in speed accessing the registry so not sure if this has changed anything but appreciate what you've done.
