### ISSUE TITLE
Minor bug when deleting accounts

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#205]
Minor bug which has been left over from the Registry switch.

When you go to delete an account it appears like this:

![image](https://user-images.githubusercontent.com/27764077/44332030-f80aae80-a462-11e8-8d95-f66ed5ecc533.png)

**Comment by derwas** [comment]
Fixed!

**Comment by derwas** [comment]
Check this [commit](https://github.com/IATI/ckanext-iati/commit/9ff52077ccebcf5846f4cfdb0156d6bb931d6703)

**Comment by amy-silcock** [comment]
Great, this is now fixed.
