### ISSUE TITLE
Urgent - user API keys not showing

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#206]
Hi,

When a non-admin is logged in to their account their API key is not showing.

I have tested this with username: dawar account. Logging in with this account does not give access to dawar's API key.

This is preventing the user from publishing to IATI.

**Comment by derwas** [comment]
Fixed.

**Comment by amy-silcock** [comment]
Thanks Wassim, I confirm that users can now see their API keys.

However, when you first log in to the Registry you are greeted with an 'internal server error'. This is happening on both Chrome and IE 11.

![image](https://user-images.githubusercontent.com/27764077/44347746-8a757700-a490-11e8-9a89-9a6fe11fee23.png)

**Comment by derwas** [comment]
Yes, looking at this now!

**Comment by derwas** [comment]
Fixed!

**Comment by amy-silcock** [comment]
Great, these are now working
