### ISSUE TITLE
Help google discover IATI datasets

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#210]
Instructions here:
https://developers.google.com/search/docs/data-types/dataset

This will e.g. help make IATI datasets visible here:
https://toolbox.google.com/datasetsearch

**Comment by andylolz** [comment]
CKAN core dev @amercader [points out on twitter](https://twitter.com/amercader/status/1039256794990866432) that you can switch this on by activating the `structured_data` and `dcat` plugins:
https://github.com/ckan/ckanext-dcat/blob/master/README.md#structured-data

**Comment by derwas** [comment]
@andylolz we have dcat enabled on IATIRegistry. This is enabled from the very beginning! 

You can check the catalog endpoint here: https://iatiregistry.org/catalog.ttl

It is DCAT compliant but for some reason google did not pick it up! I am testing something tools with google webmaster toolkit to see if we get indexed properly.

**Comment by amercader** [comment]
@derwas Google wants you to add the semantic markup embedded directly on the dataset page like [here](https://old.datahub.io/dataset/drc-timber-tracker-data) (look at the source and search for `<script type="application/ld+json">`)

As you are already using the DCAT extension, to enable this you just need to upgrade to the latest ckanext-dcat and add the `structured_data` plugin as @andylolz mentioned.

**Comment by derwas** [comment]
@amercader thanks for the advice! I was thinking of generating a sitemap ad part if ckanext-dcat and/or add and explicit download link in RDF/TTL/JSONLD which should also work! But it looks like your suggestion would be faster to implement ;)

**Comment by derwas** [comment]
All looks good in terms of adding the semantic markup. but this was not enough for google to pick IATI data from the registry. 
Google wants a description field as part of the markup but IATI registry data does not have such metadata field. I can include as part of the structured_data plugin an add-on that generates a description from other fields (e.g., Title)

**Comment by gtkChop** [comment]
Iati datasets are now indexed by Google. Closing the issue.
