### ISSUE TITLE
Misleading number of publishers

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#211]
The total count of IATI publishers on the Registry home page doesn't match the number of publishers on the publisher list:

![image](https://user-images.githubusercontent.com/27764077/45159865-d558f380-b1df-11e8-8c00-1a8c1fe707de.png)

Count of the publishers list: 
![image](https://user-images.githubusercontent.com/27764077/45159923-01747480-b1e0-11e8-92c7-de2d65ac7848.png)

**Comment by derwas** [comment]
@amy-silcock the number of publishers shown on the home page considers only organizations that have at least 1 published dataset hence the text "Organizations have published so far".

**Comment by amy-silcock** [comment]
@derwas Yes, this issue occurred when the total number of publishers on the homepage differed from the number of publishing organisations listed on the publisher page: https://www.iatiregistry.org/publisher

These two pages should be consistent.

**Comment by derwas** [comment]
This could have been an issue with the search index. I do not see any issue now!

<img width="500" alt="screen shot 2018-11-01 at 11 45 12" src="https://user-images.githubusercontent.com/21320874/47850087-f565f700-ddcb-11e8-8f20-e1cea4797dce.png">

**Comment by amy-silcock** [comment]
As the two pages are currently consistent I will close the issue for now.
