### ISSUE TITLE
404/500 Error for organisation We Effect

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#212]
When we try to go to the publisher page (https://iatiregistry.org/publisher/weeffect) for We Effect we're getting a 404 or 500 server error.

We can get round this by going to directly to the URL: https://iatiregistry.org/publisher/edit/weeffect

This is what we've advised the organisation for now as they are trying to publish.

Please can you investigate and let us know why this is occuring, as well as fixing the error.

Thank you, Amy

**Comment by jahnvidave** [comment]
We also get the same error on the user page (https://iatiregistry.org/user/weeffect8020041524) for the same organisation.

Thanks, 
Jahnvi

**Comment by EricSoroos** [comment]
The url in the resource on the dataset https://iatiregistry.org/dataset/weeffect-all_activities is incorrectly encoded (contains a space and ISO-8851 encoded ä, where they should be encoded %20 and %e4) :
 https://csoadmin.sida.se/iati/ We-Effect-(fd-Kooperation-Utan-Gränser).xml

I've rewritten the URL, so now the error is not occurring. I can't check the rewritten url for correctness, since it's behind a login.

**Comment by amy-silcock** [comment]
Hi @EricSoroos,

The error was appearing before the organisation published a file. So why should an encoding error in their IATI file be the issue, as this did not exist when the error first occurred?

We will get in contact with the organisation about their IATI file being behind a login wall. @jahnvidave please can you action this?

**Comment by amy-silcock** [comment]
I've also noticed that the stock image used, for when organisation's don't include their own is missing. Not sure if the bug is linked? 
![image](https://user-images.githubusercontent.com/27764077/45479262-ea80d580-b73d-11e8-8844-7a873cc7c13e.png)

**Comment by jahnvidave** [comment]
We Effect's publisher page and user page are now loading correctly, without error.

Regarding the image - the organisation has provided an Image URL but it is not appearing as it should on their publisher page.

**Comment by andylolz** [comment]
> https://weeffect.se/wp-content/themes/WeEffect-Web/img/logo_white.png

^^ this image is white on a transparent background, which is why it doesn’t show up.

**Comment by derwas** [comment]
I changed the logo with the one suggested by @andylolz

**Comment by amy-silcock** [comment]
Thanks both. The issue is fixed.
