### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#213]
E.g. in firefox:
![screen shot 2018-09-19 at 12 40 56](https://user-images.githubusercontent.com/464193/45751137-56b17c80-bc09-11e8-875b-b901718b34dc.png)

This is a result of 7f538e12. In order to fix this:

https://github.com/IATI/ckanext-iati/blob/95ca04dd46631989297f414379ca53eb41bb31ad/ckanext/iati/theme/less/header.less#L10
^^ This asset should be fetched over HTTPS.

**Comment by andylolz** [comment]
Here’s how it looks in chrome:
![screen shot 2018-09-19 at 16 01 23](https://user-images.githubusercontent.com/464193/45762023-56bf7580-bc25-11e8-845f-7da7faeb6944.png)

**Comment by derwas** [comment]
Pull request merged.
