### ISSUE TITLE
New dataset server error

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#214]
This user (https://iatiregistry.org/user/vivekdeloitte) is getting a 500 server error when trying to add a new dataset on the Registry, from this page (https://iatiregistry.org/dataset/new).

They receive the same error when using both Internet Explorer and Chrome.

This is preventing this organisation from publishing their data.

Please can you investigate this error and find a solution?

Thank you, 
Jahnvi

**Comment by derwas** [comment]
This was fixed by removing and adding the same user to the organization.

**Comment by amy-silcock** [comment]
Thanks @derwas
