### ISSUE TITLE
Spaces in IATI Organisation Identifiers

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#217]
We have several publishers on the Registry whose IATI Org IDs have a space (usually at the end of the identifier). This is preventing the identifiers from being valid, and has an impact on some tools.

I can fix the current identifiers that have spaces (approximately 30 identifiers).

Please can we prevent new publishers from being able to add spaces in the 'IATI Organisation Identifier' field, when they create their account?

Thanks,
Jahnvi

**Comment by notshi** [comment]
This was brought up here https://github.com/IATI/ckanext-iati/issues/165 and ultimately closed as it was also brought up here https://github.com/IATI/ckanext-iati/issues/192#issuecomment-415374125.

**Comment by derwas** [comment]
@jahnvidave @amy-silcock it looks like there are more issues with the filed "publisher_iati_id" some organisations have entered very strange values in there. I am sharing an export of the database via email.

**Comment by derwas** [comment]
I create a new validator to trim spaces from identifiers and publisher names.
Check this [commit](https://github.com/IATI/ckanext-iati/commit/71525ab91400d0c10ccd4ec9cf2cb62a4bd54f3f)

**Comment by derwas** [comment]
@jahnvidave @notshi can we close this issue now?

**Comment by jahnvidave** [comment]
Hi @derwas , I have tested this and it's looking great. Thank you!
