### ISSUE TITLE
Create list of changed org and publisher ids

### ISSUE THREAD

**Issue by notshi** [IATI/ckanext-iati#218]
Brought up here https://github.com/devinit/D-Portal/issues/487

Flag an activity if it does not enforce a standard ruleset rule for publishers to fix so it does not trickle down to tools using the data.

**Comment by amy-silcock** [comment]
Please see the discussion here: https://github.com/devinit/D-Portal/issues/503

Plan is to create a list mapping the changes to org ids and publisher ids. Going forwards this should happen less often not users are prevented from doing so - only admins can change their ids for them.

**Comment by andylolz** [comment]
Below is a list of publisher ID mappings. It would be good to add these as redirects in the registry, and to make this list public somehow.

Old publisher ID | New publisher ID
----|----
echo | ec-echo
amrefuk | amrefha
ausaid | ausgov
mia | mia_india
stromme | stromme_ug
xi-iati-ec_devco | ec-devco
xi-iati-ec_fpi | ec-fpi
xi-iati-ec_near | ec-near
dorcas | dai
solidaridad-china | solidaridad
solidaridad-central-america | solidaridad
solidaridad-east-and-central-africa | solidaridad
solidaridad-netherlands | solidaridad
solidaridad-north-america | solidaridad
solidaridad-south-america | solidaridad
solidaridad-south-and-south-east-asia | solidaridad
solidaridad-southern-africa | solidaridad
solidaridad-west-africa | solidaridad
asfpakistan | _admin
unesco-ihe | ihedelft
cfbt_kenya | edt_kenya
btc-ctb | enabel
diakonia8020173517 | diakonia802017-3517
engenderhealthagoproject | engenderhealth_eth
ifdc_acma | ifdc-us
qrf | qrfed
bmub_iki | bmu_iki
adg | eclosio
dfatd-maecd | gac-amc
ec-elarg | ec-near
gb-cc-220949 | gb-chc-220949
heifer | heifernederland
mrdf | allwecan
aa | f-aids
ihaa | f-aids
hooda | homeoffice
universityofbirmingham | universityofbirmingham_gsdrc
ke-ncb-op2180519381152 | Across
crs_vyf | crs
doh | dhsc
eu | ec-devco
grm | palladium
mcs | mce
deccadmin | beis

**Comment by JoshStanleyDevInit** [comment]
@Ocre42 Just a reminder to look into this one ahead of our next catch up with the Derilinx team

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

Sent an email.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Thanks for sending that across.

@Ocre42 ([here](https://github.com/devinit/D-Portal/issues/503) has suggested that redirects have previously been put in place manually.

It would be great if the redirects could happen automatically when a Publisher ID is changed. As Amy mentioned before, this should happen less now as this field can only be changed by admins.

If previous Publisher IDs could be added to the publisher metadata as well, that would be great.

Please look into whether the above is possible; we can then discuss in more detail in our next catch up.

**Comment by gtkChop** [comment]
@JoshStanleyDevInit @Ocre42 

Created all the redirects for the old publisher's ids to the new one.

**Functionality:**

- [ ] Created a CKAN paster command to pull the old vs new mapping.
- [ ] Once command is executed restart the application, this captures all the mapping automatically.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Thanks for looking at this. A couple of points:

- The redirects themselves look good
- Will any new changes to Publisher IDs redirect automatically?
- I am able to create a new publisher account with another publisher's 'old' publisher id. Can the old publisher ids also be invalid for new publishers?

**Comment by JoshStanleyDevInit** [comment]
@gtkChop As discussed, if we could implement an admin function whereby the latest Publisher ID changes can be pushed to the Derilinx team to implement the redirects, that would be great!

**Comment by JoshStanleyDevInit** [comment]
Hi @gtkChop,

This looks great except I am still able to create a new publisher using one of the 'old' Publisher IDs.

Would it be possible to make all previously used publisher IDs (both current and old) invalid at the point of account creation?

Thanks

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

I think it should be possible. I will have a look.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Thanks. I've tested again this morning:
- Redirects work as expected
- Validation works as expected

I have also changed the Publisher ID of publisher 'JoshTest3' from 'joshtest3' to 'joshtest3changed', and ran the redirect update. Please confirm if this has been received on your side. Thanks.

**Comment by gtkChop** [comment]
@JoshStanleyDevInit Restarted and tested. /publisher/joshtest3 will redirect to /publisher/joshtest3changed


And cannot create publisher with id josh3test.
![pub_id_test](https://user-images.githubusercontent.com/32418025/85131745-4e97ce00-b22f-11ea-9948-ca903f4461c9.png)

**Comment by JoshStanleyDevInit** [comment]
Looks good, thanks @gtkChop. This is now ready to be deployed.

**Comment by gtkChop** [comment]
Done deployed closing this. Please reopen if any issues. Thanks

**Comment by notshi** [comment]
Hi, can you tell us how to access this list? Thanks.

**Comment by notshi** [comment]
Hi, I've just taken a look at a publisher who has changed their id and it looks like the previous publisher and/or org id are not displayed on their page which is what this request is for.

Org id is not a publisher id, by the way. The latter is something that CKAN has assigned and not part of IATI data.

Could you reopen this issue if this has not been done or let me know an alternative way to access this data? Thanks.

**Comment by notshi** [comment]
By the way, in the [guidance](https://iatistandard.org/en/guidance/publishing-data/registering-and-managing-your-organisation-account/updating-your-organisation-details/):

> When you’ve updated your IATI Org ID, add the element <other-identifier> to each activity with the attributes @ref and @type. The @ref attribute should contain your previous IATI Org ID and the @type code should be 'B1', which is 'Previous Reporting Organisation Identifier'.

I suppose we should be able to derive a previous IATI Org id from here as well.

Here is a [live query of the (d-portal) database showing all B1 instances](http://d-portal.org/dquery/#%0Aselect%0A%0Axson-%3E%3E'@ref'%20as%20old_id,%20pid%20as%20new_id,%20count(*)%0A%0Afrom%20xson%20where%20root='/iati-activities/iati-activity/other-identifier'%20and%20xson-%3E%3E'@type'%20=%20'B1'%0Agroup%20by%20xson-%3E%3E'@ref',%20pid%0A%0Aorder%20by%203%20desc%0A%0A%0Alimit%2020000;%0A%0A). You can click 'Run Query' to view it online or click on the 'Download XSON as csv' link to download the data.

We found that XM-DAC-41122 is (mistakenly?) reporting multiple old activity ids rather than one old org id.
