### ISSUE TITLE
IATI Org ID error message when updating publisher account details

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#219]
Hello,

When trying to update the contact email on [Plan International UK's publisher account](https://iatiregistry.org/publisher/plan_uk), we get the following error message:

![image](https://user-images.githubusercontent.com/38503709/46679926-df578300-cbdf-11e8-8521-ba48655ae167.png)

Please can you have a look at resolving this error.

Thanks,
Jahnvi

**Comment by derwas** [comment]
@jahnvidave There is another organization using the same IATI identifier. 
https://iatiregistry.org/publisher/dfid_transactions_for_quarter_july_to_september_2013

Even though it has been removed, its data is still available in the database. 
What you can do is:
- Edit the old organization by changing its IATI identifier
- Then edit the current one.

Let me know if you still need my input for this.

**Comment by jahnvidave** [comment]
Hi Wassim,

Thank you for responding so quickly and for providing this solution.

I have followed your steps and it has worked perfectly.

Many thanks,
Jahnvi
