### ISSUE TITLE
500 Error for organisation Kadaster International

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#222]
When trying to go to the publisher page for Kadaster International (https://iatiregistry.org/publisher/kad), we get a 500 Server Error message.

Please can you investigate this and look into fixing the error?

Thank you, Jahnvi

**Comment by jahnvidave** [comment]
Hi Wassim,

Thank you for fixing this.

Please can you do the same, as a bulk update, for the other publisher accounts that are missing the contact email address?

Many thanks

**Comment by derwas** [comment]
@jahnvidave I will get you a list of those organizations that might have similar issues first then we can agree on a bulk resolution.

**Comment by jahnvidave** [comment]
That's great. Thank you!

**Comment by andylolz** [comment]
How did they register without a contact address? Registration form validation appears to be working:

![screen shot 2018-11-01 at 10 58 43](https://user-images.githubusercontent.com/464193/47848113-31498e00-ddc5-11e8-8730-0b540f5dfb75.png)

**Comment by jahnvidave** [comment]
There are some publisher accounts that were created before the 'Contact Email' field was made mandatory, and since then they have not been updated with an email address.

**Comment by andylolz** [comment]
Thanks @jahnvidave!

Seems surprising that kad would fall into this category, given they only recently started publishing.

Also, none of the other publishers that are missing a contact email address have the same 500 error.

Here are the ones missing a contact email address:
 * [1%Club](https://iatiregistry.org/publisher/onepercentclub): __[Not provided]__
 * [1%Club](https://iatiregistry.org/publisher/onepercentclub): __[Not provided]__
 * [Aasaman Nepal](https://iatiregistry.org/publisher/aasaman): "Email not found"
 * [Abt Associates Inc](https://iatiregistry.org/publisher/abt): "Email not found"
 * [act4africa](https://iatiregistry.org/publisher/act4africa): "Email not found"
 * [ACTED](https://iatiregistry.org/publisher/acted): "Email not found"
 * [ActionAid UK](https://iatiregistry.org/publisher/aauk): "Email not found"
 * [Adaptation Fund](https://iatiregistry.org/publisher/af): __[Not provided]__
 * [ADRA Slovakia](https://iatiregistry.org/publisher/adra): __[Not provided]__
 * [ADRA-UK](https://iatiregistry.org/publisher/adrauk): "Email not found"
 * [Africa Educational Trust](https://iatiregistry.org/publisher/aet): "Email not found"
 * [African Development Bank](https://iatiregistry.org/publisher/afdb): "Email not found"
 * [African Initiatives](https://iatiregistry.org/publisher/ai_1064413): "Email not found"
 * [Alfalit](https://iatiregistry.org/publisher/alfalit): __[Not provided]__
 * [All We Can (formerly Methodist Relief and Development Fund)](https://iatiregistry.org/publisher/allwecan): "Email not found"
 * [Amnesty International The Netherlands](https://iatiregistry.org/publisher/amnesty): __[Not provided]__
 * [Amref Flying Doctors](https://iatiregistry.org/publisher/amrefnl): "Email not found"
 * [Amref Health Africa - UK](https://iatiregistry.org/publisher/amrefha): "Email not found"
 * [ANDA](https://iatiregistry.org/publisher/anda): "Email not found"
 * [ARK (Absolute Return for Kids)](https://iatiregistry.org/publisher/ark): "Email not found"
 * [Asian Development Bank](https://iatiregistry.org/publisher/asdb): "Email not found"
 * [Avanti Communications Plc](https://iatiregistry.org/publisher/ava_admin): __[Not provided]__
 * [Bees Abroad UK](https://iatiregistry.org/publisher/bauk): "Email not found"
 * [Bill & Melinda Gates Foundation](https://iatiregistry.org/publisher/bmgf): "Email not found"
 * [BMB Mott MacDonald](https://iatiregistry.org/publisher/bmb-mm): __[Not provided]__
 * [BRAC UK](https://iatiregistry.org/publisher/bracuk): __[Not provided]__
 * [Canada Department of Finance / Ministère des Finances Canada](https://iatiregistry.org/publisher/finance_canada): "Email not found"
 * [Canada - International Development Research Centre/Centre de recherches pour le développement international](https://iatiregistry.org/publisher/idrccrdi): "Email not found"
 * [Carers Worldwide](https://iatiregistry.org/publisher/cww): "Email not found"
 * [Catholic Relief Services](https://iatiregistry.org/publisher/crs_vyf): "Email not found"
 * [Charity Projects Ltd (Comic Relief)](https://iatiregistry.org/publisher/cprojects): "Email not found"
 * [ChildHope UK](https://iatiregistry.org/publisher/childhopeuk): "Email not found"
 * [Christian Aid](https://iatiregistry.org/publisher/caid): "Email not found"
 * [Coffey International Development](https://iatiregistry.org/publisher/coffey): "Email not found"
 * [Crown Agents Limited](https://iatiregistry.org/publisher/cal): "Email not found"
 * [dance4life](https://iatiregistry.org/publisher/dance4life): "Email not found"
 * [Developments In Literacy Trust UK](https://iatiregistry.org/publisher/diltuk): "Email not found"
 * [Disability Rights Fund](https://iatiregistry.org/publisher/drf): "Email not found"
 * [Eco-fuel Africa Limited](https://iatiregistry.org/publisher/eco-fuelafrica): __[Not provided]__
 * [European Bank for Reconstruction and Development](https://iatiregistry.org/publisher/ebrd): "Email not found"
 * [European Commission - Neighbourhood and Enlargement Negotiations](https://iatiregistry.org/publisher/ec-near): __[Not provided]__
 * [European Commission - Service for Foreign Policy Instruments](https://iatiregistry.org/publisher/ec-fpi): __[Not provided]__
 * [European Investment Bank](https://iatiregistry.org/publisher/eib): __[Not provided]__
 * [Farm Africa](https://iatiregistry.org/publisher/fa): __[Not provided]__
 * [Find Your Feet](https://iatiregistry.org/publisher/fyf): __[Not provided]__
 * [Finland - Ministry of Foreign Affairs](https://iatiregistry.org/publisher/finland_mfa): __[Not provided]__
 * [Friends of the Earth-Ghana](https://iatiregistry.org/publisher/foe-ghana): __[Not provided]__
 * [Gender Links](https://iatiregistry.org/publisher/gl): __[Not provided]__
 * [Global Action Nepal](https://iatiregistry.org/publisher/gan): __[Not provided]__
 * [Global Integrity](https://iatiregistry.org/publisher/globalintegrity): __[Not provided]__
 * [Haitelmex Foundation](https://iatiregistry.org/publisher/49374507): __[Not provided]__
 * [Harakat - Afghanistan Investment Climate Facility Organization](https://iatiregistry.org/publisher/aicfo): __[Not provided]__
 * [HelpAge International UK](https://iatiregistry.org/publisher/ageintl): __[Not provided]__
 * [IMC WORLDWIDE](https://iatiregistry.org/publisher/imcw_admin): __[Not provided]__
 * [Interfaith Youth Partnership](https://iatiregistry.org/publisher/iyp): __[Not provided]__
 * [International Alert](https://iatiregistry.org/publisher/international-alert): __[Not provided]__
 * [International Growth Centre](https://iatiregistry.org/publisher/igc): __[Not provided]__
 * [International Union Against Tuberculosis and Lung Disease](https://iatiregistry.org/publisher/theunion): __[Not provided]__
 * [iPartner India](https://iatiregistry.org/publisher/ip-india): __[Not provided]__
 * [i+solutions](https://iatiregistry.org/publisher/iplussolutions): __[Not provided]__
 * [Itad](https://iatiregistry.org/publisher/itad): "Email not found"
 * [Japan International Cooperation Agency (JICA)](https://iatiregistry.org/publisher/jica): "Email not found"
 * [Jeevika Trust](https://iatiregistry.org/publisher/jeevika_trust): __[Not provided]__
 * [Karuna Trust](https://iatiregistry.org/publisher/karuna): __[Not provided]__
 * [Legislativa](https://iatiregistry.org/publisher/leg_it): __[Not provided]__
 * [Lepra](https://iatiregistry.org/publisher/lepra): "Email not found"
 * [Libertic](https://iatiregistry.org/publisher/libertic-520640889): __[Not provided]__
 * [Link Community Development Scotland](https://iatiregistry.org/publisher/lcds): __[Not provided]__
 * [MAG](https://iatiregistry.org/publisher/mag): __[Not provided]__
 * [Magariro](https://iatiregistry.org/publisher/magariro): __[Not provided]__
 * [Malaria Consortium](https://iatiregistry.org/publisher/malariaconsortium): __[Not provided]__
 * [Manx Times](https://iatiregistry.org/publisher/manxtimes): "Email not found"
 * [MapAction](https://iatiregistry.org/publisher/mapaction): __[Not provided]__
 * [marysmeals](https://iatiregistry.org/publisher/marysmeals): ""
 * [Medical Aid for Palestinians](https://iatiregistry.org/publisher/map): __[Not provided]__
 * [Micro Insurance Academy](https://iatiregistry.org/publisher/mia_india): __[Not provided]__
 * [Ministry of Planning and International Cooperation](https://iatiregistry.org/publisher/yem_mopic): __[Not provided]__
 * [Mondiaal FNV](https://iatiregistry.org/publisher/mondiaalfnv): "Email not found"
 * [mothers2mothers](https://iatiregistry.org/publisher/m2m_sa): __[Not provided]__
 * [NCDO](https://iatiregistry.org/publisher/ncdo): __[Not provided]__
 * [NepalKoGaun](https://iatiregistry.org/publisher/nkg): __[Not provided]__
 * [Norwegian Refugee Council](https://iatiregistry.org/publisher/nrc): "Email not found"
 * [Octavo Solutions Pvt. Ltd.](https://iatiregistry.org/publisher/ospl_2016): __[Not provided]__
 * [oeil mondial international](https://iatiregistry.org/publisher/o-m-i): __[Not provided]__
 * [One Acre Fund](https://iatiregistry.org/publisher/oneacrefund): ""
 * [Opportunity International UK](https://iatiregistry.org/publisher/opportunity-international-uk): __[Not provided]__
 * [Oxfam GB](https://iatiregistry.org/publisher/oxfamgb): "Email not found"
 * [partos](https://iatiregistry.org/publisher/partos_nl): __[Not provided]__
 * [PAX](https://iatiregistry.org/publisher/pax): __[Not provided]__
 * [PHASE Worldwide](https://iatiregistry.org/publisher/phase_worldwide): "Email not found"
 * [Plan Nederland](https://iatiregistry.org/publisher/plannlno): "Email not found"
 * [PSI Europe](https://iatiregistry.org/publisher/psieurope): __[Not provided]__
 * [Pulsar International](https://iatiregistry.org/publisher/pulsarint): __[Not provided]__
 * [PwC](https://iatiregistry.org/publisher/pwc): __[Not provided]__
 * [Rahnuma-Family Planning Assocation of Pakistan](https://iatiregistry.org/publisher/rfpap): __[Not provided]__
 * [RAIN Foundation](https://iatiregistry.org/publisher/rainfoundation): ""
 * [Roughton International Limited](https://iatiregistry.org/publisher/roughton): __[Not provided]__
 * [Royal National Lifeboat Institution (RNLI)](https://iatiregistry.org/publisher/rnli_international): __[Not provided]__
 * [Sabah Integrity Alliance Association (SINAR)](https://iatiregistry.org/publisher/sinar): __[Not provided]__
 * [Samaritan's Purse UK](https://iatiregistry.org/publisher/spuk): __[Not provided]__
 * [SAVE LIFE ON EARTH FOUNDATION (GLOBAL UNIVERSAL INTERNATIONAL) NGO NPO VSO](https://iatiregistry.org/publisher/bhimrao): __[Not provided]__
 * [Save the Children Netherlands](https://iatiregistry.org/publisher/scnl): "Email not found"
 * [Shtrii Shakti](https://iatiregistry.org/publisher/shtrii_shakti): __[Not provided]__
 * [Simprints](https://iatiregistry.org/publisher/simprints): "Email not found"
 * [Social Impact Lab CIC](https://iatiregistry.org/publisher/simlab): "Email not found"
 * [SOS Children's Villages The Netherlands](https://iatiregistry.org/publisher/sosnl): "E-mail not found"
 * [Spain - Ministry of Foreign Affairs and Cooperation](https://iatiregistry.org/publisher/maec): "Email not found"
 * [Stichting Aflatoun International](https://iatiregistry.org/publisher/aflatoun): ""
 * [Stichting Enviu Nederland](https://iatiregistry.org/publisher/enviu): __[Not provided]__
 * [Stichting Humana](https://iatiregistry.org/publisher/humana_houben): __[Not provided]__
 * [StreetInvest](https://iatiregistry.org/publisher/si): __[Not provided]__
 * [Sweden, through Swedish International Development Cooperation Agency (Sida)](https://iatiregistry.org/publisher/sida): "Email not found"
 * [Swiss Tropical and Public Health Institute](https://iatiregistry.org/publisher/swisstph): __[Not provided]__
 * [Tearfund](https://iatiregistry.org/publisher/tearfund): "Email not found"
 * [Terre des Hommes Netherlands](https://iatiregistry.org/publisher/tdh_nl): "Email not found"
 * [The International Children's Trust](https://iatiregistry.org/publisher/theict): __[Not provided]__
 * [The William and Flora Hewlett Foundation](https://iatiregistry.org/publisher/hewlett-foundation): "Email not found"
 * [The World Bank](https://iatiregistry.org/publisher/worldbank): "Email not found"
 * [Triggerise Stichting](https://iatiregistry.org/publisher/triggerise): __[Not provided]__
 * [UK - Scottish Government](https://iatiregistry.org/publisher/scottish_government): "Email not found"
 * [United Nations Central Emergency Response Fund (CERF)](https://iatiregistry.org/publisher/cerf): "Email not found"
 * [United Nations Children's Fund (UNICEF)](https://iatiregistry.org/publisher/unicef): "Email not found"
 * [United Nations Population Fund](https://iatiregistry.org/publisher/unfpa): "Email not found"
 * [Vrutti, Livelihood Resource Centre](https://iatiregistry.org/publisher/vrutti): __[Not provided]__
 * [War Child UK](https://iatiregistry.org/publisher/wcuk): __[Not provided]__
 * [War on Want](https://iatiregistry.org/publisher/waronwant): "Email not found"
 * [WASH Alliance International](https://iatiregistry.org/publisher/wai): ""
 * [WaterAid](https://iatiregistry.org/publisher/wateraid): "Email not found"
 * [Welbodi Partnership](https://iatiregistry.org/publisher/welbodipartnership): __[Not provided]__
 * [Women Win](https://iatiregistry.org/publisher/women_win): __[Not provided]__
 * [World Medical Fund for Children](https://iatiregistry.org/publisher/wmf): __[Not provided]__
 * [World Young Women's Christian Association](https://iatiregistry.org/publisher/wywca): __[Not provided]__
 * [Zing](https://iatiregistry.org/publisher/zing): "Email not found"
 * [ZOA](https://iatiregistry.org/publisher/zoa): "Email not found"

**Comment by amy-silcock** [comment]
Hi, so the lack of e-mail causing an issue on the Registry has occurred a few times. The previous Registry suppliers did a fix by adding some text to blank publisher e-mail fields and this should have been done for all approved accounts without an e-mail address at that time.

It was working for a while and I think as a team we agreed to re-look into this with Derilinx if and when the issue re-occurred.

Previous github issues are here:
https://github.com/IATI/ckanext-iati/issues/111
https://github.com/IATI/ckanext-iati/issues/71

**Comment by derwas** [comment]
For some reason, only this publisher got an issue with the email address not being provided.

There is a list of 71 publishers that do not have this information but there are no server errors generated by visiting their pages. (I have manually checked all of them.)

The solution provided by the previous supplier did not update the database, it simply displayed a warning message on the publisher page. This was not properly picked in the first instance with kad publisher.

I guess we are now all happy to close the issue?

**Comment by andylolz** [comment]
> There is a list of 71 publishers that do not have this information

There’s 133 on this list:
https://gist.github.com/andylolz/9997df4f3eb0bc391bb604b5d4b90ef5

> but there are no server errors generated by visiting their pages

+1, agreed.

> I guess we are now all happy to close the issue?

If this ticket is just about 500 errors, then I agree. Would be cool to improve publisher contact details (I did a lot of the work on this in #71 – glad @amy-silcock has linked to that ticket) but that’s a nice-to-have.

**Comment by samuele-mattiuzzo** [comment]
Possibly late to the party (so please, shout at me or tell me this has already been evaluated and discarded), but would it be possible/feasible without too much hassle to enforce requiredness only at creation level but still allow the email field to be empty/null to not incur in 500 errors anymore (it's fairly standard practice)?

Publishers lacking that value would still have time to update it while not being a cause of server error. Newer publishers would be required at form level to input that value. Once all the stored publishers have an email associated, then the db can be migrated and the requiredness can be enforced there as well.

**Comment by derwas** [comment]
@samuele-mattiuzzo right now, the requiredness of the email address is enforced at the time of creation/update of an organization. In case of empty/null email the following string shows up "Email not found"

**Comment by derwas** [comment]
Regarding the database changes, I prefer to limit access and changes on the database to extreme cases! We never know how CKAN would behave after doing some changes directly on the DB!

**Comment by gtkChop** [comment]
Is the issue still relevant? Closing for now. Please reopen you encounter any further issue. Thanks
