### ISSUE TITLE
IATI Org ID error message when updating Plan Nederland account details

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#223]
Hi,

When [Plan International Netherlands](https://iatiregistry.org/publisher/plannlno) try to update their details on their publisher account, they receive the error message that their 'IATI identifier already exists in the database'.

![image](https://user-images.githubusercontent.com/38503709/47857372-577d2700-dde1-11e8-83c0-a5c52563d80e.png)

They are changing their Publisher Name from Plan Nederland to Plan International Netherlands, and adding an email address and website.

Please can you have a look at this to resolve the error?

Many thanks, Jahnvi

**Comment by derwas** [comment]
@jahnvidave there was an old (deleted) publisher with the same IATI ID : https://iatiregistry.org/publisher/nlno

I have just changed the ID of the old publisher and this should give you the possibility to edit the current one.

**Comment by andylolz** [comment]
Should this query:
https://github.com/IATI/ckanext-iati/blob/372e56531666386d7604ea010463d357bc31057a/ckanext/iati/logic/validators.py#L168-L171

…perhaps include something like:

```python
filter(model.Resource.state != model.State.DELETED)
```

?

**Comment by jahnvidave** [comment]
@derwas Thank you Wassim!!

**Comment by samuele-mattiuzzo** [comment]
@andylolz 's suggestion is perfectly valid, yes. I'm guessing, in case of `Resource.state == DELETED`, we simply overwrite the flagged_as_deleted publisher's data? Would this cause any potential side-effect with pre-existing data?
If not, then the uniqueness check should not take into account non-active results

**Comment by gtkChop** [comment]
Fixed this issue - please check in iati staging. Please let me know if you encounter any issue. Thanks

if publisher_id_exists.state != "deleted" and publisher_id_exists.id != group_id:
        errors[key].append('IATI identifier already exists in the database.')

**Comment by gtkChop** [comment]
@jahnvidave 
Moved the below code to production.
 
if publisher_id_exists.state != "deleted" and publisher_id_exists.id != group_id:
errors[key].append('IATI identifier already exists in the database.')

**Comment by gtkChop** [comment]
Closing the issue. Please reopen if it is still relevant. Thanks
