### ISSUE TITLE
Make organisation title searchable via API

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#226]
It seems it’s currently not possible to search organisations or packages by organisation title. The following will search packages by **organisation name** “afdb”:
https://iatiregistry.org/api/3/action/package_search?q=organization:afdb

…but there’s no way to search by **organisation title** “African Development Bank”.

I raised this on the ckan-dev mailing list, and was told [this would be possible with a plugin](https://lists.okfn.org/pipermail/ckan-dev/2018-December/023009.html).

**Comment by gtkChop** [comment]
@andylolz @JoshStanleyDevInit 

Now the dataset can be searched by organization title - below are the examples. Still in staging and will be moving to production soon.

https://staging.iatiregistry.org/api/action/package_search?fq=extras_org_title:%22African%20Center%20for%20Economic%20Transformation%20(ACET)%22

https://staging.iatiregistry.org/api/action/package_search?fq=extras_org_title:%22Africa%20Educational%20Trust%22

**Comment by JoshStanleyDevInit** [comment]
@gtkChop This looks good, please deploy when you can!

**Comment by gtkChop** [comment]
@JoshStanleyDevInit @Ocre42 

This is deployed in prod. However, needs to reindex the data in production. This may take some time (approximate: 20 minutes) and no data will be visible on the site during this time. 

Could you please let me know the suitable time of the day to go on with this?

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Apologies for the delayed reply to this. To ensure that we are available to respond to any problems, please can the re-indexing take place early on Monday or Tuesday next week?

Thanks

**Comment by gtkChop** [comment]
@JoshStanleyDevInit @Ocre42 Reindexed prod. Please see the working search functionality by title. Thanks

- https://iatiregistry.org/api/action/package_search?fq=extras_org_title:"Abt Britain Limited"
- https://iatiregistry.org/api/action/package_search?fq=extras_org_title:"Acid Survivors Foundation"
- https://iatiregistry.org/api/action/package_search?fq=extras_org_title:"ACTION AGAINST HUNGER SPAIN"
- https://iatiregistry.org/api/action/package_search?fq=extras_org_title:"action against hunger spain"
- https://iatiregistry.org/api/action/package_search?fq=extras_org_title:"actionaid"

**Comment by JoshStanleyDevInit** [comment]
Looks good @gtkChop!

**Comment by gtkChop** [comment]
Please reopen if nay issue with this.
