### ISSUE TITLE
Re-set password button not working

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#228]
A user has been struggling to reset their password. They're getting an error message that they have multiple accounts. However, I can only find one account attached to their e-mail address.

Further details are in the zendesk ticket: 7745

Please can you have a look?

**Comment by amy-silcock** [comment]
Please can this issue be looked at asap. It is affecting our users.

**Comment by gtkChop** [comment]
Password reset by email is working well.

**Comment by gtkChop** [comment]
Closing for now. Please reopen if any issues. Thanks
