### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#229]
Hi, 

When a publisher account is created please can we make the option to select a license mandatory? Or just take out the 'license not specified' option?

**Comment by siemvaessen** [comment]
@amy-silcock what licensing options are currently available? Closed licensing should not be in a list, seeing IATI data is ont supposed to be closed as per IATI guidance: 

["As an open data standard, IATI requires you to make your data available under an open licence so it can be freely used. This is central to improving transparency and efficiency in all development cooperation and humanitarian work."  ](https://iatistandard.org/en/guidance/preparing-organisation/organisation-data-publication/how-to-license-your-data/)

**Comment by amy-silcock** [comment]
@siemvaessen if you log into the Registry and go to 'manage' on your publisher account. You can see the dropdown list.

**Comment by andylolz** [comment]
Big +1 on this ticket (which relates to current datastore discussions).

> please can we make the option to select a license mandatory? Or just take out the 'license not specified' option?

^^ I think this should be an “and”, not an “or”. I.e. the license field should be mandatory, and the “license not specified” option should be removed.

**Comment by siemvaessen** [comment]
@andylolz should we tie this list into that discussion? Or too detailed?

**Comment by PetyaKangalova** [comment]
Linking to the latest post: https://discuss.iatistandard.org/t/iati-data-licensing-for-unencumbered-data-use/1651/8

We want to make the field mandatory as soon as possible. Once the updated list has been agreed by the community, we need to look at options for those publishers affected by the changes- see step 3 in the post.

**Comment by gtkChop** [comment]
Implemented license functionality in production. Please reopen if you find any issues. Thanks

**Comment by siemvaessen** [comment]
@PetyaKangalova how is this reflected in the Registry? Can we check this?

**Comment by PetyaKangalova** [comment]
@siemvaessen  when an organisation creates a Publisher account it is now mandatory to select a license.

The selected license is listed under each dataset (see example below): https://iatiregistry.org/dataset/undp-afg

![image](https://user-images.githubusercontent.com/24607542/86121804-968be000-bace-11ea-8882-52739ea46abc.png)
