### ISSUE TITLE
unesco-org: incorrect filetype metadata

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#231]
[unesco-org](https://iatiregistry.org/dataset/unesco-org) is an activity dataset, but the registry metadata says it’s an organisation dataset:

![screenshot 2019-01-15 at 11 42 55](https://user-images.githubusercontent.com/464193/51178521-ba4b6e00-18ba-11e9-808d-dc9d2942b8b3.png)

There’s a notice saying “Check the filetype metadata”. Isn’t this piece of metadata set automatically?

**Comment by gtkChop** [comment]
If we see the dataset it shows file type is "iati activities". However, the metadata given is "organization".  (file type is given by the user while adding a dataset).

https://iatiregistry.org/api/action/package_show?id=unesco-org

**Comment by andylolz** [comment]
> (file type is given by the user while adding a dataset).

^^ I don’t think it should be set by the user. That’s my point. I think it should be set automatically. It’s really easy to determine the filetype from the root XML node. Asking the user to set the filetype just introduces the possibility of errors like this.

**Comment by gtkChop** [comment]
@amy-silcock 
https://iatiregistry.org/publisher/unesco

This publisher two activity dataset - 
Dataset with the title - "IATI Organisation Standard" - is actually an activity file. Could you please check with the publisher? Thanks

**Comment by andylolz** [comment]
This is fixed! :clap:

**Comment by andylolz** [comment]
This is fixed! :clap: Thanks both!
