### ISSUE TITLE
First published date logic

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#232]
Hi Swaroop,

Looking at one of our new IATI publishers, the 'First published date' on their Registry account doesn't seem to match any of the dates relating to when their file was published.

e.g. [African Revival](https://iatiregistry.org/publisher/africanrevival):
First published date: 13 January 2019
Activity stream shows the dataset was created on 15 Jan, then deleted and re-published on 17 Jan.
In the file itself, the generated date is 17 Jan.

[This is an anomaly, and most new publishers do have the correct 'First published date'.]

I was hoping to understand the logic behind the 'First published date', so I can understand where these dates come from?

Many thanks,
Jahnvi

**Comment by gtkChop** [comment]
@jahnvidave 

First published date is the metadata, that can be filled while creating a new publisher or can be edited.

However, the first published date is not a mandatory field.

If the first published date is missing, we take the date from the first resource created_date.

Hope this helps. Thanks

**Comment by jahnvidave** [comment]
Thank you for your reply Swaroop.

> If the first published date is missing, we take the date from the first resource created_date.

This is really helpful, thanks for the explanation.

**Comment by andylolz** [comment]
Why doesn’t it always come from the earliest resource created_date? Why allow the publisher to create or edit it?

The [UNOPS publisher page](https://iatiregistry.org/publisher/unops) says they first published on 29 August 2018. However, their earliest resource created_date is 3 October 2011. And in fact, the `publisher_first_publish_date` in the metadata says "03.10.2011" which (notwithstanding being a weird and ambiguous way to store a date) is correct. Where has 29 August 2018 come from?
