### ISSUE TITLE
Existing user account validation - Create new user

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#234]
Should not allow to create a new user account if email/username already exits

**Comment by gtkChop** [comment]
#235

**Comment by gtkChop** [comment]
Stop User creating a new account if email already exists. i.e. One email can have only one user name.

**Comment by deirdrelee** [comment]
Derilinx to identify how much work it would be to provide an error msg / send an email to a user if they try to log in with an email that is associated with multiple address

**Comment by JoshStanleyDevInit** [comment]
Hi all,

Please note that ZD Ticket #8037 is an example of this issue presenting itself to a user.

Thanks,
Josh

**Comment by gtkChop** [comment]
Implemented in staging - 

**Functionality:**

- [ ] User password reset option with email or username.
- [ ] Existing user validation by username or email (if the email exists do not allow the user to create a new user. (i.e. validation for both username and email).

Note: Testing in progress.

@JoshStanleyDevInit if this functionality described above looks good, then I will test and deploy to prod.  Thanks

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Please advise when this is ready for testing on staging. Thanks :)

**Comment by JoshStanleyDevInit** [comment]
@gtkChop 

Not allowing a user to create multiple accounts using the same email address looks good.

I do not seem to be able to reset my password using my email address though; see screenshot:

![image](https://user-images.githubusercontent.com/46994072/76960567-9f87e580-6913-11ea-82e8-4fbada80e589.png)

**Comment by gtkChop** [comment]
@JoshStanleyDevInit  There was a bug due to branch splitt. However, fixed now. tested reset with different accounts.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop I can still reset my password using my username but can't seem to do it using my email address.

**Comment by gtkChop** [comment]
@JoshStanleyDevInit I tried now resetting my password both with username and password and it worked (I received an email notification). 

Is it the same email that you have an account with? I am not sure about the error message that you are gitting.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop retested this and it works for both username and email address - so this is ready to deploy.

Thanks!

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

Deployed. Tested prod. Received email for reset by email id and username.
