### ISSUE TITLE
Server error creating new publisher accounts

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#236]
Hi,

When creating a new publisher account on the IATI Registry, a 'Server Error' occurs.

It is possible to fill in the details of the account, then when clicking 'Save', this error page comes up:
![image](https://user-images.githubusercontent.com/38503709/52848447-a50a6f00-3106-11e9-8ba7-9890eb66268b.png)

This is preventing users from creating accounts on the Registry.

Please can you look into this as soon as possible?

Many thanks,
Jahnvi

**Comment by gtkChop** [comment]
Fixed now. Please validate and let me know if any issues. Thanks

**Comment by jahnvidave** [comment]
Thank you for your quick response! It is working now.
Many thanks, Jahnvi

**Comment by jahnvidave** [comment]
It is now possible to create a new publisher account without the error occurring, which is great. 
However, the automatic emails that we usually get, notifying us of the new account, have not been received.
Please can you look into this?
Thanks, Jahnvi

**Comment by jahnvidave** [comment]
Hi Swaroop, we have received the email for the test account you created, so thank you for fixing that.

I think there may have been some accounts created in the meantime, which we would not have been notified of. Is there any way for you to check which accounts have been created most recently?

**Comment by gtkChop** [comment]
Sent an email which contains all recent publisher ids which need approval.

**Comment by gtkChop** [comment]
Please reopen the ticket if you find this not resolved yet. Thanks
