### ISSUE TITLE
Error 500 occuring

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#237]
Hi,

When going to the CSV upload guidance on the Registry, it's displaying a Error 500 message: https://iatiregistry.org/help_csv-import

![image](https://user-images.githubusercontent.com/27764077/53234328-39d11780-3687-11e9-8f0f-f78477caf867.png)

**Comment by gtkChop** [comment]
Fixed. Please see the link.
https://iatiregistry.org/help_csv-import

This was due to the misspelled module name.

**Comment by andylolz** [comment]
> This was due to the misspelled module name.

^^ @gtkChop: would you be able to link to the relevant commit that fixed the issue? Or is this a config file change? (If so, it might be cool to add a template config file to the repo, and use it to duplicate any config information that isn’t sensitive.)

It continues to be unclear which branch of which github repository hosts the code that is used on iatiregistry.org. It looks like it might be the `ckan-2.8.1` branch of the derilinx fork: https://github.com/derilinx/ckanext-iati/tree/ckan-2.8.1 Is that the case? If so, perhaps this could be made clearer somehow?
