### ISSUE TITLE
Server error on Swiss TPH publisher page

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#238]
Hi Derilinx,

There is a 'Server Error' message that appears when accessing Swiss Tropical and Public Health Institute's publisher account on the IATI Registry.

Their publisher account is here: https://iatiregistry.org/publisher/swisstph

Please can you look into this?

Many thanks,
Jahnvi

**Comment by gtkChop** [comment]
@jahnvidave 

Yeah, this error is due to missing publisher ID. 

Please see the metadata associated with it. 
https://iatiregistry.org/api/action/organization_show?id=swisstph&include_datasets=true

**Comment by gtkChop** [comment]
Fixed the issue and made publisher status as pending. Please change the publisher id and change status to active. Thanks
https://iatiregistry.org/publisher/swisstph

**Comment by gtkChop** [comment]
Please reopen if you find error again. thanks

**Comment by jahnvidave** [comment]
Thank you @gtkChop for the explanation and for fixing the issue.
