### ISSUE TITLE
All Sida datasets are valid XML, but the registry says they almost all have errors

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#239]
This has been the case for more than two weeks, suggesting the process that flags these errors on the registry has some problem or has not run in that time.

**Comment by andylolz** [comment]
Screenshot from [the Sida publisher page](https://iatiregistry.org/publisher/sida):

![screenshot 2019-02-27 at 10 23 59](https://user-images.githubusercontent.com/464193/53483648-d7f32200-3a79-11e9-9871-a3dc51d80af8.png)

**Comment by gtkChop** [comment]
Is this issue still relevant? I dont see errors in the Sida publisher page:[](https://iatiregistry.org/publisher/sida)

**Comment by andylolz** [comment]
It seems like the archiver has run at some point since Sida fixed their data in March, so that is good.

There does appear to have been a problem with the archiver, because there was a long period when this data wasn’t updated.

Is there some public URL that shows when the archiver was last run?

**Comment by gtkChop** [comment]
Yeah, archiver stopped running for while on the month of Feb (due to memory leak and has been fixed recently). Now archiver is made to run every day.

I don't think there is any public URL that shows the last run. However, we have brought archiver functionality on UI level (only for sysadmin).

**Comment by andylolz** [comment]
Great – thanks @gtkChop.
