### ISSUE TITLE
EIB data is broken, but registry doesn’t show errors

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#241]
Org file: https://www.eib.org/en/about/partners/cso/iati/organisation.xml
Activity file: https://www.eib.org/en/about/partners/cso/iati/activity.xml

This has been the case for a couple of days, but registry doesn’t show any yellow error boxes:
https://iatiregistry.org/publisher/eib

I guess the archiver isn’t running?

**Comment by gtkChop** [comment]
@andylolz, Thank you for bringing this into our notice.

Yes, the archiver was not running. We have set it again to run. Thanks

**Comment by andylolz** [comment]
Great – thanks @gtkChop.

Can I ask: is there any sort of monitoring set up on the archiver? It seems like it breaks occasionally, but I’m not sure if that’s always picked up.
