### ISSUE TITLE
"About" and "API" links in main nav point to 404 pages

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#242]
These ones:
![Screenshot 2019-03-19 at 15 37 49](https://user-images.githubusercontent.com/464193/54619822-22eecc80-4a5d-11e9-8f8a-90d20cfbcc4e.png)

These are due to case issues in the URLs.

For "API", this:
http://iatistandard.org/en/using-data/IATI-tools-and-resources/using-IATI-registry/
…should be:
http://iatistandard.org/en/using-data/iati-tools-and-resources/using-iati-registry/

For "About", the link is the same as the one for "API", which I guess must be a separate mistake.

**Comment by andylolz** [comment]
Looks like there’s some work to fix this in iatistandard.org middleware. But there’s no harm in fixing the links over here, too.

**Comment by andylolz** [comment]
![screencast showing the error in question](https://user-images.githubusercontent.com/464193/55020636-23eca480-4fef-11e9-9a38-a4b004a376f6.gif)

**Comment by markbrough** [comment]
Also just came across this error - looking for API docs for the IATI Registry. I think it would be good if the API navbar link would link to an anchor alongside the heading "Using the Registry metadata API", as otherwise you have to scroll half way down the page to find the relevant information:

https://iatistandard.org/en/using-data/iati-tools-and-resources/using-iati-registry/

There are quite a few other broken links on that page, e.g.:
    Developer? Resources to help.

**Comment by andylolz** [comment]
I’ve created a PR to fix the "using the IATI registry" links, but Mark is right that others are broken. I also agree that clicking API should take you to API docs, so jumping down to the API-related bit is a good idea.

I have no idea if the PR is to the correct repo – I don’t think it is. Related to this, I’ve bumped #168 because I think it’s important that IATI continues to use and promote open source.

**Comment by andylolz** [comment]
The two links no longer 404 – looks like the problem was fixed on iatistandard.org.

Would be great to also address @markbrough’s suggestion:
> I think it would be good if the API navbar link would link to an anchor alongside the heading "Using the Registry metadata API", as otherwise you have to scroll half way down the page to find the relevant information

**Comment by sargentfrancesca** [comment]
@markbrough

>I think it would be good if the API navbar link would link to an anchor alongside the heading "Using the Registry metadata API", as otherwise you have to scroll half way down the page to find the relevant information

I can definitely see the benefit of using anchors and fragment identifier links to direct users to specific information, given the vast amount of information that is available to users. This requires initial dev work within [IATI/IATI-Standard-Website](https://github.com/IATI/IATI-Standard-Website), so i'll raise this as an issue there.

**Comment by sargentfrancesca** [comment]
Issue regarding anchored headings opened: [IATI/IATI-Standard-Website#337](https://github.com/IATI/IATI-Standard-Website/issues/337)

**Comment by andylolz** [comment]
Ace – thanks @sargentfrancesca!

So I guess this one can be closed.
