### ISSUE TITLE
Valid XML marked as invalid by archiver

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#243]
The datasets [European Union Activity File - Gambia ](https://iatiregistry.org/dataset/ec-devco-gm) and [Canada - Global Affairs Canada | Affaires mondiales Canada - Activity file/Fichier des activités - status 2 & 3](https://iatiregistry.org/dataset/gac-amc-act_2_3) both have XML errors on their respective registry pages:

![Screenshot 2019-04-01 at 10 19 10](https://user-images.githubusercontent.com/464193/55317033-a0580b00-5467-11e9-9314-6ba88352a58e.png)

![Screenshot 2019-04-01 at 10 19 01](https://user-images.githubusercontent.com/464193/55317026-9c2bed80-5467-11e9-9586-e89d0d406014.png)

These errors are incorrect – both datasets contain valid XML.

**Comment by gtkChop** [comment]
No errors for the dataset: [European Union Activity File - Gambia](https://iatiregistry.org/dataset/ec-devco-gm)

For [Canada - Global Affairs Canada | Affaires mondiales Canada - Activity file/Fichier des activités - status 2 & 3](https://iatiregistry.org/dataset/gac-amc-act_2_3) looks like it is a huge file of 15.90 MB

I will further look into the archiver and will keep you updated on this. Thanks

**Comment by andylolz** [comment]
Thanks @gtkChop,

> No errors for the dataset: European Union Activity File - Gambia

^^ That’s true – that error is no longer showing.

> For Canada - Global Affairs Canada | Affaires mondiales Canada - Activity file/Fichier des activités - status 2 & 3 looks like it is a huge file of 15.90 MB

I think IATI sets the size limit at 50MB? So by that measure, this is not a huge file.

To fix this, you can change this line:

https://github.com/IATI/ckanext-iati/blob/372e56531666386d7604ea010463d357bc31057a/ckanext/iati/archiver.py#L184

…to the following:

```python
tree = etree.fromstring(xml, parser=etree.XMLParser(huge_tree=True))
```

**Comment by gtkChop** [comment]
Thanks @andylolz . I will try that

**Comment by gtkChop** [comment]
Solved please see  [Canada - Global Affairs Canada | Affaires mondiales Canada - Activity file/Fichier des activités - status 2 & 3 ](https://iatiregistry.org/dataset/gac-amc-act_2_3)

Thanks @andylolz , please let me know if you see any further issues.

**Comment by andylolz** [comment]
Great, thanks.

It looks like it was fixed on the `prod` branch of the derilinx fork: https://github.com/derilinx/ckanext-iati/commit/261ed825

Is there a plan to be a bit more transparent about where the open source code for iatiregistry.org lives? It would be great to:
   1. provide a link to the repo in the footer, and
   2. deploy from `master` or from the default branch

Thanks

**Comment by gtkChop** [comment]
@andylolz yeah, we will set the default branch soon. Closing this issue.
