### ISSUE TITLE
Home page publisher count

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#248]
As we reach 1000 publishers we would like to change the display to say how many 'active' publishers there are. These are organisations who have updated their data within the last year.

Potentially, the new figure could replace the old one. Or we could have the two running side by side?

@gtkChop how feasible this and how much time would this take to implement?

**Comment by andylolz** [comment]
> These are organisations who have updated their data within the last year.

In terms of getting the data to do this… I suspect the [IATI Dashboard timeliness page](http://dashboard.iatistandard.org/timeliness.html) provides the best figures for this. It’s available [as CSV here](http://dashboard.iatistandard.org/timeliness_frequency.csv) (it doesn’t appear to be available as JSON?)

I think here we’re saying active publishers are those with a `Frequency` other than “**Less than Annual**”. So that means publishers with a `Frequency` of: “**Monthly**”, “**Quarterly**”, “**Six-Monthly**” or “**Annual**”.

**Comment by JoshStanleyDevInit** [comment]
Hi @gtkChop,

To help us decide whether we would like to pursue this idea, please could you provide us with the following statistics:

1) How many publishers have updated their data in the past 12 months?
2) How many publishers have updated their data in the past 24 months?

Thanks,
Josh

**Comment by gtkChop** [comment]
Total active Publisher: 1321
Total Publisher Published so far: 1047

Publisher Count whose package metadata modified in past 12 months (from 2018-09-11): 844
Publisher Count whose package metadata created in the past 12 months (from 2018-09-11): 361 

Publisher Count whose package metadata modified in the past 24 months (from 2018-09-11): 1053
Publisher Count whose package metadata created in the past 24 months (from 2018-09-11): 639

**Comment by JoshStanleyDevInit** [comment]
Hi @gtkChop,

Thanks for providing those stats!

I assume that these lists would include deleted publishers and publishers who have private files etc.

In which case, please can you update the counts to include only publishers which currently have an active file (i.e. are in the existing main page list - https://iatiregistry.org/publisher

Thanks!

**Comment by JoshStanleyDevInit** [comment]
@gtkChop This has become a high priority so would be great if stats can be obtained before our next call. To be clear, the qualifying criteria are:

**Count 1**
- Publisher has at least one public activity file
- Data has been updated in the last 12 months

**Count 2**
- Publisher has at least one public activity file
- Data has been updated in the last 12 months

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 
Looking at this.

**Comment by stevieflow** [comment]
Here be dragons

By "package metadata modified" I understand that could be *any* part of a publisher corpus that has changed (overnight).  Conceivably, a publisher could change ''last-updated-datetime'', but _no other data element or attribute_, and be considered as modified - and _therefore_ active.

The IATI dashboard has a clear methodology in terms of what is considered to be an update (using the 'transaction' element).  This makes the update metric more difficult to manipulate

The wider point is that there is a continued dialogue and discussion around timeliness - which is based on the IATI dashboard.  Should new figures and lists (based on a different methodology) be distributed and disseminated - there's a significant risk of organisations questioning the validity of one or another

For display purposes, I do not understand why the metrics in the dashboard do not suffice: http://publishingstats.iatistandard.org/timeliness.html

![IATI Dashboard - Timeliness](https://user-images.githubusercontent.com/1209944/70447159-354ee180-1a96-11ea-8271-40ae718a4854.png)

If the cut off was Annual, then 758 publishers could currently be considered as "active"

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

1102: Number of active organization (all active publishers)
641: Number of organizations with at least one active dataset within a year (from today).

Production numbers would be:

1372: Number of active organization (all active publishers)
1065: Number of organizations with at least one active dataset within a year (from today).

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

Added active publisher count according to the description in email that is, all active publishers with at least one public activity file.

Split the count according to the time frame:
- 24 months
- 12 months
- 6 months

Please see the staging site and let me know your feedback. Thanks

**Comment by gtkChop** [comment]
@JoshStanleyDevInit @Ocre42 

You can generate the report through UI. I have sent an email with link to staging.

**Comment by JoshStanleyDevInit** [comment]
Thanks @gtkChop. Having it available on the admin screen has been super helpful. I'll close this for now and we can reopen if we opt to add a count to the public site in the future.
