### ISSUE TITLE
Registry Text Updates

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#250]
We want to make it clearer to users which e-mail addresses will be made public. The PR for this is here:
- https://github.com/IATI/ckanext-iati/pull/249

There is an outstanding change to the homepage wording which is here (I'll close the previous issue as it's now logged here):
- https://github.com/IATI/ckanext-iati/pull/225

@gtkChop please can these changes be implemented asap

**Comment by gtkChop** [comment]
Registry text updated. Please reopen if anything needs to be changed. Thanks
