### ISSUE TITLE
Prevent publishers from changing their IATI publisher and Org IDs

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#252]
Once a a publisher account has been approved, in most cases, the IATI Org ID and publisher ID should never change. Changes to these cause issues with other tools that use IATI data.

Currently users can change their publisher IDs and IATI Org IDs at any point.

We want to explore how we can stop this happening. So that once a publisher account is approved, the user has to get in touch with the tech team in order to change their IATI Org ID or Publisher ID.

**Comment by gtkChop** [comment]
Implemented in Staging - 
 - For active organization - **do not allow** users/org admins to change publisher and org id.
 - Sysadmin can change publisher id and org id.
 - Org admin can change publisher id and org id only if the organization is **not active** (i.e. **pending/deleted**)

**Comment by amy-silcock** [comment]
Thanks Swaroop - I'm trying to test this on staging. I can't see the option to make a new account active. Please can you activate: https://staging.iatiregistry.org/publisher/test_changing_pub_id

Then I will test

**Comment by gtkChop** [comment]
"I can't see the option to make a new account active."
A: You need to be logged in as sysadmin to make a publisher active.

Activated - https://staging.iatiregistry.org/api/action/organization_show?id=test_changing_pub_id

**Comment by amy-silcock** [comment]
Thanks Swaroop - I thought I was logged in using my admin account....

Testing the functionality, if I got to change the publisher id and re-save it the publisher id and IATI Org ID get wiped:

![image](https://user-images.githubusercontent.com/27764077/59674171-a635d080-91ba-11e9-8843-7cc341038c98.png)

And when I try to refresh the page to get them back I can no longer see them:

![image](https://user-images.githubusercontent.com/27764077/59674292-e7c67b80-91ba-11e9-9216-9065b1d9f72d.png)

**Comment by amy-silcock** [comment]
Is it possible to grey out the publisher id and IATI Org Id options? So users can see them but can't update them?

Rather than attempting to and then being told you can't? Loosing the information is also not a good option.

**Comment by gtkChop** [comment]
Greyed out now - i.e. disabled.

I have tested the below scenario:
- New user creates a new organization (state - pending for approval) - (access: orgadmin)
- Sysadmin approves the organization (i.e. state = active) - (access: sysadmin)
- Now org admin press manage button to edit **active** organization - (access: orgadmin)
- Publisher ID and ORG ID should be disabled. (access: orgadmin) - for sysadmin field is editable.

Added validator for API as well.

**Note**: 
- If sysadmin creates an organization by default organization is active.

I am testing few other scenarios for state = deleted, pending and **organization_create** api action.

I will keep you updated on this. Thanks

**Comment by gtkChop** [comment]
Deployed. Please let me know if any issues. Thanks

**Comment by gtkChop** [comment]
Please reopen if any issues. Thanks
