### ISSUE TITLE
Change `pddl` license ID back to `odc-pddl`; update existing instances of `pddl` to `odc-pddl`

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#255]
It looks like the license ID for `odc-pddl` may have been changed to `pddl`? Is that correct?

As a result of this change, when a publisher using `odc-pddl` attempts to modify their org metadata, the license field will be deselected, and they’ll need to reselect a new one. That’s not ideal.

Also, publishers have started to appear here:
http://dashboard.iatistandard.org/license/pddl.html

…but unlike [`odc-pddl`](http://dashboard.iatistandard.org/license/odc-pddl.html), the dashboard doesn’t know what [`pddl`](http://dashboard.iatistandard.org/license/pddl.html) means so there’s no heading on the page. Here’s the license lookup the dashboard uses, which includes `odc-pddl` but not `pddl`:
https://github.com/IATI/IATI-Dashboard/blob/2bf11239f07c0febeb52f35fbe28e14c9164a905/licenses.py#L3

It would be better to avoid changing these IDs, since it causes these sorts of problems. Could this one be changed back, and instances of `pddl` changed to `odc-pddl`?

**Comment by gtkChop** [comment]
`"domain_content": false,
    "domain_data": true,
    "domain_software": false,
    "family": "",
    "id": "pddl",
    "is_generic": false,
    "maintainer": "",
    "od_conformance": "approved",
    "osd_conformance": "not reviewed",
    "status": "active",
    "title": "Open Data Commons Public Domain Dedication and Licence (PDDL)",
    "url": "http://www.opendefinition.org/licenses/odc-pddl"`

**Comment by andylolz** [comment]
> However, whatever changes here need to be in changes in db as well to make sure data is consistent.

Yes, exactly. This is currently inconsistent, since the database wasn’t updated when this change was made. The following publishers all have license ID `odc-pddl` in the db:
http://dashboard.iatistandard.org/license/odc-pddl.html

This much smaller list have license ID `pddl`. Presumably these were all updated by the users since the change:
http://dashboard.iatistandard.org/license/pddl.html

When this ID was changed, the instances in the database should also have been changed. But I think it would be preferable to instead change the ID back.

**Comment by gtkChop** [comment]
Yeah sure. I will have a look into that and will let you know once updated.
Thanks, Andy

**Comment by andylolz** [comment]
Great – thanks @gtkChop!

**Comment by gtkChop** [comment]
Implemented in staging.

Currently, there are 17 active publishers with license_id = 'ppdl'. Need to check again in db and change those values when pushed to production.

**Comment by gtkChop** [comment]
Changes implemented in Production.

**Comment by andylolz** [comment]
Looks good to me! Thanks

**Comment by andylolz** [comment]
> Changes implemented in Production. Please reopen if you face any issues.

I’m not able to reopen this, but I think there is an issue. See #261.
