### ISSUE TITLE
Ensure deleted admins don't get notification e-mails

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#256]
Instance of admins who have had their account deleted still getting Registry notificaiton e-mails. @gtkChop looking into this and fix to be pushed to live on Monday

"Below is the query to get all sysadmin to send an emails notifications as soon as new publisher is created - 
	
	model.Session.query(model.User).filter(model.User.sysadmin==True)

Description:

When the sysadmin is deleted through UI/paster command - it will not remove the user details permanently from the database, instead CKAN will set the state for that user as deleted in database.

From the above query we can see that, it will get all the sysadmins (irrespective of their state) and send an notification email to all sysadmins.

Note: This is the only when new publisher is created.

Proposed Change:

Modify the query as below - i.e. make sure to check the state of the sysadmin before sending the email.

model.Session.query(model.User).filter(and_(model.User.sysadmin==True, state='active'))

We will test this in staging and once it is working as expected we will push to production.
"

**Comment by andylolz** [comment]
As a workaround, perhaps prior to deleting admins, they could first be made non-admins. Perhaps that could be part of the deletion process, in order to help avoid this [privilege escalation](https://en.wikipedia.org/wiki/Privilege_escalation).

```
model.Session.query(model.User).filter(and_(model.User.sysadmin==True, state='active'))
```

^^ This doesn’t look quite right to me. I guess the `state='active'` bit should instead say: `model.User.state=='active'`.

**Comment by amy-silcock** [comment]
Hi @gtkChop,

Do you have an update on this one?

**Comment by gtkChop** [comment]
@andylolz Thanks for the feedback.
Yes, the syntax was wrong since it was a quick suggestion.
Working code here:
```
q = model.Session.query(model.User) \
             .filter(_and_(model.User.sysadmin==True, model.User.state=='active'))
``'
This block of sending an email is custom one from IATI extension (not core CKAN). I am not aware of any process behind deleting the sysadmin. 

@amy-silcock 
Implemented in staging and works well. Could you please let us know was there any process behind deleting the sysadmin? So that I can change the code accordingly. Thanks

**Comment by amy-silcock** [comment]
Hi, I simply deleted the user account that was an admin.

I don't think we have the ability to create admins. Rather we e-mail Derilinx and you send us the details of the new admin user account?

**Comment by gtkChop** [comment]
Thanks, Amy for your inputs. Deployed in production. Please let me know if any issues. Thanks

**Comment by amy-silcock** [comment]
Thanks @gtkChop. I'll let you know

**Comment by amy-silcock** [comment]
Confirmed that a previous e-mail is no longer receiving notification e-mails. Thanks for fixing.
