### ISSUE TITLE
My Publishers page not showing organisations which haven't published

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [IATI/ckanext-iati#257]
On the 'My Publishers' page (https://iatiregistry.org/dashboard/mypublishers), admins used to be able to see a list of all publishers whose accounts have been activated. Now only those who have published a dataset are displayed.

Please can we return to all 'active' publishers being displayed?

Thanks,
Josh

**Comment by amy-silcock** [comment]
@gtkChop please can you also make a change so that the non-publishing active organisations do not appear in Registry API calls - potentially using package_count field.

**Comment by gtkChop** [comment]
- [ ] Active Publishers with 0 datasets visibility: Implemented in staging.

Please see the below links:
- https://staging.iatiregistry.org/dashboard/mypublishers (logged in users - Publisher with no dataset/not published is visible now)
- https://staging.iatiregistry.org/publisher (Publisher with no dataset/not published is visible only for sysadmins)

- [ ] @amy-silcock Could you please give more information on API calls? 

E.g: API call organization_show/organization_list will show the metadata based on the access rights and these API calls are liked to several other API calls in CKAN Core, as well as an IATI Extension and changing this functionality may result in unexpected behavior.

**Comment by JoshStanleyDevInit** [comment]
Thanks for looking into this @gtkChop.

I am happy that publishers with no dataset are now available on the Publisher list for admins only.

For My Publishers, is the intention that the publisher is visible even when their account has not been activated? This does not seem to be the case at the moment.

With regard to API calls, we want to avoid users from being able to access metadata for publishers which have not yet published a dataset. Please can you look into that?

Thanks!

**Comment by gtkChop** [comment]
@JoshStanleyDevInit Thank you for the feedback.

I will look into this and keep you updated.

**Comment by gtkChop** [comment]
@amy-silcock @JoshStanleyDevInit 

We can create a new API called publisher_list and publisher_show we can change the behavior of these API's according to our needs. 

However, it's difficult to change the behavior of organization_list and organization_show because is been used internally by CKAN for several processes. Changing these may result in unexpected behavior of the existing process.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop if the existing API cannot be changed then I do not see the worth in creating a new one so I think this can be closed.
