### ISSUE TITLE
CSV uploader inconsistent error messages

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#263]
Hi,

This relates to zendesk ticket: 8833

A publisher is getting this error message: 
![image](https://user-images.githubusercontent.com/27764077/61941620-c01fbb80-af8f-11e9-8155-5e07a9772c8b.png)

Looks to be created by a special character identified in their CSV file. However, some of the IATI files from the file are making it to their publisher account. I recreated this on staging and had the same result.

Please can you look into this / make the error message and actions consistent.

**Comment by gtkChop** [comment]
@JoshStanleyDevInit @amy-silcock @Ocre42 
- Made - encoding consistent
- Handled error on each row.

Should be working. Tested with the CSV files given in zendesk ticker 8833.

If this looks good from you, I will be pushing the code to prod.

**Comment by JoshStanleyDevInit** [comment]
@amy-silcock Please can you double-check that this is working as expected before we confirm that it can be deployed?

Thanks!

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Please can you confirm if this was deployed on Mon 18th as planned?

**Comment by gtkChop** [comment]
@JoshStanleyDevInit Deployed.
