### ISSUE TITLE
Datasets returning internal server errors

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#264]
The following datasets return internal server errors:

 * https://iatiregistry.org/dataset/pdorg-activities
 * https://iatiregistry.org/dataset/wvuk-bo

This one does a redirect to a 404 page:

 * https://iatiregistry.org/dataset/international-alert-org

They all return 500 errors via the API:

 * https://iatiregistry.org/api/3/action/package_show?id=pdorg-activities
 * https://iatiregistry.org/api/3/action/package_show?id=international-alert-org
 * https://iatiregistry.org/api/3/action/package_show?id=wvuk-bo

**Comment by gtkChop** [comment]
@andylolz @amy-silcock 

This is because for the above datasets metadata_modified is null. Hence throws server error.

I checked for datasets in the database where metada_modified is null - below is the result :

          name           | metadata_modified 
-------------------------+-------------------
 wvuk-bo                 | 
 pdorg-activities        | 
 international-alert-org | 

Only 3 datasets with metadata_modified null.

**Comment by andylolz** [comment]
Okay, so could you manually set `metadata_modified` to equal `metadata_created`?

**Comment by gtkChop** [comment]
I will you know once done. Thanks

**Comment by gtkChop** [comment]
owner_org               | metadata_created | metadata_modified |          name           
--------------------------------------+------------------+-------------------+-------------------------
 8103ff7e-c091-465d-b265-2b95ea2b33b4 |                  |                   | wvuk-bo
 83d37947-ddff-4ed5-bf81-4219a5a38a28 |                  |                   | pdorg-activities
 c3f34286-ac9b-495f-b74b-02addd697f45 |                  |                   | international-alert-org




publisher 83d37947-ddff-4ed5-bf81-4219a5a38a28 has been deleted.

**Comment by JoshStanleyDevInit** [comment]
Hi Andy,

I've had a quick look into this and it appears that all three of the specified datasets have since been deleted from the Registry. Peace Direct in fact have not been a publisher for some time, looking at their Activity Stream, the last action on the account was to remove the pdorg-activities file 10 months ago.

Josh

**Comment by andylolz** [comment]
Thanks for looking into this, both.

I’m not sure why these datasets exist in the API, then. Could/should they be removed?

I’m running into this issue because I’m trying to use the following endpoint:
https://iatiregistry.org/api/3/action/package_list

This list includes all three of these datasets, and they all error. So perhaps the solution here is just that `package_list` shouldn’t list them?

**Comment by andylolz** [comment]
> metadata_created and metadata_modified both are empty for the above datasets.

^^ As an aside: It’s weird that `metadata_created` is empty. These datasets must have been created at some point. Any idea how this has happened?

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Would you normally expect deleted datasets to appear in the package_list API? If not, is there any risk involved with simply removing them, as @andylolz suggests?

**Comment by gtkChop** [comment]
@andylolz @JoshStanleyDevInit 

All the three datasets state is active in database hence it appears in the package list. 

For the deleted organization: (83d37947-ddff-4ed5-bf81-4219a5a38a28) - package (pdorg-activities) is active, which should not be (probably bad data). I think we can make the package state as deleted. 

For the remaining two packages:
- **wvuk**
- **international-alert**
If these are not used anymore we can make the state of the above packages as deleted as well. 

Once deleted this should not be appearing in package_list.

**Comment by JoshStanleyDevInit** [comment]
Hi @gtkChop,

Just confirming that we agreed on last week's call that these datasets can be deleted, as we discussed on last week's call.

Thanks,
Josh

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 
Deleted the above mentioned 3 datasets and it also not visible in API package_list.

Further, we can also purge the dataset - (non-retrievable)

**Comment by gtkChop** [comment]
Please reopen if it is still an issue. Thanks
