### ISSUE TITLE
Download Publisher List

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [IATI/ckanext-iati#265]
Please can we add a function to the Publisher list page (https://iatiregistry.org/publisher) whereby the user can download the list? Ideally the user could select which file format the list can be downloaded in (i.e. CSV, XLS, XML, JSON).

Thanks,
Josh

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

Implemented download functionality in staging. Please review (XML fields) and let me know if you need any changes. Thanks

https://staging.iatiregistry.org/publisher

**Comment by JoshStanleyDevInit** [comment]
Thanks for this @gtkChop.

Three of us have tested this and it doesn't always work in every browser. For some of us it would not work in Chrome but was fine for IE and Firefox - please can you look into this?

Also, please can you advise which publishers are being pulled? We would like for it to be the same as the https://iatiregistry.org/publisher page, i.e. active publishers with at least 1 dataset. Please can this be replicated for the download option?

Thanks,
Josh

**Comment by JoshStanleyDevInit** [comment]
Hey @gtkChop,

I am still unable to see the format drop-down when I click on the box, when using Chrome :(

**Comment by gtkChop** [comment]
@JoshStanleyDevInit Thanks for letting us know this. 

Could you please provide me the below details?

Browser Name:
Browser Version:
Operating System:


Thanks.

**Comment by JoshStanleyDevInit** [comment]
Browser Name: Google Chrome
Browser Version: 76.0.3809.132 
Operating System: Windows 10 Pro

**Comment by gtkChop** [comment]
@JoshStanleyDevInit Thanks for the details. I have tested the functionality with the same above configuration and it worked fine.

We can talk about this in next status meeting (probably share the screen) and see what exactly an error in browser console. That would be a good starting point for me to debug the problem.

Thanks

**Comment by JoshStanleyDevInit** [comment]
Hi @gtkChop,

Just confirming that we agreed on last week's call that this can now be deployed, when ready.

Thanks,
Josh

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 
Deployed

**Comment by gtkChop** [comment]
Please re open if you face any issues. Thanks
