### ISSUE TITLE
Re-enable API CORS support

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#266]
CORS support was enabled in #224, but it looks like it has been disabled at some point.

You can test this by visiting the following link and clicking "Send request":
https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fiatiregistry.org%2Fapi%2F3%2Faction%2Forganization_list&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

The results at the bottom show an error:
![Screenshot 2019-08-08 at 12 23 23](https://user-images.githubusercontent.com/464193/62699395-5663d080-b9d7-11e9-8c80-c986ef04530c.png)

---

This change breaks services that rely on CORS, including IATI Decipher.

Please could this be re-enabled? Thanks

**Comment by gtkChop** [comment]
Enabled now - 

https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fiatiregistry.org%2Fapi%2F3%2Faction%2Forganization_list&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

**Comment by andylolz** [comment]
Excellent! Thanks for resolving this.
