### ISSUE TITLE
Links to files in AidStream giving inconsistent errors 

### ISSUE THREAD

**Issue by Ocre42** [IATI/ckanext-iati#268]
As an example:
https://www.iatiregistry.org/dataset/ipa-org

It appears that there's occasions when the files point to `np.aidstream.org` instead of `aidstream.org` when adding `www` to the url. Resulting in error messages for files and issues when trying to download them using scripts.

**Comment by andylolz** [comment]
I think this is an aidstream bug, related to their SSL certificate.

If you visit the above link in Firefox:

![Screenshot 2019-10-04 at 16 54 35](https://user-images.githubusercontent.com/464193/66221836-b8833e00-e6c7-11e9-91e2-2cffbb67bdd5.png)

The publisher can fix this by switching to a bare domain i.e.:
https://iatiregistry.org/dataset/ipa-org

…or aidstream can fix this by adding the www subdomain to their SSL certificate.

**Comment by andylolz** [comment]
I think this is an aidstream bug, related to their SSL certificate.

If you visit the above link in Firefox:

![Screenshot 2019-10-04 at 16 54 35](https://user-images.githubusercontent.com/464193/66221836-b8833e00-e6c7-11e9-91e2-2cffbb67bdd5.png)

The publisher can fix this by switching to a bare domain e.g.:
https://aidstream.org/files/xml/ipa-org.xml

…or aidstream can fix this by adding the www subdomain to their SSL certificate.

**Comment by andylolz** [comment]
> It appears that there's occasions when the files point to `np.aidstream.org` instead of `aidstream.org` when adding `www` to the url. Resulting in error messages for files and issues when trying to download them using scripts.

np.aidstream.org is a subject alternative name (SAN) on the certificate. So that’s where that comes from. I don’t think it’s about where the file points to, but rather about the allowed subdomains in the certificate.

![Screenshot 2019-10-04 at 17 10 58](https://user-images.githubusercontent.com/464193/66222862-06994100-e6ca-11e9-9061-1ffdc6f198e7.png)

**Comment by Ocre42** [comment]
Fixed by AidStream: https://github.com/younginnovations/aidstream/issues/310

**Comment by andylolz** [comment]
Great – I hope comments above were helpful.

**Comment by andylolz** [comment]
Great – looks good to me.

I hope comments above were helpful.
