### ISSUE TITLE
File error messages - very bad handshake

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#269]
Hi,

The publisher Transparency International Secretariat is having issues with their files: https://www.iatiregistry.org/publisher/transparency-international. 

The error message:

![image](https://user-images.githubusercontent.com/27764077/66817500-b759d880-ef33-11e9-9e56-9f4cf007b649.png)

Is appearing for some of the files and we can't work out why. The data is accessible and is showing up on tools such as d-portal.

Would you be able to investigate?

Best wishes,

Amy

**Comment by notshi** [comment]
Hi @amy-silcock - we ignore invalid security certificates at d-portal because these go wrong all the time; ie. the 'bad handshake' here is probably an expired certificate which needs refreshing by the publisher.

**Comment by amy-silcock** [comment]
Thanks @notshi, I'll pass your message on.

**Comment by andylolz** [comment]
According to the code in this repo, the registry refresher also ignores invalid certificates, so this error message is a bit mysterious.

See the `verify=False` here:

https://github.com/IATI/ckanext-iati/blob/ce4712ab3a5b62d5bc30c2108762a815e75b681f/ckanext/iati/archiver.py#L429-L430

That’s [documented here](https://requests.kennethreitz.org/en/master/user/advanced/#ssl-cert-verification).

**Comment by gtkChop** [comment]
@andylolz 
 
Yes, verify=False (only when the head request fails). However, the archiver first sends the head request and there exists an SSL validation. Please see the link below.

https://github.com/ckan/ckanext-archiver/blob/master/ckanext/archiver/tasks.py#L970

@JoshStanleyDevInit 
Created a patch with verify=False in staging. We will be pushing the changes to prod once we are good with test results.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Please can you confirm if this was deployed on Mon 18th as planned?

**Comment by gtkChop** [comment]
@JoshStanleyDevInit Deployed

**Comment by JoshStanleyDevInit** [comment]
Looks good, thanks @gtkChop
