### ISSUE TITLE
Mobile View /publisher page

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#271]
looks like mobile view css broken.

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

Looks like the IATI registry is not using the CSS bootstrap at all. So the mobile view is not working.

Is this ever worked before? And I believe this needs UI changes in several places.

**Comment by Ocre42** [comment]
From our understanding, the registry hasn't had a functioning mobile/responsive implementation

**Comment by andreaszenasidi** [comment]
It was confirmed that the registry hasn't had a responsive implementation.
