### ISSUE TITLE
Download Publisher option has codes instead of full values

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [IATI/ckanext-iati#272]
The (very useful) 'Download List' function on the [list of publishers page](https://iatiregistry.org/publisher) returns 'Organization Type' and 'HQ Country or Region' columns.

Currently these are codified. It would be preferable if they instead returned the full values.

e.g. Organization Type = Government (instead of 10)
HQ Country or Region = Italy (instead of IT)

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

It should be possible to give titles instead of codes. I will have a look and see how it goes.

Thanks

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

This has been fixed. Please see the staging site publisher page. 

Let me know your feedback thanks.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Looks good, thanks Swaroop! Please go ahead and deploy when ready.

**Comment by gtkChop** [comment]
@JoshStanleyDevInit Deployed. Closing the issue. Please reopen if are still any issues with this. Thanks
