### ISSUE TITLE
Ivory Coast filter does not work

### ISSUE THREAD

**Issue by stevieflow** [IATI/ckanext-iati#274]
From a publisher page - eg:

https://iatiregistry.org/publisher/dfid

The right-hand side list of countries - 

![- Organizations - IATI Registry (2)](https://user-images.githubusercontent.com/1209944/74954016-5a4ac380-53fa-11ea-9d14-243be003a661.png)

On selecting Ivory Coast we get a Server Error page

https://iatiregistry.org/publisher/ea4de570-bd2c-4dee-a709-9197c4a8ebe9?country=C%C3%B4te+D%27Ivoire

I have tested this on other publishers - same behaviour

**Comment by gtkChop** [comment]
@stevieflow 

This is an encoding problem. Usage of str in python2.7 converts to ASCII by default. Made changes in staging and tested. I will be pushing to a prod soon. Thanks

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

Deploying this feature to production.

**Comment by gtkChop** [comment]
Closing this. Please re open if it is still an issue

**Comment by stevieflow** [comment]
Thanks - checked and working.
