### ISSUE TITLE
Pagination and search functionality for download publisher records

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#276]
CSV download feature page:

- [x] Pagination and search for this page. Should look similar to publisher page
- [x] Search functionality to search publisher

**Comment by gtkChop** [comment]
Pending Items:

- [ ] - Check for security (do not show private organization/datasets) for non-logged in users
- [ ] - Fix title ascending and descending dropdown/table sorter.

**Comment by JoshStanleyDevInit** [comment]
@gtkChop looks good, can be deployed

**Comment by gtkChop** [comment]
@JoshStanleyDevInit 

There was a bug in template download. It has been fixed now. Deployed to production.
