### ISSUE TITLE
Time out error when download all publisher records.

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#278]
Currently, there is a feature in **Download current Records** to download all the records for all the publishers. I don't see anywhere this has been used.

**Problem**: Since IATI has lot of publishers and download all records throws time out error (>30 seconds) and also not recommended to store all data in memory which may cause out of memory as more and more publishers are added.

It's best to use steaming download (stream with context) for these files.

**Comment by andreaszenasidi** [comment]
The feature is not available anymore.
