### ISSUE TITLE
IATI CSV upload and archiver job stuck and jobs are not running

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#281]
Email From Petya.

Background: 

Here are only three files so unsure why it is taking so long. I am also not getting any errors. Can you check and let me know? Can you also confirm if all fields in the attached are mandatory? Also this is a test file not to be shared more widely. Hence, I am using the staging site.

**Comment by gtkChop** [comment]
* Identified the issue. This is due to the redis queue being stopped executing jobs

**Comment by JoshStanleyDevInit** [comment]
No issues reported since this happened so this can be closed

**Comment by gtkChop** [comment]
Solved in Production too. Closing this
