### ISSUE TITLE
Admin Dashboard Timing Out

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [IATI/ckanext-iati#282]
I am unable to access the Registry admin Dashboard page: https://iatiregistry.org/dashboard/

Each time I try to do so, the page times out.

**Comment by gtkChop** [comment]
@JoshStanleyDevInit I am not sure. I tried the dashboard and it works well for me.

**Comment by JoshStanleyDevInit** [comment]
This seems to be fine now so happy to close.
