### ISSUE TITLE
Last update dates

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#283]
Hi all,

A number of IATI publisher's last-updated-date metadata isn't updating automatically. It updates when I run the archiver for individual publishers.

Shouldn't the archiver also be running automatically every 24 hours? Or did we change this?

Best,

Amy

**Comment by gtkChop** [comment]
@amy-silcock @JoshStanleyDevInit 
Thanks for bringing this to our notice. Please see issue #284 

This will be looked at and will be fixed on the completion of tasks in 284. I Will let you know once all the tasks are completed.

**Comment by amy-silcock** [comment]
Thank you @gtkChop :)

**Comment by JoshStanleyDevInit** [comment]
@gtkChop Has the archiver been run for all datasets now? Can we expect that all last updated dates in the metadata are now showing correctly?

**Comment by gtkChop** [comment]
Yes, archiver last run date Aug 4 (Today). Did quick sanity check through archiver logs and looks good.

**Comment by gtkChop** [comment]
Closing this. Please reopen if any issues. Thanks

Last archive run is 19th August - 2020
