### ISSUE TITLE
IATI CKAN version and system upgrade

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#284]
**The task that's required:**

- [x] 1. - Upgrade to ckan 2.8.1 to 2.8.5 (In staging - need to move to production).
- [x] 2. - Upgrade docker and docker-compose to the latest stable version.
- [x] 3. - Stabilize archiver run with email notification on status. (Old version of docker causes corruption of corn file).

**Comment by gtkChop** [comment]
@JoshStanleyDevInit @amy-silcock 

Updated the system and all changes are mentioned in IATI [change logs.](https://iatiregistry.org/pages/iati-change-logs)

CKAN is now on 2.8.3 version. Can verify here:  https://iatiregistry.org/api/action/status_show

Looks like docker is not corrupting the cron file and currently, the archiver is running (would take some time). We will keep monitoring the cron jobs for a few days and will confirm once again. Thanks

**Comment by gtkChop** [comment]
Updated CKAN iati to 2.8.5 in staging and good to go to production.

No visual or functionality changes. Changelog for ckan 2.8.5 here: https://docs.ckan.org/en/2.8/changelog.html

**Comment by PetyaKangalova** [comment]
Thanks, looks good! @gtkChop when is the planned timing for 2.8.5 to go to production? Forgot to ask when we spoke!

Then happy to close this issue and we can set another issue about the update to CKAN 2.9.

**Comment by gtkChop** [comment]
@PetyaKangalova Deployed to prod. 

https://iatiregistry.org/api/action/status_show

Please reopen if any issues. Thanks
