### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [IATI/ckanext-iati#285]
Users (including admins) are currently unable to log into the Registry. The following message appears despite the details being correct:

![image](https://user-images.githubusercontent.com/46994072/88530460-52223000-cff9-11ea-901b-dda2a4995af5.png)

Please investigate urgently.

Thanks,
Josh

**Comment by gtkChop** [comment]
@JoshStanleyDevInit

It was a problem with headers (which contains integer form Nginx cache). Fixed it.

Please let me know if any issues again. Thanks

**Comment by JoshStanleyDevInit** [comment]
Confirmed that this is fixed - this can be closed.

**Comment by gtkChop** [comment]
Closing this
