### ISSUE TITLE
Optimise CSV Upload Process

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [IATI/ckanext-iati#286]
Occasionally the csv upload process does not work for publishers and the first dataset gets stuck at the 'queued' stage.

@gtkChop has advised that this is down to many users trying to use the function at once, and getting stuck in a queue.

Please can we investigate how this process can be optimised to mitigate the chances of this happening?

Thanks

**Comment by gtkChop** [comment]
To mitigate this effect I have a few things in my mind:

* Limit the number of dataset upload (max 60 per upload). 
* Disabled archive jobs for those which are updated from csv uploader (because 1 upload = 2 jobs 1 for archiver and 1 for upload). Once all the csv data is uploaded they/admin have to run manually.
* Possibly add expire logic for each job (wait for 15 mins to execute, if not cancel the job - so that we dont have the ever growing queue).

**Comment by gtkChop** [comment]
@PetyaKangalova 

Optimized csv upload and currently on staging. 

Pending task:

- Try uploading 50 files at a time and see time consumed. (performance and load testing)
- Need to deploy to production

**Comment by gtkChop** [comment]
@PetyaKangalova 

Currently ckan background jobs works on the basis of first in first out. That is, all the previous jobs has to be completed first before executing the current one. Hence, it gives the users feeling of job is being stuck.

**To avoid this:**
- I have disabled the archive when dataset is updated/created though CSV upload.
- For those dataset/package that are updated/created using csv upload, archive has to be run manually.

Tested few scenarios and good to go for production.

**Comment by PetyaKangalova** [comment]
@gtkChop  I just did a few uploads on staging and files are indeed uploading very quickly!  Also got an error message if uploading more than 50 activities. Let's discuss today as I am unclear why the archiver has to be run manually? Would that be the case in production??

**Comment by PetyaKangalova** [comment]
As discussed, add sentence on the CSV upload page to notify the user that their metadata fields will be updated the next day.

**Comment by gtkChop** [comment]
@PetyaKangalova Added a  note on the CSV upload page and also increased the limit to 100

Currently in staging and can be deployed to production. Thanks

**Comment by PetyaKangalova** [comment]
Hi @gtkChop  I tested with 100 and worked very well. I am not sure I see the message? Where is it showing?  Nothing on main page, or is it on individual pages?
![image](https://user-images.githubusercontent.com/24607542/96131442-165c7f80-0ef1-11eb-87d2-91de5fba8187.png)

**Comment by gtkChop** [comment]
Pushed to production. Closing this for now. Please re-open if any issues. Thanks
