### ISSUE TITLE
The Asia Foundation Publisher deleted

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#287]
The publisher's list page shows there are 13 datasets. But, when visiting the publisher, its shows publisher has been deleted.

**Comment by gtkChop** [comment]
The publisher is not deleted, however it is redirecting to the old publisher which was deleted. This is a bug in redirects.

This has been fixed, now.

**Comment by JoshStanleyDevInit** [comment]
I can confirm that this has been fixed, please feel free to close.

**Comment by gtkChop** [comment]
Closing this. Please reopen if any issues. Thanks
