### ISSUE TITLE
Registry activity count for invalid datasets

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#288]
The number of activities in an activity dataset is included in registry metadata. However, I’m not sure how this number is computed, particularly in cases when the data is invalid.

For example, this dataset:
https://iatiregistry.org/dataset/unhabitat-activity

The number of activities is listed as 824. While there are 824 `iati-activity` elements in total, there’s only one at `/iati-activities/iati-activity`.

I’ve raised the data issue with the publisher, but I think there’s also an issue with the way the registry is counting activities here.

Note that the dashboard correctly lists the number of activities as 1:
http://dashboard.iatistandard.org/publisher/unhabitat.html#h_exploringdata

**Comment by gtkChop** [comment]
@PetyaKangalova @andylolz Changes have been updated. Should be reflecting the counts when the archiver is run next time
