### ISSUE TITLE
IATI Archiver last run stats to admin page

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#290]
Show Archiver last run time stamp to the admin page to track archiver schedule.

**Comment by gtkChop** [comment]
@PetyaKangalova 

This is done. You can see the archiver status here: https://iatiregistry.org/ckan-admin/

Note: The last run timestamp is not available yet, since its deployed now. It should update by tomorrow.

**Comment by PetyaKangalova** [comment]
Tested and looks good! I can see the last run timestamp, so closing the issue.
