### ISSUE TITLE
List of metadata that are not use

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#291]
Find the metadata that are not in use.

**Comment by gtkChop** [comment]
Package (Looks like 6 of the fields are residual and not in use anymore):

 iati_version
 archive_file
 activity_period-from
 donors_country
 secondary_publisher
 donors_type
 record_updated
 department
 donors
 issue_type
 language
 filetype
 publisher
 activity_count
 data_updated
 issue_message
 issue_date
 country
 activity_period-to
 Verified
 
Publisher (All metadata are in use):
 publisher_ui
 publisher_url
 publisher_segmentation
 publisher_description
 publisher_constraints
 publisher_source_type
 publisher_units
 publisher_thresholds
 publisher_timeliness
 publisher_country
 publisher_refs
 publisher_frequency
 publisher_implementation_schedule
 publisher_frequency_select
 license_id
 publisher_contact
 publisher_record_exclusions
 publisher_data_quality
 publisher_first_publish_date
 publisher_iati_id
 publisher_contact_email
 publisher_organization_type
 publisher_field_exclusions
 publisher_ui_url
 publisher_agencies

**Comment by andreaszenasidi** [comment]
FORM FIELD | BACKEND   FIELDS | USED
---------------------------------------------
Publisher Id | name | √
Publisher Name | title | √
IATI Organisation Identifier | publisher_iati_id | √
Source | publisher_source_type | √
License | license_id | √
Type | publisher_organization_type | √
Country | publisher_country | √
**Image URL | image_url |**
State | state |√  
First published date | publisher_first_publish_date | √
Website | publisher_url | √
Address | publisher_contact | √
Contact Email | publisher_contact_email | √
Description | publisher_description | √
Implementation Schedule | publisher_implementation_schedule | √
Organisations / agencies covered | publisher_agencies | √
Timeliness of Data | publisher_timeliness | √
Frequency of publication | publisher_frequency_select | √
Frequency of publication    (extra comments) | publisher_frequency | √
Units of Aid | publisher_units | √
Segmentation of Published Data | publisher_segmentation | √
Data Definitions and References | publisher_refs | √
Field Exclusions | publisher_field_exclusions | √
Record Exclusions | publisher_record_exclusions | √
Thresholds | publisher_thresholds | √
Other Constraints | publisher_constraints | √
Data Quality | publisher_data_quality | √
User Interface | publisher_ui | √
User Interface URL | publisher_ui_url | √

Looks like there is only 1 form field that isn't used, the Image URL.

**Comment by andreaszenasidi** [comment]
@gtkChop While this was not in the initial request, would it be possible to count how many publishers use each of these fields? 
We can discuss this in our next meeting.

**Comment by jodiegardiner** [comment]
Hi @andreaszenasidi,

Raw numbers from the database for active publishers are as follows:
```
 count |                key                
-------+-----------------------------------
  1718 | publisher_ui
  1310 | publisher_url
  1718 | publisher_segmentation
  1718 | publisher_description
  1718 | publisher_constraints
  1698 | publisher_source_type
  1718 | publisher_units
  1718 | publisher_thresholds
  1718 | publisher_timeliness
  1718 | publisher_country
  1718 | publisher_refs
  1718 | publisher_frequency
  1631 | publisher_implementation_schedule
  1631 | publisher_frequency_select
  1718 | license_id
  1718 | publisher_contact
  1718 | publisher_record_exclusions
  1718 | publisher_data_quality
  1630 | publisher_first_publish_date
  1718 | publisher_iati_id
  1691 | publisher_contact_email
  1718 | publisher_organization_type
  1718 | publisher_field_exclusions
   487 | publisher_ui_url
  1718 | publisher_agencies
(25 rows)
```
