### ISSUE TITLE
Python 3 and CKAN upgrade

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#293]
Steps:

- [x] Upgrade CKAN current version to ckan 2.8.5 (python2)
- [x] Upgrade CKAN to version 2.9.1 (python 2)
- [ ] A new environment for ckan 2.9.1  in staging (python 3)
- [ ] Convert all extensions to python 3 compatible (python 3)
- [ ] Test in staging (python 3)
- [ ] Deploy python 3 to production (python 3)

**Comment by gtkChop** [comment]
Testing Done from Derilinx Team:

- Publisher create/update good
- Dataset create/update good
- Publisher delete good
- Dataset delete good
- Add members good
- Delete members good
- Activity tab good
- Login good
- CSV upload good
- Dataset archiver good
- Publisher Archiver (There is a bug - needs fixing)
- Recent Publishers good
- Pending Publishers good
- My publishers good
- Publisher Report good
- Update redirects feature good.
- Sysadmin purge good
- Download current records good
- Issues report good
- Change logs good (need to update version for ckan 2.9 upgrade)
- Regenerate API key good

**Comment by andreaszenasidi** [comment]
Testing done by the IATI Tech Team:
- Login **PASSED**
- Publisher create **PASSED**
- Publisher update **PASSED**
- Publisher delete **PASSED**
- Add members **PASSED**
- Delete members **PASSED**
- Activity Stream tab **PASSED**
- CSV upload **PASSED**
- Dataset archiver **PASSED**

**Comment by gtkChop** [comment]
@andreaszenasidi 

Yes, the bug with the publisher archiver has been fixed.

**Comment by andreaszenasidi** [comment]
Hi @andylolz , thank you for raising this issue. At the moment Derilinx is prioritizing the API documentation and [CKAN upgrade](https://github.com/IATI/ckanext-iati/issues/293). However, in the upcoming two weeks we are reviewing and prioritizing all issues raised and we will pick this ticket up as well.
