### ISSUE TITLE
Can't fully delete a user account

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#296]
A particular user wants to delete their user account. I've deleted them and they're no longer listed in the list of users: https://iatiregistry.org/user/

However, I and others can still access their account details via the activity stream on their organisation account: https://iatiregistry.org/dataset/activity/nlr-activity

Please can this be removed and the name/username anonymised? I've changed their name to NLR as a quick fix.

**Comment by gtkChop** [comment]
- There is a significant change in CKAN 2.9 for activity list.
- Hence, It would be better to upgrade CKAN and see if the user is masked in latest CKAN.
- If not there is no direct way but need to figure out a way to delete users from db (hard delete) database.

I will keep you updated once we migrate to CKAN 2.9

**Comment by PetyaKangalova** [comment]
@gtkChop  I am aware you are working now on the CKAN 2.9 upgrade. As we have been chased by the user, is it all possible to make this user "Anonymous" until we have a long term solution following the completion of the CKAN upgrade?

**Comment by gtkChop** [comment]
@PetyaKangalova @andreaszenasidi

Here is the changes that is implemented: 

- Only sysadmin can see deleted users

**Comment by gtkChop** [comment]
@andreaszenasidi @PetyaKangalova 

Deployed

**Comment by andreaszenasidi** [comment]
@gtkChop tested on the live site and it's not anonymizing deleted users

![image](https://user-images.githubusercontent.com/74558657/141959480-c0559c69-f3c2-4820-9652-d738bec15a75.png)

**Comment by adrianoamaral** [comment]
@gtkChop can you please check if it's deployed in prod or staging? Andrea will tested in the staging, once the test made in prod fail.

**Comment by andreaszenasidi** [comment]
@gtkChop @adrianoamaral Works in staging, not in production.

**Comment by gtkChop** [comment]
@andreaszenasidi It is deployed in production.

If you are logged in as sysadmin, you can see users. 

Users are shown as Anonymous for all the users who are not a sysadmin. Please see the below screenshot.

<img width="652" alt="Screen Shot 2021-11-18 at 12 52 23" src="https://user-images.githubusercontent.com/32418025/142410627-7d203deb-1c78-4d1d-8bb1-2c21362d9375.png">

**Comment by andreaszenasidi** [comment]
@gtkChop I tested it again in production and it works. Not sure what I did earlier that wasn't working.
