### ISSUE TITLE
Publishers list shows publisher with private dataset

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#297]
Example: Barry Aid

https://iatiregistry.org/publisher/barryaid

**Comment by gtkChop** [comment]
@PetyaKangalova This is fixed and the count matches.

**Comment by PetyaKangalova** [comment]
@gtkChop  I just checked and the list is now correct, including all existing publishers. The issue is resolved and the ticket can be closed.

**Comment by gtkChop** [comment]
Closing this
