### ISSUE TITLE
Organisation list API - filter option

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#298]
- Documentation says yes possible
- When I tried this doesn't work (not only in IATI but in other CKANs as well).
- https://docs.ckan.org/en/2.9/api/index.html

Need to investigate on this.

**Comment by gtkChop** [comment]
https://iatiregistry.org/api/action/organization_list?organizations=abyrint&organizations=acfspain&all_fields=true

**Comment by andreaszenasidi** [comment]
Tested and works fine.
