### ISSUE TITLE
 XML errors for SIDA's files

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#299]
I can see at the iatiregistry page that it tells us that there were some problems accessing some of Sida’s IATI-files.

https://www.iatiregistry.org/publisher/sida?page=4

One example is the file for India: http://iati.openaid.se/xml/IN.xml

![image](https://user-images.githubusercontent.com/27764077/98944754-6f680500-24e9-11eb-97e7-7003ac63b55b.png)

On my laptop some files fail to open and other open with valid xml (though not always conforming to the IATI schema.

@akmiller01 has also tried downloading that openaid.se 998b file programmatically and it worked just fine. It's rather large (24 MB) but hopefully that wouldn't break the registry...

```
Resolving iati.openaid.se (iati.openaid.se)... 13.48.95.144, 13.49.54.253, 13.48.36.108
Connecting to iati.openaid.se (iati.openaid.se)|13.48.95.144|:443... connected.
HTTP request sent, awaiting response... 200 OK

```

@gtkChop please can you also look into the errors and let us know whether it's a bug on the Registry to be fixed, or what the publisher needs to do to fix their files.

Thank you

**Comment by gtkChop** [comment]
Hi, @amy Thanks for the detailed description.

@amy-silcock  @PetyaKangalova 

We are currently upgrading the ckan 2.9 (step towards python 3) in staging and will look at this as soon as we finished the task. Thanks

**Comment by gtkChop** [comment]
@andreaszenasidi @amy-silcock 

Is this issue still relevant?

I tried running archive manually for the file https://iati.openaid.se/xml/IN.xml and looks good.

**Comment by andreaszenasidi** [comment]
@gtkChop SIDA confirmed that this was an issue on their end. I will close this ticket.
