### ISSUE TITLE
Organisation list- API endpoint

### ISSUE THREAD

**Issue by PetyaKangalova** [IATI/ckanext-iati#300]
@gtkChop I have a question about the Organisation list API endpoint: https://iatiregistry.org/api/action/organization_list

Currently, it looks like it includes organisations that have been approved on the IATI Registry, but have **not** published any data so far, like this one: https://www.iatiregistry.org/publisher/onepercentclub 

I think it might be related to this issues #297 .

The public API endpoint should give you the list of organisation that have at least one datasets made public.

**Comment by gtkChop** [comment]
@PetyaKangalova This is the case when for download org and publisher page. 

However, organization_list will return all approved organizations (irrespective of the number of datasets). This is the expected behavior from the organization API list.
