### ISSUE TITLE
_update_resource error

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#301]
Hi Swaroop,

We've noticed that the last updated date for one of Germany BMZ's files hasn't updated as expected. It's saying 2019 rather than a more recent 2020 date.

Running the archiver I get this message: 
![image](https://user-images.githubusercontent.com/27764077/99557422-94adb500-29ba-11eb-9e2b-af35505df3d0.png)

Is this an internal error with the Registry? If yes, please can we fix it.
If not, what does the publisher need to do to fix it?

Best,

Amy

**Comment by gtkChop** [comment]
@amy-silcock 

Fixed the coding the. But looks like the resource is huge. Please see the error.

```
Download Error · (March 12, 2021)
Content-length 70666399 exceeds maximum allowed value 60000000
```

**Comment by andreaszenasidi** [comment]
@gtkChop looks good. I will notify the publisher about the size of the dataset.
