### ISSUE TITLE
Travis-CI.org will be deprecated 31 Dec, 2020 - migrate to Travis-CI.com or something else

### ISSUE THREAD

**Issue by nosvalds** [IATI/ckanext-iati#302]
https://travis-ci.community/t/org-to-com-migration-deadline/10260 

Migrate tests to travis-ci.com from travis-ci.org by Dec 31st if you intend to keep using TravisCI

**Comment by nosvalds** [comment]
Feel free to change the priority/close this issue if you aren't still actually using TravisCI.

**Comment by nosvalds** [comment]
Looking at the code more closely this is actually low priority. The testing code has been commented out since 2017… 

https://github.com/IATI/ckanext-iati/blob/master/bin/travis-install-dependencies
https://github.com/IATI/ckanext-iati/blob/master/bin/travis-run-tests

Looks like someone meant to bring them back in after an upgrade or something but never did.

**Comment by siemvaessen** [comment]
Does this mean no tests are performed at all on the Registry @nosvalds ? (just scanning the issues as I created a new one :-)

**Comment by andreaszenasidi** [comment]
@siemvaessen at the moment no automated tests are running. This is related to [308](https://github.com/IATI/ckanext-iati/issues/308) and [175](https://github.com/IATI/ckanext-iati/issues/175).

**Comment by Bjwebb** [comment]
Task is to re-enable tests, probably on GitHub Actions, see https://github.com/IATI/ckanext-iati/issues/175 for that.
