### ISSUE TITLE
Deleted dataset by IATI Archiver

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#305]
A [publisher](https://iatiregistry.org/publisher/tgh) reported via the IATI support desk that the IATI Archiver deleted their dataset. Would be great to understand why this happened.

**Activity stream:** https://iatiregistry.org/publisher/activity/tgh 

![image](https://user-images.githubusercontent.com/74558657/104031973-5f0c9780-51c5-11eb-97cf-cd9be6e25aaf.png)

**Comment by AudreyIATI** [comment]
Adding to this conversation with a different [publisher](https://iatiregistry.org/publisher/raleigh_int) that has experienced the same issue.
Activity stream: [https://iatiregistry.org/publisher/activity/raleigh_int/0](https://iatiregistry.org/publisher/activity/raleigh_int/0)


<img width="736" alt="Raleigh International" src="https://user-images.githubusercontent.com/74548472/105973345-89df6280-6084-11eb-95a9-20c713947e18.png">

**Comment by andreaszenasidi** [comment]
There was a bug fixed in the config, needs to be monitored and reported if it happens again.

**Comment by andreaszenasidi** [comment]
Closing since it was not reported again.
