### ISSUE TITLE
"Download List" on publishers page saves all formats as "iati-publishers.csv"

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#307]
## Steps to reproduce
 1. Go here: https://iatiregistry.org/publisher
 2. Click "Download List"
 3. Select any format other than CSV (e.g. JSON)
 4. Downloaded file is called iati-publishers.csv, and is served with content type `text/csv`
 5. (On my machine) the file is therefore previewed as if it were a CSV, and is default opened with Microsoft Excel

I’ve added a comment where I think this issue comes from:
https://github.com/derilinx/ckanext-iati/commit/9331822c#r45953386

## Other comments
Also note that these URLs have changed. E.g.:
https://iatiregistry.org/publisher/download_list/csv

…is now:
https://iatiregistry.org/publisher/download/csv

---

It looks like this issue comes from this commit:
https://github.com/derilinx/ckanext-iati/commit/9331822c

…however, I don’t think this commit exists on the master branch of the IATI repo (or, indeed, in the IATI repo at all). I’ve made this point before (see e.g. #168) but it would be good practice to deploy from the `master` branch of the IATI repo, rather than the dev branch of some other repo.

**Comment by andreaszenasidi** [comment]
@andylolz, thank you for raising this issue. We reviewed all open issues as part of a prioritization meeting and this ticket was deemed to be a high priority. It will be worked on in the first quarter of 2021. Thanks again for reporting it!

**Comment by andylolz** [comment]
That’s great, thanks @andreaszenasidi.

**Comment by gtkChop** [comment]
Thanks @andylolz raising the issue. It was a bug when we migrated to ckan 2.9.1

@andreaszenasidi 

This is fixed and deployed to production.

**Comment by andylolz** [comment]
> This is fixed and deployed to production.

Fix works for me! Thanks!

However, I don’t see it on the `master` branch of this repository?

**Comment by gtkChop** [comment]
@andylolz 

It's on the derilinx repo. Recently we have migrated to ckan 2.9.1 and the code is still pending to push to ckanext-iati public repo.

And also, possible need to update README as well. Thanks

**Comment by andreaszenasidi** [comment]
Tested and works as expected. Thanks for the fix @gtkChop!
