### ISSUE TITLE
New organisation "My Test Publisher 3" added

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#311]
https://iatiregistry.org/publisher/my-test-publisher-3

I guess this was approved in error?

It has already been pulled into services including d-portal:
![Screenshot 2021-01-20 at 09 48 38](https://user-images.githubusercontent.com/464193/105157411-db2ba700-5b04-11eb-8dbc-a5130edcc3d2.png)

/cc @amy-silcock

**Comment by andreaszenasidi** [comment]
@andylolz thanks for raising this. The test publisher is now deleted.

**Comment by andylolz** [comment]
Great - thanks for addressing this so quickly.
