### ISSUE TITLE
Add new member to a publisher using email invite

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#315]
I’m struggling with a publisher on Registry. They want to add a new member of the team and delete themselves as the admin.

However, when they try to add the new person, the page says “internal server error”, see screengrab below.

I tried too and received the same message – so did other members of the team.

 

Here is the publisher – https://iatiregistry.org/publisher/mic-uk

**Comment by gtkChop** [comment]
This is a core CKAN bug where validation error is not captured in groups add new member views.
https://github.com/ckan/ckan/blob/ckan-2.9.1/ckan/views/group.py#L1091

**Comment by andreaszenasidi** [comment]
@gtkChop University of Oxford just tried to delete an old admin and they got a 404 error. However, as a sysadmin I was able to delete the user.

**Comment by gtkChop** [comment]
@andreaszenasidi 

Works as expected. I cannot reproduce the error. Maybe that old user is already deleted?. A sysadmin can remove members from the organization even though the user is deleted because user delete is soft delete (does not entirely remove from the database).

**Comment by andreaszenasidi** [comment]
@gtkChop I tested on staging and looks like it's working.
