### ISSUE TITLE
Issue with api/3/action/organization_show

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#317]
Hi,

Issue with the CKAN API raised by a user:

"We use IATI API to download USAID and MCC data. I use this API call to get list of all packages https://iatiregistry.org/api/3/action/organization_show?id=usaid&include_datasets=true&include_dataset_count=true. However, recently whenever we call this API the “packages” section of the response only contain the top 10 packages name.

I check the API document I and I didn’t see any changes. Can you please let me know why I only get the top 10 instead of all of them."

Do we know the reason behind this?
Please can this either be fixed or the change and solution documented?

Thanks,

Amy

**Comment by gtkChop** [comment]
@amy-silcock 

CKAN **organization_show** API with parameter **include_all_dataset**=True is a really expensive process. Hence, the API has a limit of 10 datasets.

A better way to get all datasets belongs to a publisher is by **package_search** API.

API **organization_show** gives an id. We can use this id to get all the datasets that belong to an organization. E.g.

https://iatiregistry.org/api/3/action/package_search?fq=owner_org:8c54d3ba-1da7-40a8-a1cb-598cfb1ba6c1&rows=1000

I hope this helps. Thanks

**Comment by SoleCode** [comment]
> @amy-silcock
> 
> CKAN **organization_show** API with parameter **include_all_dataset**=True is a really expensive process. Hence, the API has a limit of 10 datasets.
> 
> A better way to get all datasets belongs to a publisher is by **package_search** API.
> 
> API **organization_show** gives an id. We can use this id to get all the datasets that belong to an organization. E.g.
> 
> https://iatiregistry.org/api/3/action/package_search?fq=owner_org:8c54d3ba-1da7-40a8-a1cb-598cfb1ba6c1&rows=1000
> 
> I hope this helps. Thanks

Thank you the suggested API solved my problem.

**Comment by amy-silcock** [comment]
Thanks @gtkChop!

@SoleCode do let us know if you have any other questions or issues.

**Comment by SoleCode** [comment]
@amy-silcock thank you, we appreciate the help.

**Comment by gtkChop** [comment]
Please re-open if any issues again. Thanks
