### ISSUE TITLE
First Published date on creating new publisher (sysadmin only)

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#318]
**Description:**
I was not able to create a test registry on staging when I used the First Published Date field. I keep getting invalid date format error.

**Comment by gtkChop** [comment]
@andreaszenasidi 

Fixed this. Please let me know if face any issues again. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop tested on staging and it works. Thank you!

**Comment by gtkChop** [comment]
Closing this. Please reopen if any issues again. Thanks
