### ISSUE TITLE
Registry newsfeed - 404 error

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#320]
The Registry newsfeed is producing a 404 error: https://www.iatiregistry.org/revision

![image](https://user-images.githubusercontent.com/27764077/106734503-01743b00-660b-11eb-9e70-fc52b79d3877.png)

**Comment by andreaszenasidi** [comment]
The News Feed was deprecated in the new CKAN ([changelog](https://docs.ckan.org/en/2.9/changelog.html)).
