### ISSUE TITLE
IATI Registry- URL error

### ISSUE THREAD

**Issue by PetyaKangalova** [IATI/ckanext-iati#322]
@gtkChop I have been in touch with one of our IATI publishers ([IFC](https://iatiregistry.org/publisher/ifcwbg)) as they data was not accessible in the URL they have provided. They have now fixed that issue and the URL linked to their data refer to the IATI XML: https://disclosures.ifc.org/iati/ifc-af.xml

However, the Registry still returns an error and I am unclear what it means and what they still need to fix. Could you let me know what they need to do so there is no longer an error?

![image](https://user-images.githubusercontent.com/24607542/107355902-06803100-6ac8-11eb-9b2a-98334bbd51f5.png)

**Comment by gtkChop** [comment]
@PetyaKangalova 

I was the problem with their hosting server. They do not allow our archiver to get the head request.

I found an alternative that fixes the issue. I have deployed the new version of archiver today and hopefully, by tomorrow all the URL issues should be resolved.

**Comment by andreaszenasidi** [comment]
The issue is resolved. Thanks @gtkChop
