### ISSUE TITLE
AU-5 data issue

### ISSUE THREAD

**Issue by siemvaessen** [IATI/ckanext-iati#323]
Both Datastore and D-Portal are unable to retrieve AU-5 data from the originating AU-5 source. Humans are able to download the files, but it's very likely some machine crawling not-allowed of kinds is in place on the originating location making it impossible to download files in an automated fashion. As this is not a Datastore nor D-Portal issue, we have [closed the issue ](https://github.com/zimmerman-team/iati.cloud/issues/2470)on the Datastore end have added it to this issue tracker as it seems a more appropriate place to log this issue.

**Comment by andylolz** [comment]
Same problem raised here: codeforIATI/iati-data-bugtracker#9

I contacted the email addresses I found in DFAT’s metadata, but didn’t hear back.

**Comment by andylolz** [comment]
The registry archiver is now also showing issues fetching ausgov data:

![Screenshot 2021-03-04 at 08 32 30](https://user-images.githubusercontent.com/464193/109934209-2b7d5380-7cc4-11eb-96b9-04e26a678612.png)

**Comment by gtkChop** [comment]
@andylolz 

This is giving timeout

```
        with requests.get(url, headers=req_headers, timeout=url_timeout, verify=False, stream=True) as res:
            resp_headers = res.headers
```

**Comment by andylolz** [comment]
> I have changed the user agent, theoretically, this should be fixed when the archiver runs for the next time.

Nice – looks like it worked! 👏

**Comment by andreaszenasidi** [comment]
Looks good.
