### ISSUE TITLE
Change the wording of automated email from Registry for new publisher accounts

### ISSUE THREAD

**Issue by AudreyIATI** [IATI/ckanext-iati#329]
To improve the user experience of new publisher accounts and keep them informed of what to expect, we'd like to make some small changes to the automated email new publisher accounts receive after successfully creating an account:

1.	Publisher creates new publisher account
2.	If all correct and account is approved by IATI Tech Team, user receives automated confirmation email

**NEW wording for automated confirmation email:**

Dear (Name),

Congratulations, the publisher that you created on the IATI Registry has been approved.

Well done for taking the first step to join over 1300 others in becoming an IATI publisher!
https://iatiregistry.org/publisher/[publisher name]

Your next step is to start creating your IATI files. Guidance for this can be found on the IATI website under step 2: https://iatistandard.org/en/guidance/publishing-data/publishing-files/publishing-checklist/

Should you have any queries or support needs, then please email the IATI Helpdesk at: support@iatistandard.org  

You can also join the conversation with other new publishers in the "Newbies Corner" on IATI Connect:
https://iaticonnect.org/newbies-corner/stream

Kind regards,
IATI Technical Team

**Comment by gtkChop** [comment]
@andreaszenasidi 

Estimation of **0.5 day.**

**Comment by gtkChop** [comment]
@andreaszenasidi @AudreyIATI 

This is done. Please see the staging site. Below is the screenshot of the same
![Screen Shot 2021-09-26 at 09 27 13](https://user-images.githubusercontent.com/32418025/134798177-9255631e-51f8-4ec6-a863-1d0048628e01.png)


Please let me know if you need any changes.

**Comment by andreaszenasidi** [comment]
@gtkChop Thanks for this! I found one small issue, the support email doesn't appear as an email address.

![image](https://user-images.githubusercontent.com/74558657/135269290-dbb93b6f-ee7f-4076-976d-394370f06e22.png)

**Comment by gtkChop** [comment]
@andreaszenasidi 

Changed few things. Email is clickable now. Please review and let me know if you need any updates on this. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop There is still an issue. When I moved 1 publisher account from Active to Pending. And Then I went ahead and Approved again the account I received the below email, not the one in the requirements:

![image](https://user-images.githubusercontent.com/74558657/137470516-5cd7b73a-b241-4a35-8044-74fc3d10b1f0.png)

**Comment by gtkChop** [comment]
@andreaszenasidi 

Yes, maybe. can you please test again? I have switched the branch.

**Comment by gtkChop** [comment]
@andreaszenasidi Updated text.

**Comment by andreaszenasidi** [comment]
@gtkChop looks good!
