### ISSUE TITLE
`organization_list` with `all_fields=true` – maximum 50 results

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#333]
I guess as part of the recent CKAN upgrade (#293), the upper limit of organizations returned has been reduced to 50 (previously, 100 worked).

[The documentation suggests](https://docs.ckan.org/en/2.9/api/#ckan.logic.action.get.organization_list) this is set in the site’s configuration, in `ckan.group_and_organization_list_all_fields_max`.

This change has caused a problem for the IATI Dashboard (IATI/IATI-Dashboard#578), and IATI publishing statistics (IATI/IATI-Publishing-Statistics#12), both of which assume a page size of 100 will work.

**Comment by gtkChop** [comment]
@andylolz 

organization_list with all_fields=True is an expensive process. Hence there is a limit.

Please use package_search?owner_org=<> to get all datasets and to get details of an organization please use organizatoion_show.

**Comment by andylolz** [comment]
> organization_list with all_fields=True is an expensive process. Hence there is a limit.

Thanks @gtkChop – understood.

If changes like this are made to the registry API, derilinx or IATI should provide some notification in advance. I think I’m right in saying this breaking change was made without warning.

It’s particularly tricky in this case, because the request fails silently. I.e. if 100 results are requested, the request succeeds, but 50 results are returned.

**Comment by gtkChop** [comment]
@andylolz 

Thanks for the input. Yes, will notify users in the future if anything changes like this. Thanks

**Comment by andylolz** [comment]
Looks like this endpoint is now consistently 504ing:
https://iatiregistry.org/api/3/action/organization_list?all_fields=true&include_extras=true&include_tags=true&include_groups=true&include_users=true&limit=50

I’ve now migrated away from using it, but wondered if it was related to a recent change.
