### ISSUE TITLE
3rd party service POST connection to Registry (request/conversation)

### ISSUE THREAD

**Issue by siemvaessen** [IATI/ckanext-iati#334]
As part of our work for [AIDA](https://www.aida.tools/), we will offer organisations the option to register with the IATI Registry so they can manage their data in AIDA and synchronise back to the Registry. As organisations make use of an API key to synchronise Registry metadata into AIDA enabling organisations to manage data in AIDA, we would also like to offer them a way of avoiding to directly make use of Registry. 

This scenario will allow organisation to just register with AIDA and the complete registration package is then sent to the Registry enabling to stay on 1 single centralised platform rather than having to deal with the Registry itself. For this I am wondering if any scenario has been taken into account where a 3rd party service (AIDA) gets to connect and is allowed to POST.

cc @PetyaKangalova @amy-silcock

**Comment by andreaszenasidi** [comment]
Hi @siemvaessen, it’s great to hear about AIDA’s future plans. At the moment we don't have plans to implement this feature in the Registry API, however seems like this could be a useful feature to consider in the long term. If you would like you could add more details about your specific needs to this GitHub issue for future reference.

Even though the API doesn't have this specific feature, I did want to share with you our revised [Registry API documentation](https://iatistandard.org/en/iati-tools-and-resources/iati-registry/iati-registry-api/) which could be helpful in developing other areas of AIDA.
