### ISSUE TITLE
New automated emails for new publisher accounts and successfully published files

### ISSUE THREAD

**Issue by AudreyIATI** [IATI/ckanext-iati#335]
To improve the user experience of new publisher accounts and keep them informed of what to expect, we’d like to introduce new automated emails that publisher accounts will receive after they create an account on registry and also after they successfully publish a file:

1. Publisher creates new publisher account
2. User receives an automated “holding” email, confirming registration (**NEW - see text below**)
3. Helpdesk receives alert to approve new publisher account (no action required)
4. If all correct and account is approved by IATI Tech Team, user receives automated confirmation email (NEW – already raised in issue #329)
5. If something is incorrect, BA’s contact user with the macro saved in Zendesk (no action required)
6. Once errors fixed, BA’s approve account and user receives automated confirmation email (**NEW see text below**)
7. After user publishes a file to IATI, they receive a confirmation email so they know data has successfully published (**NEW see text below**)

**NEW Automated confirmation email (2 and 6):**

Dear (Name),

Thank you for registering with IATI.
A member of the Technical Team will review your account and contact you in 1-3 days with an update.

Kind regards,
IATI Technical Team

**NEW Automated confirmation email (7):**

Dear (Name),
 
Congratulations! Your file(s) have been successfully published to IATI  (https://iatiregistry.org/publisher/[publisher name]).
 
To view your published data, please check [d-portal](http://d-portal.org) (allow 24 hours after publishing).

You can also do a more detailed search of your published data via the [Datastore](https://iatidatastore.iatistandard.org/querybuilder/).

Should you have any queries or support needs, then please email the IATI Helpdesk at: support@iatistandard.org
  
Kind regards,
IATI Technical Team

**Comment by gtkChop** [comment]
@andreaszenasidi 

I can see three processes here in total:

* Publisher should receive email on creation - 0.5
* Publisher should receive email on publisher account approval - 0.5
* Notification for publisher while adding a new dataset for the approved publisher. - 1

**2.5 days** in total including testing and deployment

**Comment by gtkChop** [comment]
@adrianoamaral @andreaszenasidi 

This is implemented in staging. Please let me know if any changes are required. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop I was testing on staging but I did not receive any of the two emails.

**Comment by gtkChop** [comment]
@andreaszenasidi 

Deployed to staging. Can you please check your spam folder too? Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop looks good! 
When a new dataset is published I receive the email. I wanted to check, if a publisher publishes a dataset via the Registry API, would the same email be sent out?

**Comment by andreaszenasidi** [comment]
@gtkChop tested the API on staging and the email was sent.
