### ISSUE TITLE
/api/3/action/package_show: `extras` key-value pairs appear in duplicate

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#338]
E.g. https://iatiregistry.org/api/3/action/package_show?id=aics-bo

There are two copies of the key-value pairs shown in the screenshot:

![Screenshot 2021-03-03 at 19 24 37](https://user-images.githubusercontent.com/464193/109860643-4fa24b80-7c56-11eb-8ac0-4920346e9e23.png)

**Comment by gtkChop** [comment]
@andylolz 

This is fixed. Please let me know if you have any questions. Thanks

**Comment by andylolz** [comment]
That’s great! Thanks @gtkChop.

**Comment by andreaszenasidi** [comment]
Looks good. Thanks @gtkChop
