### ISSUE TITLE
dmru-999 - archiver says “File is an HTML document” but it is XML

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#339]
[This dataset](https://iatiregistry.org/dataset/dmru-999) shows an error.

However, the data has been valid XML since 21 Februrary 2021.

![Screenshot 2021-03-03 at 22 59 42](https://user-images.githubusercontent.com/464193/109883991-2690b380-7c74-11eb-8540-cc0946223743.png)

**Comment by andreaszenasidi** [comment]
@andylolz Thanks for reporting this. The publisher republished some of their datasets, this dataset doesn't exist anymore.

**Comment by andylolz** [comment]
Great – thanks for following up on this
