### ISSUE TITLE
france-cicid – archiver shows no error, but the linked data is HTML

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#342]
[france-cicid](https://iatiregistry.org/dataset/france-cicid) links to [an HTML page](https://www.diplomatie.gouv.fr/en/french-foreign-policy/development-assistance/news/2018/article/interministerial-committee-for-international-cooperation-and-development-a-new), rather than an IATI XML document. This has been the case since March 2020. However, the archiver does not show an error, and does not list an error in the dataset metadata.

![Screenshot 2021-03-03 at 23 19 05](https://user-images.githubusercontent.com/464193/109885686-db2bd480-7c76-11eb-8064-41985cef460d.png)

**Comment by andylolz** [comment]
The same issue applies to [transparency-international-1_2062](https://iatiregistry.org/dataset/transparency-international-1_2062).

**Comment by Bjwebb** [comment]
There's now an error message there, about content types. It looks kind of odd though, so I've made a new issue for that.

I've checked another dataset with HMTL, and there's an appropriate warning there too: https://iatiregistry.org/dataset/solidaridad-waf-org
