### ISSUE TITLE
Archiver shows 403 error for maec-57 and maec-100

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#343]
[maec-57](https://iatiregistry.org/dataset/maec-57) and [maec-100](https://iatiregistry.org/dataset/maec-100) both show 403 errors, but both datasets are fine. It looks like these errors have shown on the registry since March 2019.

I wonder if this was just a temporary error, and the archiver just needs to try again at fetching these datasets?

![Screenshot 2021-03-03 at 23 26 45](https://user-images.githubusercontent.com/464193/109886423-ed5a4280-7c77-11eb-822a-15fc2d2ec50a.png)

**Comment by andreaszenasidi** [comment]
@andylolz Thanks for reporting this. The Archiver error message is clearer now, there is an issue with the Country metadata. I will reach out to the publisher.

**Comment by andylolz** [comment]
Thanks @andreaszenasidi, that error message is much clearer.

Does the registry now prevent invalid updates to metadata? I assume these errors crept in before this metadata validation, but hopefully it’s not possible for new errors of this sort to be added.

**Comment by gtkChop** [comment]
@andreaszenasidi @andylolz 

I don't see any error now. Archiver is updated recently which shows if there are any existing errors (E.g. country code)

**Comment by andylolz** [comment]
Looks good to me. Thanks!

**Comment by andreaszenasidi** [comment]
Looks good, I will close this issue.
