### ISSUE TITLE
unfpa-glbl – archiver gets version number wrong

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#345]
[unfpa-glbl](https://iatiregistry.org/dataset/unfpa-glbl) – version number is shown as v2.01. In fact, it’s v2.03
![Screenshot 2021-03-03 at 23 44 42](https://user-images.githubusercontent.com/464193/109887853-6fe40180-7c7a-11eb-9c62-f84f19c1e608.png)

![Screenshot 2021-03-03 at 23 45 12](https://user-images.githubusercontent.com/464193/109887898-825e3b00-7c7a-11eb-9402-07144dd75623.png)

**Comment by andylolz** [comment]
This also applies to [scuk-archive](http://iatiregistry.org/dataset/scuk-archive). The correct version is v2.03, but the version shown is v1.04.

**Comment by andreaszenasidi** [comment]
@andylolz Seems they were updated now to the correct version.

**Comment by andylolz** [comment]
Agreed – metadata for both datasets looks correct to me.
