### ISSUE TITLE
User experience enhancement - Simplify account creation

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#349]
One of the user experience enhancement recommendations was to simplify the account creation process. At the moment new publishers need to create two separate accounts, a user account and a publisher account. 

**Prerequisite:** https://github.com/IATI/ckanext-iati/issues/350 and https://github.com/IATI/ckanext-iati/issues/351  

### Requirements:
**1. Add 2 options to the Registration page**
- Remove the **Why sign up?** section of the [register page](https://staging.iatiregistry.org/user/register) 
![image](https://user-images.githubusercontent.com/74558657/121698059-8ee9ff00-cac5-11eb-83a9-16ccfdf97ad0.png)

- Add 2 options to the [registry page](https://staging.iatiregistry.org/user/register) 1) Register a new Publisher and 2) Register a new User
The mock of the page is below; the colour of the buttons and boxes should match the theme colour of the Registry. 
![image](https://user-images.githubusercontent.com/74558657/122740742-2dbbeb80-d27c-11eb-9b0d-e6ed2401f016.png)

**2. Register a new User** 
- When **Create User account** button is clicked (mock above), they should be redirected to the current register page https://staging.iatiregistry.org/user/register to create a new user account. No changes are needed on this page.
- When a new user account is created successfully they are currently redirected to the Newsfeed. Add a green banner (similar to other info banners in the Registry) to this page with the following text:
_User account was created successfully. Please contact your organisation’s IATI administrator to add you as a Member of the organisation’s Publisher account._

**3. Register a new Publisher** 
- When **Create Publisher account** button is clicked (mock above), redirect to a new page that will allow users to create both a new Publisher and an admin User account in one step.
- The page should look the same as the current https://iatiregistry.org/publisher/new page, with the addition of the User account fields. 
- The User account fields (same fields as the current [user registration fields](https://staging.iatiregistry.org/user/register)) should be displayed before _Group name:_ Publisher Information (implemented in https://github.com/IATI/ckanext-iati/issues/350). The user account fields _Group name_ should be Admin User Information
- Required fields, error messages and validation should follow the rules outlined and implemented in https://github.com/IATI/ckanext-iati/issues/350 and https://github.com/IATI/ckanext-iati/issues/351 
- When the user clicks **Create Publisher** button both a new Publisher account and a new User account should be created. The User account should be linked as a Member with an Administrator role to the newly created Publisher account.

**Comment by gtkChop** [comment]
@andreaszenasidi 

Please see the revised efforts:

- 3 days to implement a feature 
     * We need to create a new form that includes both user details and publisher details
     * Need some kind of validation and workaround if the user details (email) already exist.
- 1 day to test and deployment
- 1 day for feedback after implementing the feature (Ay changes to the implemented feature).

**Total of 5 days.**

**Comment by gtkChop** [comment]
@andreaszenasidi 

Development is done. Please let me know if any bugs or need any changes. Thanks

https://staging.iatiregistry.org/register

Pending:

```
When a new user account is created successfully they are currently redirected to the Newsfeed. Add a green banner (similar to other info banners in the Registry) to this page with the following text:
User account was created successfully. Please contact your organisation’s IATI administrator to add you as a Member of the organisation’s Publisher account.
```

**Comment by andreaszenasidi** [comment]
@gtkChop I completed the testing and found a few issues:
1. _[This was missing from initial requirements]_ **On the [User Login page](https://iatiregistry.org/user/login) the **Create Account** should take users to the Registration page** 
![image](https://user-images.githubusercontent.com/74558657/135266853-237ec9a7-b2a9-47d7-8480-99143f33609a.png)

**Requirements:**
- rename 'Create an Account' button to 'Register'
- when the button is clocked it should redirect to https://iatiregistry.org/register
- change the text 'Then sign right up, it only takes a minute.' to 'Then sign right up, it only takes a few minutes.'

**2. Spelling of organisation is incorrect**
**Requirements:**
- Update 'organization' to 'organisation' (spelt with s) on page https://staging.iatiregistry.org/register. There are 2 instances where the word is misspelt. 

**3. Rename 'User Information' group name to 'Admin User Information' on page https://staging.iatiregistry.org/register_publisher/**

**4. Missing Profile Picture field from to the Admin User Information group from Register a Publisher page**
**Requirement:**
- Similar to the Profile Picture field found on https://staging.iatiregistry.org/user/register, add a new field to the [Register a Publisher page](https://staging.iatiregistry.org/register_publisher/) Admin User Information group

**5. Update the 'Register as an additional user to your organization's IATI publisher account' text on page https://staging.iatiregistry.org/register to include the link 'Register as an additional user to your organization's [IATI publisher account](https://iatiregistry.org/publisher/)'**

**Comment by gtkChop** [comment]
@andreaszenasidi  

Completed all the tasks above. Please let me know if you encounter any issues. Thanks

**Comment by gtkChop** [comment]
@andreaszenasidi This is fixed. Please let me know if you encounter any further bugs. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop the logo now is saved fine if you fill in all the required fields correctly. If however, you make an error and the validation kicks in then after you fix the errors and you save the publisher the user logo is not saved ok. You will see this:  
![image](https://user-images.githubusercontent.com/74558657/139660683-ec6f1736-146a-4982-b5eb-db32c5f88252.png)

**Comment by gtkChop** [comment]
@andreaszenasidi 

On profile image upload bug, there is already bug associated with it: https://github.com/ckan/ckan/issues/5664

**Comment by andreaszenasidi** [comment]
@gtkChop I just noticed that one requirement was not implemented yet.

**2. Register a new User**
When a new user account is created successfully they are currently redirected to the Newsfeed. Add a green banner (similar to other info banners in the Registry) to this page with the following text:
_User account was created successfully. Please contact your organisation’s IATI administrator to add you as a Member of the organisation’s Publisher account._

**Comment by gtkChop** [comment]
@andreaszenasidi Done

**Comment by andreaszenasidi** [comment]
@gtkChop looks good, thanks!

The deployment date for this ticket is January 26th.
