### ISSUE TITLE
User experience enhancement - Simplify Publisher registration form

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#350]
One of the user experience enhancement recommendations was to simplify/dummy-proof the Publisher registration form.

### **Requirements:** 

**1. Clearly indicate which fields are required.** 
	- Require field label: Publisher Id * (asterisk with red color)
	- When a or multiple required fields are missed and the user clicks 'Create Publisher' turn all required field boxes/lists in red and in focus, scroll to the first required field and add the popup message 'Please fill required field'
	- Remove the blue box validation error summary from the top of the page. Only show error messages in red over the specific fields.
![image](https://user-images.githubusercontent.com/74558657/113991986-e9a77600-984a-11eb-98a3-61b29da611a6.png)

**2. Do not pre-select choice for fields with multiple-choice options.** 
	- Add 'Please select' to all drop-down lists, except the Source field, this should still default to 'Primary'

**3. Regroup fields meaningfully; name groups and fields meaningfully.**
	_Group name:_ Publisher Information 
	_Fields (required fields should come first):_ Publisher ID
          	   Publisher Name
                   IATI Organisation Identifier
		   Type -> rename to Publisher Type
                   License  ->  rename to: Data License   
	           Country
	           Image URL -> rename to Publisher Logo URL
		   State (should not be visible when you create a new publisher, only when you edit - except for sysadmins)
	           Description
	_Group name:_ Contact Information
	_Fields (required fields should come first):_ Email
		   Website
		   Address
	_Group name:_ Data Publishing Additional Information                
	_Fields (required fields should come first):_	Source		                           
                First Published Date
		Implementation Schedule
		Organisations / agencies covered
		Timeliness of Data
		Frequency of publication
		Frequency of publication (extra comments)
		Units of Aid
 		Segmentation of Published Data
		Data Definitions and References
		Field Exclusions
		Record Exclusions
		Thresholds
		Other Constraints
		Data Quality
		User Interface
		User Interface URL	-> rename to: User Interface Website	

**4. Limit the number of optional sections.** (Used fields: https://github.com/IATI/ckanext-iati/issues/291)
	- We will not remove any fields for now, since it's a longer process because the wider IATI community needs to be consulted before any fields are removed.

**5. Update left side panel to include the following text**
- Title: Get Support
- Description: Dont' hesitate to contact the IATI technical team for support at support@iatistandard.org
![image](https://user-images.githubusercontent.com/74558657/114035179-c1357100-9876-11eb-8f40-d1f4bb32652a.png)

**Comment by gtkChop** [comment]
@andreaszenasidi 

1. Clearly indicate which fields are required. - **2 days**
2. Do not pre-select choice for fields with multiple-choice options. - **0.5 day**
3. Regroup fields meaningfully; name groups and fields meaningfully. - **1.5 days**
4. Limit the number of optional sections. (Used fields: #291) - **0.5 day**
5. Update left side panel to include the following text - **0 day**

**Total: 4.5 days**

**Comment by gtkChop** [comment]
@andreaszenasidi 

This is done please refer to the staging site. Please let me know if you have any questions or need any changes on UI.

For further details please refer to ticket: https://github.com/IATI/ckanext-iati/issues/349

**Comment by andreaszenasidi** [comment]
@gtkChop I completed the testing and found a few issues:

**1. Remove the (required) from all fields where is currently added. Only the red asterisk should mark the required fields.**

**2. When you try to submit a new publisher account without filling any fields only 1 field is highlighted as missing** 
**Steps to reproduce:**
- Open https://staging.iatiregistry.org/register_publisher/
- Do not fill any fields
- Click Create Publisher button
- Only the Contact Email is highlighted as a missing field, we want to highlight all required fields with red and mark them missing

**3. When you fill in missing required fields the Missing value error message doesn't disappear**
**Steps to reproduce:**
- Open https://staging.iatiregistry.org/register_publisher/
- Fill in only a few required fields
- Click Create Publisher button
- 'Missing value' is displayed on the remaining required fields
- Now fill in all required fields and add an invalid email address to the Contact Email field
- Click Create Publisher
- The Missing Value error messages are still displayed, it is not clear that the email address is invalid format. We want all Missing Value fields to disappear and show an Invalid Email address error message for the Contact Email

**4. 'Missing value' error message should be changed to 'Please fill required field'**

**5. All group header names are misaligned, should be inside the coloured box**
![image](https://user-images.githubusercontent.com/74558657/135267793-0b42c1fb-ca2a-4f96-aa83-476430bffa3a.png)


**6. When an incorrect email address is entered the error message is not attached to the textbox and it's not marked with red, please see the screenshot below.**
![image](https://user-images.githubusercontent.com/74558657/135267885-21c2b7fc-ef71-4d67-bd79-e69240cf6055.png)


**7. Add 'Please Select' as the first option in the Type drop-down and mark this field required**

**8. The order of the fields do not follow the order from '3. Regroup fields meaningfully; name groups and fields meaningfully.'**

**9. The fields should be renamed according to the requirements from '3. Regroup fields meaningfully; name groups and fields meaningfully.'** e.g. Type should be renamed Publisher Type

**10. Update help text of the 'Frequency of publication' field from 'How often is IATI data refreshed?' to 'How often is IATI data refreshed? IATI recommends refreshing the data at least quarterly.'**

**11. Update the help text of the field Publisher Name from 'The Name of the Organisation publishing the data. to 'The Name of the organisation publishing the data.'**

**Comment by gtkChop** [comment]
@andreaszenasidi Fixed.

**Comment by andreaszenasidi** [comment]
@gtkChop Looks good. Thanks!
