### ISSUE TITLE
Add validation status to the IATI Registry

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#352]
****WARNING:** Needs  to be deployed together with https://github.com/IATI/ckanext-iati/issues/365, https://github.com/IATI/ckanext-iati/issues/381 and https://github.com/IATI/ckanext-iati/issues/390**

As an IATI publisher, I want to see the IATI Validator's validation status of my datasets so that I am aware of if my datasets contain errors that I need to fix.

**Acceptance criteria**
1. **Functional Criteria**
1.1. A publisher logged in their publisher account when they select the **Datasets** tab, they should see each published dataset IATI Validator's validation status (see screengrab below for the location). The list of Validation statuses include:
- Success (text color: #18bc9c)
- Warning (text color: #ff7264)
- Error (text color: #f73357)
- Critical (text color: #a66ee9)

![image](https://user-images.githubusercontent.com/74558657/156181509-f4f9fe39-f440-4a9a-95d4-14bbb0bff6c6.png)

1.2. A publisher logged in their publisher account when they click the Validation Status text a new tab should open taking them to the dataset's IATI Validator Report.
1.3. An IATI user without a Registry account when they select the **Datasets** tab of a publisher, should be able to see the validation status and link as described in Functional Criteria 1.1. and 1.2.
1.4. A publisher logged in their publisher account when selecting to view the **Metadata** of a dataset should see the Validation Status as a new metadata field (see screengab below).
![image](https://user-images.githubusercontent.com/74558657/156188379-3127c7d7-2d1e-49eb-b9cf-d482d50fe654.png)
1.5. An IATI user without a Registry account when selecting to view the **Metadata** of a dataset should see the Validation Status as a new metadata field as described in Acceptance Criteria 1.4.
1.6. A publisher logged in their publisher account when selecting to edit the **Metadata** of a dataset should not see the Validation Status as an option in the form.
1.7. The Validation Status of the datasets should be checked for an update every time the dataset is updated (the _IATI data updated_ metadata field changes).

_**Technical note:**_ the [IATI Validator API](https://developer.iatistandard.org/api-details#api=iati-validator-v2&operation=get-pub-get-repor) returns each datasets validation status and link to the validation report.

**Comment by adrianoamaral** [comment]
Request: https://api.iatistandard.org/validator/report[?id][&url][&hash]
 @titi - Confirm what specifically are the parameter to be used at the API call: id, url, hash

**Comment by cormachallinanderilinx** [comment]
code is mostly done, there is some issues getting the status to display in the UI.
Found issues when testing this on staging

**Comment by Bjwebb** [comment]
@cormachallinanderilinx What happened with this? I don't see it on live or staging at the moment.

**Comment by cormachallinanderilinx** [comment]
Hi @Bjwebb 
It was decided in the end to just go with adding a link to the validation URL instead so it was replaced with this:
<img width="665" alt="image" src="https://github.com/IATI/ckanext-iati/assets/106073237/206fffe9-9d6b-40e5-8c37-3202339621e9">

It was decided in this issue: https://github.com/IATI/ckanext-iati/issues/398

**Comment by Bjwebb** [comment]
Thanks, I'll therefore close this issue.
