### ISSUE TITLE
Publisher license enhacement

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#353]
Quite a lot of publishers choose 'Other' as a license during registration. On the registration form, we want to highlight the most commonly used one and encourage using an open data license.

**Requirements:**
- Update the information on the License field to:
_License under which your data is being published. IATI is an open data standard, thus requires you to make your data available under an open licence so it can be freely used. One of the most frequently used license is Creative Commons Attribution. For more information on IATI's licensing guidelines go to [How to license your data](https://iatistandard.org/en/guidance/standard-overview/preparing-your-organisation-data-publication/how-to-license-your-data/)._

**Comment by gtkChop** [comment]
@andreaszenasidi 

Less than 0.5 days (deployment)

**Comment by gtkChop** [comment]
@andreaszenasidi 

Done. Please see staging. If good I will deploy to prod

**Comment by andreaszenasidi** [comment]
@gtkChop I made a mistake in the text, forgot an _S_. Could you please update the text to the following:

_License under which your data is being published. IATI is an open data standard, thus requires you to make your data available under an open licence so it can be freely used. One of the most frequently used licenses is Creative Commons Attribution. For more information on IATI's licensing guidelines go to [How to license your data](https://iatistandard.org/en/guidance/standard-overview/preparing-your-organisation-data-publication/how-to-license-your-data/)._

Otherwise, everything looks good. This should go live only when all UX Enhancement tickets are done. They should be deployed together.

**Comment by gtkChop** [comment]
@andreaszenasidi Updated text in staging

**Comment by gtkChop** [comment]
@andreaszenasidi 

Yes, because I was working on feature: #324 

UX enhancement is redeployed now in staging. Thanks
