### ISSUE TITLE
CSV upload bug - remove byte order mark (BOM)

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#354]
When the CSV file is converted/saved from the excel file byte order mark (**\xef\xbb\xb**) gets introduced to the beginning of the data. This new set of characters causes failure in recognizing the column.

E.g. The column name (first row) will be 

```
['\xef\xbb\xbfregistry-publisher-id', 'registry-file-id', 'title', 'description', 'contact-email', 'source-url', 'file-type', 'recipient-country', 'default-language', 'secondary-publisher']
```

**Comment by gtkChop** [comment]
@AudreyIATI 

Thanks for bringing up this issue. This is the same problem as before (BOM - see description). I have fixed the problem and deployed it to prod.  Please let me know if you encounter this issue again. Thanks

**Comment by gtkChop** [comment]
@AudreyIATI 

Thanks for bringing up this issue. This is the same problem as before (BOM - see description). I have fixed the problem and deployed it to prod.  Please let me know if you encounter this issue again. Thanks

**Comment by AudreyIATI** [comment]
Thank you for fixing, I'll update the publisher now.
For future reference is there anything they need to change in their publishing process to avoid this error happening again?

**Comment by gtkChop** [comment]
@AudreyIATI 

Theoretically, it should work fine without any problem from now on.

**Comment by AudreyIATI** [comment]
OK great - thanks again. 
I'll wait to see that they are able to upload successfully and if so, will close this issue.

Audrey

**Comment by AudreyIATI** [comment]
Hello again - I can confirm that the publisher was able to publish without further issues.
Thanks again for your help.

Audrey
