### ISSUE TITLE
Send notification emails when a pending publisher account gets updated

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#357]
Add new functionality to send a notification email to the IATI Helpdesk (support@iatistandard.org) when a Pending publisher account is updated.

A notification email should be sent when **ALL** the following criteria are met:
- Publisher account is in Pending status
- User who updates the Publisher is a Member of the publisher account (not sysadmin)
- One of these fields are updated: Publisher Id, IATI Organisation identifier, Email, Website or License. When a user updates multiple fields, it is ok to send multiple emails.

Question:
- How much work is required to implement this feature?

**Comment by Bjwebb** [comment]
We're not currently planning on looking into this feature.
