### ISSUE TITLE
Automatically generate API Key for new user accounts

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#358]
When new user accounts are created the API Key is not getting generated automatically. 

**Expected behaviour**
1. When a new user registered via the _Register_ button the API Key should be automatically generated for them
2. When a sysadmin adds a new member to a publisher using the below screen the new user should have an automatic API key generated for them
![image](https://user-images.githubusercontent.com/74558657/119489865-0f81cf00-bd54-11eb-9ea9-9320171bd8a6.png)

**Comment by gtkChop** [comment]
@andreaszenasidi 

This is the core functionality. I don't see any bug here. 

User/sysadmin should generate API key, key will not be generated automatically for a new user. (Either through register or new members of the publisher)

User page -> Manage -> Regenerate API key

**Comment by gtkChop** [comment]
Enhancement: Generate API key automatically.

**Comment by andreaszenasidi** [comment]
This request is not relevant anymore. We are transitioning from API Keys to API Tokens. More info on the change can be found on [IATI Connect](https://iaticonnect.org/group/9/discussion/proposal-iati-registry-api-users-registry-api-authentication-switch-api-key-api).
