### ISSUE TITLE
Organisation IDs in registry metadata are not unique

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#362]
For example, publishers simone_sympany and humana_houben both use the same organisation identifier

Same issue raised here: https://github.com/codeforIATI/iati-data-bugtracker/issues/19

…and mentioned here: https://github.com/IATI/ckanext-iati/issues/128#issuecomment-317987006

Organisation IDs on the registry not being unique is a problem, because it prevents them from being used as a key. #363 is a related problem.

---

### Explanation of the issue

Publishers [Sympany+](http://iatiregistry.org/publisher/simone_sympany) and [Stichting Humana](https://iatiregistry.org/publisher/humana_houben) are both using org ID `NL-KVK-30285304` in their registry metadata, and in their IATI data too.

### URLs / screenshots

 * http://iatiregistry.org/publisher/simone_sympany
 * https://iatiregistry.org/publisher/humana_houben

**Comment by andreaszenasidi** [comment]
@andylolz thanks for raising this. We couldn't get in touch with the publishers, unfortunately, thus we won't be able to amend their IATI org identifiers. Their data is quite old from 2015 and it's in version 1.03 and 2.01 therefore it should be a minimal impact on data users.

**Comment by andylolz** [comment]
> Their data is quite old from 2015 and it's in version 1.03 and 2.01 therefore it should be a minimal impact on data users.

Okay, I have reworded the title of the issue to make it clearer what the more general problem is here. The specific example doesn’t directly affect data users, but the general problem affects tools that use IATI data.

**Comment by andreaszenasidi** [comment]
@andylolz thanks for making the change. I checked the current publishers and these two are the only ones at the moment that have duplicate IATI org ID's. Are you aware of other ones by any chance?

The Registry publisher registration form now includes a validation check and doesn't allow new publishers to reuse an existing org ID, thus this issue shouldn't occur again.

**Comment by andylolz** [comment]
> Are you aware of other ones by any chance?

Nope, there aren’t any others.

> The Registry publisher registration form now includes a validation check and doesn't allow new publishers to reuse an existing org ID, thus this issue shouldn't occur again.

Great to know that there’s validation on the form. I believe these values can also be modified via the API – is that right? If so, does the validation also apply there?

**Comment by andreaszenasidi** [comment]
@andylolz thanks for confirming that there aren't other duplicates. 
You are correct that you can create a new publisher or update an existing one via the API, but I don't know what checks are done for the Org ID field.  

@gtkChop Could you please let us know if there is any validation done for the **organization_create** and **organization_update** endpoints _publisher_iati_id_ field to avoid duplications?

**Comment by andylolz** [comment]
Nice – I just tried via the API, and got the following error message:

```
IATI identifier already exists. Please verify if your organisation already has a publisher account.
```

So that is working I think.

**Comment by gtkChop** [comment]
Maybe these are the ones added before the validators. I can see the validators here

https://github.com/IATI/ckanext-iati/blob/master/ckanext/iati/plugins.py#L149

publisher_iati_id is supposed to be unique and there is a validation for the same.

**Comment by andreaszenasidi** [comment]
@gtkChop thank you for checking!
