### ISSUE TITLE
Organisation IDs and registry IDs are mutable, but changes are not tracked publicly

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#363]
This is a problem when attempting to use either field as a key.

Ideally, one or both fields would be immutable. Alternatively, changes could be publicly tracked.

**Comment by andreaszenasidi** [comment]
@andylolz thanks for raising this. This seems to be a duplication of https://github.com/IATI/ckanext-iati/issues/324

**Comment by andylolz** [comment]
Apologies, you're right. My mistake - I'll close this one.

**Comment by andylolz** [comment]
Apologies, you're right. My mistake - I'll close this one.
