### ISSUE TITLE
Change user role from Admin to Editor

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#364]
One of the publishers is trying to change their Members user role from Admin to Editor (note that they have 2 admins and only 1 role changes to Editor). I can't find a way to do this when I edit their Members page. If I click the Tool icon (see screengrab below), it takes me to the Add Member page where if I select the username and new role it gives me a 404 error. This is happening on the Live environment, in Staging, I am able to update the role successfully.

![image](https://user-images.githubusercontent.com/74558657/123290470-38d77b80-d509-11eb-8aad-ded23c9c5cc7.png)

@gtkChop Due to the sensitivity of information regarding the user accounts, I can't share their email address here, if needed I can send you an email.

**Comment by gtkChop** [comment]
@andreaszenasidi 

Fixed. Please test this. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop in Staging works, but on live, the Role dropdown list is greyed out and I am not able to change the role to Editor. I am logged in as a sysadmin.

**Comment by gtkChop** [comment]
@andreaszenasidi 

I can change the role with sysadmin access.

may I know what access and publisher are you trying on?

**Comment by andreaszenasidi** [comment]
@gtkChop my bad, I was trying to change the role of the user I was logged in as. I tried a different user and it works.
