### ISSUE TITLE
GSMA Foundation dataset XML error

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#367]
The [GSMA Foundation](https://iatiregistry.org/publisher/gsma_foundation) is trying to publish a [dataset](https://iatiregistry.org/dataset/gsma_foundation-org) that is a valid IATI XML file according to the [IATI Validator](https://iativalidator.iatistandard.org/). However, the Registry gives an **XML error, the file is an HTML document**. 

Why does the Registry give this error when the dataset is valid?

**Comment by gtkChop** [comment]
@andreaszenasidi 

```
u'<!DOCTYPE html>\n<html>\n  <head>\n    <title>403 This User Agent is  banned from this site.  Please contact via a different client configuration if you believe that this is a mistake.</title>\n  </head>\n  <body>\n    <h1>Error 403 This User Agent is  banned from this site.  Please contact via a different client configuration if you believe that this is a mistake.</h1>\n    <p>This User Agent is  banned from this site.  Please contact via a different client configuration if you believe that this is a mistake.</p>\n    <h3>Guru Meditation:</h3>\n    <p>XID: 820285886</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n'
```

When the archiver tries to access the dataset, this is the response. Hence it is not a valid XML file.


Reason: 'User-Agent': "curl/7.35.0" is banned.

We can change the user agent, but not sure what other datasets will allow the new user agent.

**Comment by andreaszenasidi** [comment]
@gtkChop thank you for looking into this so promptly! I agree that changing the archiver user agent is not the best idea. I will inform the publisher to allow the archiver user agent curl/7.35.0.

**Comment by andreaszenasidi** [comment]
@gtkChop the publisher decided to host the dataset somewhere else. The new dataset looks fine: https://iatiregistry.org/dataset/gsma_foundation-org2 The old dataset will be marked Private.
