### ISSUE TITLE
Request of list of publishers with contact emails

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#368]
Currently, the CSV with the list of publishers does not contain the main contact email address of the publishers.

Could you please pull the list of all publishers from the Registry with their main contact email address?

**Comment by jodiegardiner** [comment]
Hi @andreaszenasidi,

Sure, this is no problem. Is there currently a fixed source location you are getting the csv you mention from or would you like me to generate a fresh one for sending via email? If the latter, which fields would you like included other than title and contact email?

**Comment by andreaszenasidi** [comment]
@jodiegardiner a fresh list would via email would be great. 

Would be good to have the following fields: Publisher Name, IATI Organisation Identifier, Publisher ID, Organization Type, Contact Email, HQ Country or Region
