### ISSUE TITLE
`/api/3/action/organization_list?all_fields=true` ignores `limit` param

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#371]
I mentioned this problem in https://github.com/IATI/ckanext-iati/issues/333#issuecomment-902615331, but I can’t reopen that ticket.

https://iatiregistry.org/api/3/action/group_list?all_fields=true&limit=2
…returns 1715 results. It should only return 2. I think the limit param is being ignored? Rather than falling back to the default (25 results) it’s attempting to return all results.

I think that’s also why this no longer works:
https://iatiregistry.org/api/3/action/organization_list?all_fields=true&include_extras=true&include_tags=true&include_groups=true&limit=50

It 504s, presumably because it’s trying to process a really large request. With a limit of 50, this previously worked fine.

This stopped working sometime in the last 2 weeks.

**Comment by andylolz** [comment]
The documentation for this route is here:
https://iatistandard.org/en/iati-tools-and-resources/iati-registry/iati-registry-api/publisher-endpoints/#ListPub

In the `limit` param description, it says:
> It's not recommended to use all_fields=true

Can I suggest moving this text so it’s in the `all_fields` param description instead? Also, would you consider referring to this parameter as "deprecated" rather than saying its use is not recommended?

**Comment by AudreyIATI** [comment]
@gtkChop Tagging you just in case you hadn't already seen Andy's message above.
Let me know if you need anything from me.

**Comment by gtkChop** [comment]
@andylolz @AudreyIATI @andreaszenasidi 

This is fixed. Please let me know if you have any questions. Thanks

**Comment by andylolz** [comment]
Looks good – thank you!
