### ISSUE TITLE
Registry API Authentication switch from API key to API token

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#376]
### Issue & Solution
The IATI Registry API authentication is currently done using the API key. The API key is UUID which is normally used to authorize a user. The API key is not URL safe (that is, passing a key to the API  is not safe) and anyone with this API key can access the system.

Whereas the API token is an encoded, complex string that contains user data, which is URL safe and is the Internet standard for API’s. Moreover, it can be configured with an expiry time, which ensures more safety to the system. It's common practice to use an API token rather than an API key.

For this reason, CKAN, the underlying system of the IATI Registry, recommends using API tokens for authentication. Tokens are encrypted keys that can be generated manually from the UI or using the api_token_create() API function. A user can create as many tokens as needed, and revoke tokens at any time. When a new token is generated this will not be visible after its creation, thus nobody will be able to gain access to the token.

We want to improve the security of the Registry API by encouraging the Registry API users to start using the API tokens for authentication since they are considered the standard practice for HTTP-based APIs. The API token generation is already part of the IATI  Registry UI, as well as the API, thus the API users can start using this feature right away. 

The Registry UI will go through a change whereby the API key generation and key display will be removed and users will be required to navigate to the existing API token tab to generate their tokens.

The Registry API authentication will still support the legacy API keys, but its use is discouraged.

### Requirements
**1. Remove the API Key section from the user account right panel**
![image](https://user-images.githubusercontent.com/74558657/142009505-85df794f-6482-4238-967a-711f59562b32.png)

**2. Add description text**
Add the below text to the API tokens page (https://iatiregistry.org/user/.../api-tokens) before the **Name** label, as shown by the red line on the screengrab
_The API tokens are encrypted keys (strings) that identifies a user and can be used by applications to connect to the IATI Registry. Because of security reasons, after an API Token is generated, it needs to be copied right away since it won't be accessible again._ 

_If tokens are lost, a new token needs to be generated. There is no limit to how many tokens can be generated for a user._

_To revoke access to a token, click the red **x** button next to the relevant token._
![image](https://user-images.githubusercontent.com/74558657/142015110-39dda8f5-1e98-4a88-bde4-13405445a00a.png)

**Comment by gtkChop** [comment]
@andreaszenasidi 

Deployed. Please let me know if any changes are required. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop this can't be deployed yet. Please revert this change asap. We had a release plan that needs to be followed for this issue.

**Comment by gtkChop** [comment]
@andreaszenasidi Done reverted.

**Comment by andreaszenasidi** [comment]
@gtkChop Thank you!

**Comment by andreaszenasidi** [comment]
@gtkChop could you please put this work in staging so I can test it before deployment?

The deployment of this ticket is scheduled for Thursday, December 16.

**Comment by adrianoamaral** [comment]
@andreaszenasidi now on staging for test

**Comment by gtkChop** [comment]
@andreaszenasidi done, in staging now.

I will deploy to prod soon if you are okay with it. Thanks

**Comment by andreaszenasidi** [comment]
Looks good @gtkChop!

**Comment by andreaszenasidi** [comment]
@gtkChop @adrianoamaral The Regenerate API Key is still visible on the user account page. 

**Staging:**
![image](https://user-images.githubusercontent.com/74558657/154298569-9d815c5c-8adf-48de-9d68-b4db1d70aee6.png)


**Production:**
![image](https://user-images.githubusercontent.com/74558657/154299058-64cf68ef-4fab-4aec-b9b6-7e7a7e112ce7.png)

**Comment by gtkChop** [comment]
@andreaszenasidi Fixed and in prod now.
