### ISSUE TITLE
Publisher information missing on IATI Registry

### ISSUE THREAD

**Issue by AudreyIATI** [IATI/ckanext-iati#379]
The following publisher has flagged an issue where the usual information is missing from their Activity File page in the IATI Registry.
Publisher is International Organisation for Migration - https://iatiregistry.org/dataset/iom-activity 

Strangely, if I click on "Manage" the meta data is visible.

Let me know if you need further information.

Thanks,
Audrey

Screen shot attached. The missing data is publisher type, publisher organisation type and publisher identifier

![image](https://user-images.githubusercontent.com/74548472/144071671-2ffbf0a2-7296-47b7-8a80-5467fe9fca8c.png)

**Comment by andreaszenasidi** [comment]
@gtkChop looks good to me, thanks.

@AudreyIATI you can let IOM know this was resolved.

**Comment by AudreyIATI** [comment]
Will do @andreaszenasidi - thank you!
