### ISSUE TITLE
Registry down?

### ISSUE THREAD

**Issue by siemvaessen** [IATI/ckanext-iati#380]
It seems the Registry service is down for the last 24 hours? This affects services depending on the Registry.

**Comment by andreaszenasidi** [comment]
@siemvaessen Thanks for opening the ticket. Derilinx was notified this morning.

**Comment by jodiegardiner** [comment]
The registry came under attack at 3am UTC from what appears to be a denial of service. Once we were full of morning coffee and had scrolled to the bottom of our Notifications about it, we added a blocker that now returns a 444 to the culprit user-agent. Logs now look fine.

**Comment by alexlydiate** [comment]
@jodiegardiner Many thanks for bringing the service back to stability in good time. From our perspective the responses we received appeared to be partial - you would hope that an API either works or does not work, where as we received 200 responses but with containing incorrect data. I'll join your call with @andreaszenasidi on the 5th January and we can see if we can find a solution to avoid a repeat - cheers. In the meantime, happy holidays :)
