### ISSUE TITLE
The Registry API package_show endpoint returns datasets of deleted orgs

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#382]
The Registry API **/package_show** endpoint returns datasets of deleted organisations. Some examples are below, they have "owner_org": null

E.g.
https://iatiregistry.org/api/3/action/package_show?id=wb-af-test1
https://iatiregistry.org/api/3/action/package_show?id=51ff835f-b746-40d2-8afd-b6c3a549488f

**Comment by gtkChop** [comment]
@andreaszenasidi 

Looks like these are old and test datasets. Please see below list of datasets with null owner org.

```
                  id                  |          name           | private | state  | owner_org |      metadata_created      
--------------------------------------+-------------------------+---------+--------+-----------+----------------------------
 87787537-2db0-44a4-b7aa-4afbf34d10a1 | thefreedomfund-org      | t       | active |           | 2016-03-24 13:42:22.332097
 51ff835f-b746-40d2-8afd-b6c3a549488f | aqphs-activities        | f       | active |           | 2018-08-01 08:59:49.337903
 2ff06896-3d8a-48e8-9337-0e3a75dfca0d | wb-af-test1             | f       | active |           | 2011-05-15 18:18:26.346905
 b55d0f10-eb5b-4a88-9b69-f463cdc11559 | testupload-afg          | f       | active |           | 2019-07-15 13:39:25.25444
 c0d1cbee-cdbe-4e70-8090-2bce6f7733e2 | testupload-ago          | f       | active |           | 2019-07-15 13:39:28.748452
 73ad08be-25d8-46c2-8d18-181c21a2cb54 | dttillp-smudidata       | t       | active |           | 2018-09-25 11:48:18.433291
 4008f48f-b9e1-4c2e-8e47-3928bf66a056 | my-test-publisher-3-org | f       | active |           | 2021-01-19 23:25:07.399494
```

**Comment by andreaszenasidi** [comment]
@gtkChop thanks for investigating. Please delete these datasets and could you make a change to the API endpoint to not return any datasets with empty owner_org?

**Comment by gtkChop** [comment]
@andreaszenasidi Update all the above datasets to deleted state (only sysadmin can see deleted dataset).

```
Please delete these datasets and could you make a change to the API endpoint to not return any datasets with empty owner_org
```

I wouldn't recommend this, because the above scenario should never occur, if it happens again we need to investigate further.

**Comment by andreaszenasidi** [comment]
@gtkChop thank you, sounds good.
