### ISSUE TITLE
Registry API package_search does not return data for xm-dac-3-1

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#384]
It was reported that the **package_search** does not return data when searching for publisher xm-dac-3-1 For other publishers data is returned.
 
Registry API endpoint returning data: https://iatiregistry.org/api/3/action/package_search?q=publisher_iati_id:dk-cvr-26487013 
Registry API endpoint that does not return data: https://iatiregistry.org/api/3/action/package_search?q=publisher_iati_id:xm-dac-3-1

**Comment by gtkChop** [comment]
@andreaszenasidi There is no organization with id: xm-dac-3-1

https://iatiregistry.org/publisher/xm-dac-3-1

**Comment by gtkChop** [comment]
@andreaszenasidi I am not sure we can search by publisher_iati_id. 

As far as I know we don't store publisher_iati_id on dataset level

**Comment by adrianoamaral** [comment]
Review with the users before close the issue or some amendment
