### ISSUE TITLE
After reset password users can't login

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#389]
As a sysadmin I tried to set a temporary password for 2 users, 2 different publishers. 
1. **financeuk-6396**, publisher https://iatiregistry.org/publisher/peas 
2. **hapa-2083**, publisher https://iatiregistry.org/publisher/dca 

When I set their password I get a successful message that the password was set. However, when I try to login as this user it tells me 'Bad username or password'. I tried multiple times and in an incognito window as well, but still doesn't work. The end-user gets the same error message when she tries to login.

**Comment by gtkChop** [comment]
@andreaszenasidi Both the user status is pending. I guess they got an invite through an email and they never accepted it.

So when you add new members to the publisher through publisher edit page, the user gets an invite email.

I don't think its a bug. Thank you

**Comment by andreaszenasidi** [comment]
@gtkChop thanks for investigating. As a sysadmin we need to be able to reset even a Pending user's password since we get often requests that they did not receive the email to finish setting their account (they do check both their Inbox and Junk folders). Is it possible in CKAN to make this change?

Until then, could you please resend the email invite of the users **financeuk-6396** and **hapa-2083**

**Comment by andreaszenasidi** [comment]
I am closing this ticket, as discussed changing this functionality in CKAN is not feasible.
