### ISSUE TITLE
Add banner with Previewer and CSV Conversion tool deprecation warning to the IATI Registry

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#395]
As an IATI Registry end user (both in a logged in and logged out state),
I want to see a banner in the IATI Registry warning me that the Previewer and CSV Conversion tools will be deprecated
so that I am aware they will be removed.

![image](https://user-images.githubusercontent.com/74558657/173302121-193e0024-4aee-4fa9-8440-6ecf23c37e41.png)

**Acceptance criteria**
1. **Functional Criteria** 
1.1. Given when I access the IATI Registry (any page)
       Then a banner is visible with a grey x icon and the following text:
**The IATI Previewer and the CSV Conversion Tools will be switched off and no longer available as of 16 December 2022. Please read [guidance](https://cdn.iatistandard.org/prod-iati-website/documents/IATI_Previewer_Deprecation_Guide.pdf) on alternative options for previewing your IATI data and [guidance](https://cdn.iatistandard.org/prod-iati-website/documents/CSV_Conversion_Deprecation_Guide.pdf) for using the IATI Datastore Search to access data in a CSV format.**

![image](https://user-images.githubusercontent.com/74558657/173303392-e51e778f-1655-4ba2-b601-231e6ce1e4e4.png)

1.2. Given when the user clicks the grey x button
      Then the banner should be removed for the current session.

**Comment by andreaszenasidi** [comment]
@adrianoamaral I finalized the text to be added to the banner, including the 2 links.

**Comment by cormachallinanderilinx** [comment]
Added PR for change: https://github.com/derilinx/ckanext-iati/pull/6
Changes on staging env: https://staging.iatiregistry.org/

**Comment by Bjwebb** [comment]
The banner was added.
