### ISSUE TITLE
Search Box to be added to Pending Publishers in the Registry 

### ISSUE THREAD

**Issue by titiolukole** [IATI/ckanext-iati#399]
As a user, I want to be able to search for pending publishers in the registry so that I can easily navigate through publishers that are yet to be approved. 

1. **Functional Criteria** Search box to be added to the pending publishers similar to the recent publishers tab

![image](https://user-images.githubusercontent.com/102729339/214537725-671e6496-8186-4d60-bf0e-addf32af3a7f.png)
![image](https://user-images.githubusercontent.com/102729339/214537765-f8613ec4-1bd7-4237-b91f-e017432e5242.png)

**Comment by cormachallinanderilinx** [comment]
Hi Titi,

These changes have been made to the staging site: 
- With Search Query: https://staging.iatiregistry.org/dashboard/mypublishers-pending?q=cormac
- Without Search Query: https://staging.iatiregistry.org/dashboard/mypublishers-pending

If this looks good to you I can push the changes out to production

**Comment by titiolukole** [comment]
Hi Cormac, @cormachallinanderilinx  

Thank you for sending this across, I have checked and tested and it looks good and works fine. It can be moved to Prod now. Also, what is the difference between both links though because they are both showing the search box. Am I missing something?

**Comment by cormachallinanderilinx** [comment]
HI Titi,

No, both links are for the search.
The first one just has a query in the link, to show after the search the link can be shared.
