### ISSUE TITLE
Existing datasets that don't end in XML cause the archiver to fail with the message: "Package resource(s) invalid"

### ISSUE THREAD

**Issue by akmiller01** [IATI/ckanext-iati#400]
**Brief Description**
First noticed on the WHO. All of their datasets fail archiver validation. Downloaded the files and manually validated them, and they seem fine. Only connection I can establish is that none of them end in `.xml` . Might be related to this issue, where the front-end UI validates for xml files only: https://github.com/IATI/ckanext-iati/issues/381

**Severity**
High

**Issue Location**
Some example URLs that seem to trigger this archiver failure:
- https://rsr.akvo.org/organisation/5844/iati-org/ from https://iatiregistry.org/dataset/asdap-org
- http://open.who.int/api/iatiFiles/iati-file-content/AFG from https://www.iatiregistry.org/dataset/who-afg
- https://pdb.cku.dk/iati/reportDMRU from https://iatiregistry.org/dataset/cku-all

All three can be validated straight from their respective URLs, and are all schema-valid, at the least:
![image](https://user-images.githubusercontent.com/2836840/234660090-e966a24c-1f4b-49bd-a091-71d71b4efdc3.png)

This also seems to affect XML files with parameters. E.g. "iati.xml?q=123"

Also created a SOLR query for the symptoms and there could be ~425 datasets failing for similar reasons, but some of them seem to be legitimately failing: https://iatiregistry.org/api/3/action/package_search?q=extras_issue_type:archiver-failed%20AND%20extras_issue_message:%22Package%20resource(s)%20invalid%22

**Steps to Reproduce**
1. Go to https://www.iatiregistry.org/dataset/who-afg
2. See error

**Expected Results/Behaviour**
I would expect the form validation from https://github.com/IATI/ckanext-iati/issues/381 to only affect validation at the point of data entry (e.g. on the form UI or at the point of publishing via API).

**Actual Results/Behaviour**
The validation appears to be affecting otherwise valid IATI URLs that were added to datasets prior to this validation being in place.

**Comment by akmiller01** [comment]
FYI, I suggested to the WHO that as a work-around, they could add a hash to the end of their URLs, like `#.xml` to fool this validation step into thinking it was an XML file. That work-around worked for getting the Archiver to successfully run on their files: https://www.iatiregistry.org/dataset/who-afg

Therefore we can conclude that I was correct that the Archiver is failing because it's looking for URLs to end in `.xml`. But we need this behavior fixed for all publishers, because it's not convenient to add random hashes to the end of files for the sale of this validation step.

**Comment by cormachallinanderilinx** [comment]
Hi @akmiller01 

Apologies for the late reply.

It's seems the archer triggers dataset update under the hood which calls the schema update which is where the validations are.

We are looking at the best options to fix this.

The best is to look at the dataset resource using `requests.head()` and check that xml is returned.
This will allow older datasets which are in xml format to run, if there are older datasets which are _not_ xml they will fail.

I want to make sure if we go with this solution, we are not sending sending too many requests in a short space of time.

If I this is viable and this sounds good to ye, I can go ahead and implement this?

**Comment by akmiller01** [comment]
Hi @cormachallinanderilinx ,

Unfortunately I think looking at the mime type through a HEAD request would probably open up another can of worms. Just experimenting with the WHO files, it looks like their API only allows GET requests:
```
curl -I http://open.who.int/api/iatiFiles/iati-file-content/AFG#.xml
HTTP/1.0 405 Method Not Allowed
Connection: close
Content-Length: 16
```

Ultimately, I'm not sure that the feature from https://github.com/IATI/ckanext-iati/issues/381 was possible without hindering other users of the Registry, and the best solution may just be to roll it back.

**Comment by cormachallinanderilinx** [comment]
Hi @akmiller01 

No problem, I will roll back these changes.

**Comment by cormachallinanderilinx** [comment]
yes, that sounds correct @akmiller01

**Comment by cormachallinanderilinx** [comment]
Hi @akmiller01 

Seems archiver didnt run.

We can run it manually?

**Comment by akmiller01** [comment]
Yes, if you can trigger a run manually, please do.

**Comment by cormachallinanderilinx** [comment]
Got this error after manually triggering.

![Screenshot 2023-05-10 at 14 03 25](https://github.com/IATI/ckanext-iati/assets/106073237/bf948fcb-cd07-4db5-8c2e-8aaa7d35d913)

From the logs:
`ERROR [ckanext.iati.archiver] Error downloading resource for dataset who-afg: HTTPConnectionPool(host='open.who.int', port=80): Read timed out. (read timeout=100)`

**Comment by akmiller01** [comment]
Thanks for checking on that. I'm afraid it probably just means the archiver is misconfigured on staging, as the link is working fine:
```
$ wget http://open.who.int/api/iatiFiles/iati-file-content/AFG
--2023-05-10 14:10:51--  http://open.who.int/api/iatiFiles/iati-file-content/AFG
Resolving open.who.int (open.who.int)... 158.232.12.119
Connecting to open.who.int (open.who.int)|158.232.12.119|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6370323 (6.1M) [application/xml]
Saving to: ‘AFG.1’

AFG.1               100%[===================>]   6.08M   420KB/s    in 14s     

2023-05-10 14:11:07 (452 KB/s) - ‘AFG.1’ saved [6370323/6370323]
```

You might need to look into what's going wrong with the archiver on staging prior to testing this issue.

**Comment by cormachallinanderilinx** [comment]
Hi @akmiller01 
Yes, had some network errors.

The archiver has passed: 
![Screenshot 2023-05-11 at 09 51 34](https://github.com/IATI/ckanext-iati/assets/106073237/39e4d4dc-e87a-43d7-a849-c441b129cf95)

**Comment by cormachallinanderilinx** [comment]
Hi @akmiller01 
Are you happy for me to put these changes on to production?

**Comment by akmiller01** [comment]
Yes, please do.

**Comment by cormachallinanderilinx** [comment]
The changes are made

**Comment by siwhitehouse** [comment]
@akmiller01 Can we close this issue, please?
