### ISSUE TITLE
Invalid dataset upload format generic email

### ISSUE THREAD

**Issue by titiolukole** [IATI/ckanext-iati#401]
Hi Cormac, 

We had a user who received the following message below:

Dear matt-devinit,

You're receiving this email because you are the admin user of publisher_name's IATI Registry account.
We've detected an issue with the following IATI dataset in your IATI Registry account: publisher_registry_dataset_link
The dataset is not in a valid IATI XML format. Please see our [Guidance pages](https://iatistandard.org/en/guidance/publishing-data/creating-files/) on how to publish your data in IATI XML format.

Should you have any queries or support needs, then please email the IATI Helpdesk at: [support@iatistandard.org]support@iatistandard.org

We think this line of email should contain a variable rather than the piece of text highlighted ( admin user of publisher_name's IATI Registry account.

*Conversation has already taken place* 

Changes are currently on staging

Thanks, 
Titi

**Comment by cormachallinanderilinx** [comment]
Hi @titiolukole 

After removing the xml validation as part of [400](https://github.com/IATI/ckanext-iati/issues/400)
This email wont be sending again

**Comment by titiolukole** [comment]
That's great news Cormac. Thank you for the update!

Many thanks,


Titi Olukole | Business and data Analyst

Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK

T: +44 (0) 1179 272 505 | M: +44 (7480252441)



At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.

DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

________________________________
