### ISSUE TITLE
Emails from IATI Registry go to Spam

### ISSUE THREAD

**Issue by robredpath** [IATI/ckanext-iati#403]
**Brief Description**
Every email I've had from that IATI Registry has gone to my spam folder. Obviously that's not very helpful!

**Severity**
Medium

**Details**

<img width="1128" alt="Screenshot 2023-09-01 at 14 26 10" src="https://github.com/IATI/ckanext-iati/assets/641009/74d85da2-055e-4b24-80a1-285c3155a966">

Gmail isn't being particularly helpful with its error messaging, but I can understand why these emails might look like spam: email from a web hosting IP, no SPF/DKIM/DMARC, short message, high link-to-text ratio. 

@odscjames would SPF/DKIM (maybe not DMARC, actually) be any use? Can we set that up? 

Is there anything else we can do to improve deliverability? I think that for IATI Publisher we switched from direct email to using Amazon SNS - would that be an option here?

**Comment by odscjames** [comment]
> I think that for IATI Publisher we switched from direct email to using Amazon SNS - would that be an option here?

Yes and that sounds worth trying here (or a competitor). 

I heard a claim that Google recently got more strict with how they spam check, and generally I think not trying to send email ourselves unless we have a really good reason to is a good plan.

Tho this is really a Q for Derilinx

**Comment by robredpath** [comment]
@cormachallinanderilinx I'm not sure if you get notified about these issues, so here's a ping! @odscjames can help with any DNS changes if needed, or I'm sure would be happy to share details on what we did with IATI Publisher.

**Comment by cormachallinanderilinx** [comment]
We would be open to looking into some options for sending mails if it is becoming problematic.

Do you mean SNS or AWS SES?

**Comment by cormachallinanderilinx** [comment]
We can try out SES, it may have cost implications so i'm not sure how this might affect the contract? 
If so we may need to do the SPF/DKIM

**Comment by odscjames** [comment]
> is there any particular criteria that you'd use to choose between the options?

I'd ask @cormachallinanderilinx what extra features you need but I assume nothing fancy, just sending. In which case it's more about the services record and reputation on how well that actually deliver email. This is a case where it's easy to change service provider later, so a "try it and see" approach can be taken.

> how certain are we that just doing the various bits of DNS stuff won't be enough?

It might be enough but there is also things like ip-warming to consider. We could end up spending a lot of time on this, so I think a third party service has the potential to save us a lot of hassle here.

> We can try out SES, it may have cost implications

Can you say how many emails you send a month, just very roughly?

**Comment by cormachallinanderilinx** [comment]
I dont believe we need anything fancy, all emails are plan text mainly to alert when new publishers register and password resets

**Comment by odscjames** [comment]
Sounds like a very low quantity then - so I would expect a very low cost? https://aws.amazon.com/ses/pricing/

**Comment by cormachallinanderilinx** [comment]
Im working to get this on staging, I will then add it to production.
I might need support on production, if so I will update here

**Comment by siwhitehouse** [comment]
The plan is to implement SPF and/or DKIM. 

@cormachallinanderilinx do you have an update for us, please? We continue to miss new publisher emails as they are landing in spam inboxes, including those sent to the support@ email address

**Comment by cormachallinanderilinx** [comment]
Hi @siwhitehouse 

Going to implement with SES after talking with some of my team who are familiar with emails.

We have set up an SES identity for https://staging.iatiregistry.org/ 
When I mentioned testing on staging I forget we dont own the staging for IATI (like most our proejcts), would someone from your team be able to set up the DNS configuration?

I have the DNS record set ready to send on and how you would like me to transfer it to you/the team?

If its easiest for them to do it for production as well at the same time I can that configuration on as well?

**Comment by odscjames** [comment]
If you email me both at the same time I can set it up. james@ the same co-op domain as my colleagues.

**Comment by cormachallinanderilinx** [comment]
Changes have been pushed to production

**Comment by siwhitehouse** [comment]
We have left this running for a few weeks and checked that all emails are now going into the IATI Support mailbox
