### ISSUE TITLE
Move code from derlinx/ckanext-iati to IATI/ckanext-iati

### ISSUE THREAD

**Issue by cormachallinanderilinx** [IATI/ckanext-iati#404]
**Description:**
Move code from https://github.com/derilinx/ckanext-iati to https://github.com/IATI/ckanext-iati
We will also need to update all .gotmodules to point towards IATI/ckanext-iati instead of derilinx/ckanext-iati

**Goal:**
To update the .gitmodules file in this repository and move code to a new GitHub repository while ensuring that submodules are correctly configured.

**Additional Notes:**

Be cautious when moving code, especially if the existing repository is widely used, as this can potentially break other projects or workflows that depend on it.

Double-check that you have the necessary permissions to create a new repository and make changes to submodules.

Make sure to preserve commit history when copying code from the old repository to the new one, if applicable

**Comment by cormachallinanderilinx** [comment]
@siwhitehouse 
I create this issue, as mentioned in our class last week you would like me to start work on this item.

**Comment by siwhitehouse** [comment]
Thanks @cormachallinanderilinx. The move is properly described in the title but then reversed in the description. We want to host the code in IATI/ckanext-iati. Please do start on this as working on other issues is dependent on this being done.

**Comment by cormachallinanderilinx** [comment]
Started on this, my bad moved it to Todo instead of In Progress

**Comment by cormachallinanderilinx** [comment]
I have moved the code to iati/ckanext-iati
My development area is also pointing to iati/ckanext-iati so branches will be pushed to it and build will be built from it

**Comment by siwhitehouse** [comment]
This issue is closed with PR #405
