### ISSUE TITLE
Broken link on homepage

### ISSUE THREAD

**Issue by odscjames** [IATI/ckanext-iati#407]
**Description**
https://iatiregistry.org/ has a "datastore" link, in the "Search IATI Data" section. It goes to https://datastore.iatistandard.org/docs/ which 404's - can it go to https://datastore.iatistandard.org/ ?

(tho @robredpath may have thoughts on a better place?)

**Severity**
Medium

**Comment by robredpath** [comment]
Good spot -  https://datastore.iatistandard.org/ is good for now. 

The "someone wanting to start using IATI data" user journey is one that's going to be on my list, I think, but that's a little way off yet.

**Comment by cormachallinanderilinx** [comment]
PR created: https://github.com/IATI/ckanext-iati/pull/409

**Comment by cormachallinanderilinx** [comment]
This has been deployed to production

**Comment by Bjwebb** [comment]
Thanks!
