### ISSUE TITLE
IATI Recent Publishers List can't be downloaded

### ISSUE THREAD

**Issue by IsabelBirds** [IATI/ckanext-iati#424]
**Brief Description**
As an admin, I cannot download the recent publishers list 

**Severity**
Medium 

**Steps to Reproduce**

1. Be logged in as a sysadmin
2. Go to https://iatiregistry.org/dashboard/recent-publishers 
3. Click download list, csv
4. Get an "Internal server error" https://iatiregistry.org/dashboard/recent-publishers/download

**Comment by robredpath** [comment]
Given the timing, this may be an issue with the Python 2->3 upgrade.

**Comment by cormachallinanderilinx** [comment]
A fix has been pushed to production. 
Please let me know if there are any more issues

**Comment by IsabelBirds** [comment]
Thanks Cormac, tested on my end and also fixed for me.
