### ISSUE TITLE
Format of the publisher download endpoint has changed

### ISSUE THREAD

**Issue by markbrough** [IATI/ckanext-iati#426]
**Brief Description**
[Code for IATI Codelists](https://codelists.codeforiati.org/) collects codelists from a range of different sources and makes them available through a simple publicly-accessible interface. It is used to power a number of different services and tools, including Datastore Classic and CDFD.

One codelist, [ReportingOrganisation](https://codelists.codeforiati.org/ReportingOrganisation/), replicates the list of Publishers on the IATI Registry. It also makes publisher names available in a number of other languages (EN, FR, ES, PT). There is [a scraper](https://github.com/codeforIATI/codelist-updater/blob/main/importers/reporting_organisation.py) which accesses the following endpoint, and then puts the data into the IATI Codelist XML format:

https://iatiregistry.org/publisher/download/json

The format of this endpoint has changed. Previously, the organisation type and country were output as the labels. Now they are output as the codes.

For example, this data:
```json
{
    "Publisher": "Australia - Department of  Foreign Affairs and Trade",
    "IATI Organisation Identifier": "AU-5",
    "Organization Type": "10",
    "HQ Country or Region": "AU",
    "Datasets Count": 173,
    "Datasets Link": "https://iatiregistry.org/publisher/ausgov"
}
```

Was previously output as:
```json
{
    "Publisher": "Australia - Department of  Foreign Affairs and Trade",
    "IATI Organisation Identifier": "AU-5",
    "Organization Type": "Government",
    "HQ Country or Region": "Australia",
    "Datasets Count": 173,
    "Datasets Link": "https://iatiregistry.org/publisher/ausgov"
}
```

This change was made around 18th January -- as a result of this change, we have a large pending PR to this codelist:
https://github.com/codeforIATI/Unofficial-Codelists/pull/896

Before changing the scraper to follow the new approach, I thought it would be good to check if:
* this change was really intended
* whether the codes and labels (for `Organisation Type` and `HQ Country or Region`) could both be included in this endpoint?

Many thanks!

**Severity**
High - no new publishers will be captured in CDFD and possibly other tools until this codelist is fixed.

**Steps to Reproduce**
Add a list of actions needed to replicate the error.
1. Go to [https://iatiregistry.org/publisher/download/json](https://iatiregistry.org/publisher/download/json)
2. See that the organisation type for the first item is `10`

**Expected Results/Behaviour**
Consistent endpoint

**Actual Results/Behaviour**
Inconsistent endpoint

**Comment by robredpath** [comment]
Thanks, @markbrough - this is likely related to #420 which we're reviewing the impact of now.

**Comment by cormachallinanderilinx** [comment]
A fix has been pushed to production. 
Please let me know if there are any more issues

**Comment by markbrough** [comment]
Looks good, thank you! The scraper has now run correctly:
https://github.com/codeforIATI/Unofficial-Codelists/pull/896
