### ISSUE TITLE
Right hand menu filters on publisher page do not work (500 error)

### ISSUE THREAD

**Issue by stevieflow** [IATI/ckanext-iati#427]
**Brief Description**
Using the right hand menu filters on a publisher page results in an error page
This seems to occur on all filters, regardless of publisher or filter

**Severity**
High

**Issue Location**

eg: https://iatiregistry.org/publisher/asdb

Right hand menu includes filters for 

- Source
- Recipient Country
- File Type
- 

Attempting to filter - by clicking on any listed item - results in a Internal server error page (500 error)

**Expected Results/Behaviour**

The datasets would be filtered by the chosen value

**Actual Results/Behaviour**

500 Internal Server Error

![Firefox_Screenshot_2024-01-30T10-08-29 739Z](https://github.com/IATI/ckanext-iati/assets/1209944/6776960a-6a84-4837-badf-c40f71ccb1e6)

**Comment by cormachallinanderilinx** [comment]
A fix has been pushed to production. 
Please let me know if there are any more issues

**Comment by stevieflow** [comment]
Thanks @cormachallinanderilinx - that looks to be fixed from my testing of the filters on live
