### ISSUE TITLE
Some CSV files have Python's bytes literal marker in the contents of the field

### ISSUE THREAD

**Issue by simon-20** [IATI/ckanext-iati#430]
**Brief Description**
Some fields in some CSV files on the Registry are enclosed in Python's bytes literal marker, `b''`, so that these fields appear as, e.g., `b'actual field contents here'`.

**Severity**
High

**Issue Location**
Files affected:

The list of publishers: https://iatiregistry.org/publisher/download/csv

The title field (maybe others) of the downloadable list of records for each publisher: https://iatiregistry.org/csv/download

And perhaps others.

**Steps to Reproduce**
Download the file.

**Expected Results/Behaviour**
Fields should not be enclosed in `b''`

**Comment by cormachallinanderilinx** [comment]
A fix has been pushed to production. 
Please let me know if there are any more issues
