### ISSUE TITLE
404s on home page

### ISSUE THREAD

**Issue by robredpath** [IATI/ckanext-iati#440]
A number of the links on https://iatiregistry.org return 404 or link to inappropriate content. 

## "Register a Publisher"
<img width="655" alt="Screenshot 2024-03-12 at 17 19 23" src="https://github.com/IATI/ckanext-iati/assets/641009/745183e6-d912-4b3c-a248-d01e88cdaa6a">

...should link to https://iatiregistry.org/register

## "Using IATI data"
<img width="592" alt="Screenshot 2024-03-12 at 17 20 00" src="https://github.com/IATI/ckanext-iati/assets/641009/52cfc574-d42f-4326-8365-d944cc44563a">

...should link to https://iatistandard.org/en/using-data/ 

## "How do I register my data?" & "How does the IATI Registry work?"
<img width="316" alt="Screenshot 2024-03-12 at 17 22 03" src="https://github.com/IATI/ckanext-iati/assets/641009/af36e876-07d8-49bd-a1be-261c75ec175f">

...can be removed

**Comment by robredpath** [comment]
@cormachallinanderilinx please can you take a look at this ?

**Comment by cormachallinanderilinx** [comment]
@robredpath 
Changes are on staging and PR here: https://github.com/IATI/ckanext-iati/pull/446

**Comment by robredpath** [comment]
Looks good to me @cormachallinanderilinx - please deploy to live

**Comment by cormachallinanderilinx** [comment]
deployed, we can close
