### ISSUE TITLE
Page 2 broken on user list

### ISSUE THREAD

**Issue by dan-odsc** [IATI/ckanext-iati#441]
Initial issue: Page 1, 3 and onwards are fine: https://iatiregistry.org/user/?q=&order_by=date&page=2https://iatiregistry.org/user/?q=&order_by=name&page=1 but Page 2 is broken https://iatiregistry.org/user/?q=&order_by=name&page=2

Could be an issue with a misconfigured user who happens to be on page 2. 

When we order by date (by changed the address directly) page 2 is no longer broken so this explanation seems correct https://iatiregistry.org/user/?q=&order_by=date&page=2

This issue is related to #416 

@robredpath please add any additional context.

**Comment by robredpath** [comment]
I've not been able to replicate this - it was first discussed a few weeks ago and seems to have fixed itself. I've tried paging through users and no luck. Possibly the user in question changed whatever broken, or we've accidentally fixed this with other bug fixes. 

I would suggest that we leave this for now, and come back to it if we see it again.

**Comment by dan-odsc** [comment]
Ok @robredpath thanks. 

Closing and can re-open if it crops up again.
