### ISSUE TITLE
New publisher emails not being received

### ISSUE THREAD

**Issue by siwhitehouse** [IATI/ckanext-iati#464]
**Brief Description**
We haven't been receiving new publisher emails for up to a week. We can see that new accounts have been created via IATI Publisher and these appear as pending in the Registry UI at https://iatiregistry.org/dashboard/mypublishers-pending

**Severity**
Critical

**Issue Location**
https://iatiregistry.org/dashboard/mypublishers-pending

**Steps to Reproduce**
Add a list of actions needed to replicate the error.
1. Go to https://iatiregistry.org/dashboard/mypublishers-pending
2. Search for 'Technische'

**Expected Results/Behaviour**
When this new publisher account was set up a new publisher email should have been sent to a list of users, including support@iatistandard.org. This didn't happen.

**Actual Results/Behaviour**
No emails were received. Addresses confirmed include support@ and two members of the support team who are sent these too.

**Comment by siwhitehouse** [comment]
@cormachallinanderilinx Can you look at this urgently, please? We need the emails to start being sent again and the ones that were missed too.

**Comment by cormachallinanderilinx** [comment]
Hi @siwhitehouse 
There is an issue without out SES which we are looking into. We trying to fix this ASAP

**Comment by siwhitehouse** [comment]
Hi @cormachallinanderilinx do you have an update? If we don't have an imminent could we discuss receiving a list of new, unapproved publishers so we can process them, please?

**Comment by cormachallinanderilinx** [comment]
Hi @siwhitehouse 
This should be now fixed.
I can also send you on a lost of unapproved publishers from the last week?

**Comment by cormachallinanderilinx** [comment]
Simon here is a list of all publishers with approval needed which were created in the last 3 weeks
https://iatiregistry.org/publisher/prag_corp
https://iatiregistry.org/publisher/triple_trade
https://iatiregistry.org/publisher/nl_tud
https://iatiregistry.org/publisher/clsz-org
https://iatiregistry.org/publisher/article_25
https://iatiregistry.org/publisher/ffh
https://iatiregistry.org/publisher/830123149
https://iatiregistry.org/publisher/240001090

**Comment by siwhitehouse** [comment]
Thanks @cormachallinanderilinx
