### ISSUE TITLE
IATI Registry - 404 error - non-standard characters in filename

### ISSUE THREAD

**Issue by siwhitehouse** [IATI/ckanext-iati#467]
**Brief Description**
We had an issue where the Registry returned a 404 error for a publisher's file. This was hosted on their own server (i.e. not using AidStream or Publisher) and the filename included multiple non-standard characters, shown below

`_IATIExport_%20(12).xml`

This file was taken down and, following advice from IATI Support, the publisher has uploaded a file with standard characters in its filename. The Archiver now reports "Verification complete without errors." when run manually and the problem no longer persists.

Renaming the file was not the only change made during this process. It is also notable that many publishers use non-standard characters in their filenames. It can't be assumed that the filename was the issue here, although it is a likely candidate we can investigate.

During the time this problem existed Derilinx were unable to identify the root cause of the issue with this publisher.

**Severity**
Medium

**Steps to Reproduce**
I'd like us to discuss how we try to reproduce this error. In the first instance could @cormachallinanderilinx let us know if there are any known issues with CKAN accessing files with the characters shown in our example filename, please?

Next, to discount this we should use a test account on IATI Registry staging site to register a file with this filename on a server we have access to and see if we can recreate the error.

I'd appreciate suggestions from @cormachallinanderilinx and @robredpath of any other steps we can take to investigate this. As it is now fixed we can't completely exclude the possibility that the 404 was returned because there wasn't a file at that address (although Support could view its Validator report during this time) or that the server mistakenly reported it as unavailable.

@cormachallinanderilinx I know you investigated this issue at the time. Could you detail what you did to try and identify the problem, please?

**Comment by odscjames** [comment]
> we can't completely exclude the possibility that the 404 was returned because there wasn't a file at that address

Several of us (including me) could directly view the file at the time, so we are pretty sure it was there.

Also may be relevant; there was an expired SSL certificate. Then there was briefly an self-signed one, then a working one. However I understand the tool was manually told to recheck the file after the SSL cert was corrected, and it was still erroneously reporting a 404.

**Comment by cormachallinanderilinx** [comment]
When looking into the issue I was trying to add some extra logging but it didnt tell me a lot as it was all 404 not found errors.
After thinking about it, is there a possibility that there is some firewall in place that prevents requests from accessing the file from outside the browser?
Or could it have been set that some custom headers are needed for this specific file

**Comment by siwhitehouse** [comment]
@odscjames @cormachallinanderilinx 
Do we have an update on this, please? If not, and with the error not repeating, is it better to close this issue or leave it open?

**Comment by cormachallinanderilinx** [comment]
@siwhitehouse I think we can close, it this issue repeats again we can re-open?
