### ISSUE TITLE
https://iatiregistry.org/api/3/action/organization_list problems?

### ISSUE THREAD

**Issue by odscjames** [IATI/ckanext-iati#469]
https://iatiregistry.org/api/3/action/organization_list is returning junk data. 2 identical lists of only 20 publishers

**Comment by odscjames** [comment]
@EricSoroos can you help?

**Comment by cormachallinanderilinx** [comment]
Hi @odscjames how many publishers are expected to return?

**Comment by odscjames** [comment]
All of them, so thousands.

**Comment by cormachallinanderilinx** [comment]
Hi @odscjames I have a fix on staging
This this looks more like what is expected: https://staging.iatiregistry.org/api/3/action/organization_list

**Comment by odscjames** [comment]
I think there should only be one result key, not 2 nested ones.

**Comment by cormachallinanderilinx** [comment]
Good catch, I made the update

**Comment by siwhitehouse** [comment]
Hi @cormachallinanderilinx - do you have an ETA for applying the fix, please? This affects live systems so at this point should we roll back the changes, do you think?

**Comment by cormachallinanderilinx** [comment]
Hi @siwhitehouse I am just testing the image build now.
I will have it deployed in next 5 minutes

**Comment by cormachallinanderilinx** [comment]
Changes are made

**Comment by odscjames** [comment]
Is the config limit ckan.group_and_organization_list_max set at 2000? Can that be higher? We are concerned it's missing some.

Also, is this the same set as before (eg before was it only approved ones, or some filter?)

**Comment by siwhitehouse** [comment]
@cormachallinanderilinx Can you rollback the changes and then fix this in less haste, please? There are other live tools that use this API.
